### ISSUE TITLE
No GERMAN language?

### ISSUE THREAD

**Issue by thxthx0** [benzino77/tasmocompiler#1]
Hi, REALLY GREAT tool! Thanks so much :)

I don't know if it's an issue, but I can't find the **German Language** in selection box?

Also 2Mbit selection would be great (e.g. for Shelly)

Thanks again.

**Comment by benzino77** [comment]
Thanks. I'm glad that youfind it usefull.

Fixed (new docker image available to download) - my bad.
For 2Mbit devices you can use "Sonoffs 1Mbit" memory layout. It won't harm your device ;)

**Comment by thxthx0** [comment]
BIG THX for your super fast fix :)

**Comment by benzino77** [comment]
Your welcome.
