### ISSUE TITLE
Warning! Ignore unknown configuration option `shared_libdeps_dir` in section [env:custom]

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#101]
With tasmocompiler 2.4.14 I got a warning

**_Warning! Ignore unknown configuration option `shared_libdeps_dir` in section [env:custom_**]

I checked that in /server/compile/platformio.ini there is a section

[common]
shared_libdeps_dir        = lib

Is it normal the warning?

Thanks.

**Comment by benzino77** [comment]
It's just a warning, nothing to worry about. If you want to get rid of this message delete this line: https://github.com/benzino77/tasmocompiler/blob/master/server/compile/platformio.ini#L48

**Comment by bovirus** [comment]
Thanks.
