### ISSUE TITLE
tasmocompiler 2.4.17 - Error using Gitpod

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#105]
@benzino77 

Error using Gitpod

failed to create containerd task: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/theia/supervisor\": stat /theia/supervisor: no such file or directory": unknown; last backup failed: workspace does not exist. Please contact support if you need the workspace data.
Please file an issue if you think this is a bug.

**Comment by benzino77** [comment]
It is not related to TasmoCompiler, there is something wrong with gitpod itself.

**Comment by bovirus** [comment]
@benzino77 

Very strange.

Before last changes in tasnocompiler I can compile with Gitpod.

Now can I run tasmocompiler if Gitpod didn't work?

**Comment by benzino77** [comment]
It is not related to TasmoCompiler, there is something wrong with gitpod itself.
Try to delete TasmoCompiler workspaces on gitpod and start new workspace by https://gitpod.io/#https://github.com/benzino77/tasmocompiler

Non è correlato a TasmoCompiler, c'è qualcosa di sbagliato in gitpod stesso.
Prova a eliminare gli spazi di lavoro TasmoCompiler su gitpod e avvia un nuovo spazio di lavoro da https://gitpod.io/#https://github.com/benzino77/tasmocompiler
