### ISSUE TITLE
Build "standard" tasmota builds with additional features

### ISSUE THREAD

**Issue by drtorchwood** [benzino77/tasmocompiler#110]
Hi, 

perhaps I just did not understand the manual correctly but I have a quite simple request. 
I want to get the tasmota-sensors build with addtional zigbee support. What is the easiest way to get the standard parameters for tasmota-sensors and then add the zigbee feature? I want to avoid to give every sensor device in the custom parameters.

**Comment by drhideg** [comment]
Use [BUILDS.md](https://github.com/arendst/Tasmota/blob/development/BUILDS.md) as a ruler.
Write each desired feature in to the custm parameters box leading with #define, somethin like these:

> #define USE_ENERGY_SENSOR
#define USE_I2C
#define USE_ADE7953

It can be a future improvement for this tool, to preselect features based on the precompiled ones.

**Comment by benzino77** [comment]
Sensors are divided by category in TC: Energy sensor, Air sensor, etc. 
You can crosscheck `user_config_override.h` file produced by TC with the link provided by @drhideg.

**Comment by benzino77** [comment]
@drtorchwood you can try to check zigbee support on features list and then in next step put `#define FIRMWARE_SENSORS`.
This should build the binary you want. There is also a description (from yesterday) what is included in particular features group you can select: [link](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md).

**Comment by Jason2866** [comment]
In general you cant customize predefined Tasmota binaries. You will run in compile errors or the changes you did are not there. This behaviour is as designed and wanted
For a customized build the base has to be Tasmota(32)

**Comment by bovirus** [comment]
https://github.com/benzino77/tasmocompiler/discussions/212#discussioncomment-993016

I created a fork by original repository.
Made the changes (pre-set #define FIRMWARE_LITE)
No error during compilation using the fork.
