### ISSUE TITLE
USE_MQTT_AWS_IOT_LIGHT 

### ISSUE THREAD

**Issue by harryd31** [benzino77/tasmocompiler#112]
I'm sure or not seeing how I can add the USE_MQTT_AWS_IOT_LIGHT feature when compiling a build.

**Comment by benzino77** [comment]
You can add features (not listed for selecting them) by "Custom parameters" step.
Just put `#define`'s there. Those parameters will be added at the end of `user_config_override.h` file.

**Comment by harryd31** [comment]
I used the code snippet I found on the website still seems not to work. Here is what I added to the user config ( not sure if I did something wrong)

#ifndef USE_MQTT_TLS
#define USE_MQTT_TLS
#define USE_MQTT_TLS_CA_CERT // Optional but highly recommended
#endif
#ifndef USE_MQTT_AWS_IOT_LIGHT
#define USE_MQTT_AWS_IOT_LIGHT
#endif
#ifdef USE_DISCOVERY
#undef USE_DISCOVERY
#endif

**Comment by benzino77** [comment]
As I can see it compiles well, so you have to give more information what seems to not work.

**Comment by harryd31** [comment]
The code I provided can just be added to the custom parameters step correct?

**Comment by benzino77** [comment]
Yes.

**Comment by harryd31** [comment]
Thank you very much, it seems the issue I’m experiencing is not the compiler. It seems to be socket is timing out
