### ISSUE TITLE
tasmotizer config option for i2c sensors

### ISSUE THREAD

**Issue by riker65** [benzino77/tasmocompiler#114]
Hi, need some help using tasmotizer. need to compline display and i2c sensors . But do not know which option to check for i2c Sensors as INA219. Thanks

so I need rules, i2c display, web, I2C sensor

Would this work?

Or did I miss anything?

Thanks T

**Comment by drhideg** [comment]
If you select Display support, it will include i2c support. For INA219 you need to add lines in the custom parameters box
```
#ifdef USE_INA219
  #undef USE_INA219
#endif
#define USE_INA219
```
You can add any feature/sensor from [here](https://github.com/arendst/Tasmota/blob/development/BUILDS.md) as described above.

**Comment by benzino77** [comment]
I think there should be additional group of features created - "Voltage and current sensors". In such situation you will just need to select display and voltage and current sensors on features step.

**Comment by benzino77** [comment]
... or add "Generic sensors" checkbox to include all others sensors which are not included in other sections.

**Comment by riker65** [comment]
ok thanks.
Is there an overview which use-options are covered with your checkboxes?
thanks a lot

**Comment by benzino77** [comment]
No there is not... but it should be. Let me think about it.
For now you can check [this link](https://github.com/benzino77/tasmocompiler/blob/master/src/components/AppStepper/FeaturesStep/AvailableFeatures.js)

**Comment by benzino77** [comment]
I have created features description [file](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md) which  includes informatioan which sensors are included in particular features group.
