### ISSUE TITLE
TasmoCompiler v3.1.5 not working correctly development 2.7.4 German

### ISSUE THREAD

**Issue by motorrad** [benzino77/tasmocompiler#120]
Hi there
TasmoCompiler v3.1.5 not working correctly development 2.7.4 German:

Processing firmware (platform: espressif8266@2.6.2; framework: arduino; board: esp01_1m)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 (2.6.2) > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 2.7.4+9 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.30000.201119 (3.0.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Converting tasmota.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain+, Compatibility ~ soft
Found 93 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ESP KNX IP Library> 0.5.2
|   |-- <EEPROM> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|-- <EEPROM> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266HTTPClient> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266httpUpdate> 1.3
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <JSMN JSON parser customized and optimized for ESP8266 and Tasmota> 1.0
|-- <Wire> 1.0
|-- <LinkedList>
|-- <Ticker> 1.0
|-- <Unishox Compressor Decompressor highly customized and optimized for ESP8266 and Tasmota> 1.0
|-- <UdpListener> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <PubSubClient> 2.7
|-- <IRremoteESP8266> 2.7.14
|-- <C2Programmer> 1.0.0
|-- <TasmotaSerial> 3.1.0
|-- <rc-switch> 2.6.2
|-- <stm32flash-1.0-tasmota>
|-- <TasmotaModbus> 1.2.0
|   |-- <TasmotaSerial> 3.1.0
|-- <LibTeleinfo> 1.1.3
|-- <Mutichannel_Gas_Sensor> 0.0.1
|   |-- <Wire> 1.0
|-- <Adafruit SGP30 Sensor> 1.2.0
|   |-- <Wire> 1.0
|-- <Adafruit CCS811 Library> 1.0.0
|   |-- <Wire> 1.0
|-- <FrogmoreScd30>
|   |-- <Wire> 1.0
|-- <Adafruit MAX31865 library> 1.0.1
|   |-- <SPI> 1.0
|-- <HPMA115S0 Arduino Library> 1.0.0
|-- <Adafruit MCP9808 Library> 1.1.2
|   |-- <Wire> 1.0
|-- <LOLIN_HP303B> 1.0.0
|   |-- <Wire> 1.0
|   |-- <SPI> 1.0
|-- <SPI> 1.0
Building in release mode
*** use provided user_config_override.h as planned ***
Compiling .pio/build/firmware/src/StackThunk_light.cpp.o
In file included from tasmota/my_user_config.h:904:0,
                 from tasmota/StackThunk_light.cpp:28:
tasmota/user_config_override.h:4:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pio/build/firmware/src/WiFiClientSecureLightBearSSL.cpp.o
In file included from tasmota/my_user_config.h:904:0,
                 from tasmota/WiFiClientSecureLightBearSSL.cpp:23:
tasmota/user_config_override.h:4:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pio/build/firmware/src/tasmota.ino.cpp.o
Generating LD script .pio/build/firmware/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/firmware/lib359/EEPROM/EEPROM.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiAP.cpp.o
In file included from tasmota/my_user_config.h:904:0,
                 from /tmp/Tasmota/tasmota/tasmota.ino:43:
tasmota/user_config_override.h:4:2: warning: #warning **** user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
In file included from tasmota/i18n.h:708:0,
                 from /tmp/Tasmota/tasmota/tasmota.ino:48:
tasmota/language/de_DE.h:466:0: warning: "D_ZIGBEE_NOT_STARTED" redefined [enabled by default]
 #define D_ZIGBEE_NOT_STARTED "Zigbee nicht gestartet"
 ^
In file included from /tmp/Tasmota/tasmota/tasmota.ino:48:0:
tasmota/i18n.h:525:0: note: this is the location of the previous definition
 #define D_ZIGBEE_NOT_STARTED "Zigbee not started"
 ^
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiClientSecureAxTLS.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiServer.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiServerSecureAxTLS.cpp.o
Archiving .pio/build/firmware/lib359/libEEPROM.a
Indexing .pio/build/firmware/lib359/libEEPROM.a
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiServerSecureBearSSL.cpp.o
Compiling .pio/build/firmware/lib5c2/ESP8266WiFi/WiFiUdp.cpp.o
Compiling .pio/build/firmware/lib9db/ESP8266WebServer/detail/mimetable.cpp.o
Compiling .pio/build/firmware/libbf1/esp-knx-ip-0.5.2/esp-knx-ip-config.cpp.o
Compiling .pio/build/firmware/libbf1/esp-knx-ip-0.5.2/esp-knx-ip-conversion.cpp.o
Archiving .pio/build/firmware/lib9db/libESP8266WebServer.a
Indexing .pio/build/firmware/lib9db/libESP8266WebServer.a
Compiling .pio/build/firmware/libbf1/esp-knx-ip-0.5.2/esp-knx-ip-send.cpp.o
Compiling .pio/build/firmware/libbf1/esp-knx-ip-0.5.2/esp-knx-ip-webserver.cpp.o
Compiling .pio/build/firmware/libbf1/esp-knx-ip-0.5.2/esp-knx-ip.cpp.o
Compiling .pio/build/firmware/lib428/ESP8266HTTPClient/ESP8266HTTPClient.cpp.o
Compiling .pio/build/firmware/lib3b2/ESP8266httpUpdate/ESP8266httpUpdate.cpp.o
Compiling .pio/build/firmware/lib755/jsmn-shadinger-1.0/JsonGenerator.cpp.o
Compiling .pio/build/firmware/lib755/jsmn-shadinger-1.0/JsonParser.cpp.o
Compiling .pio/build/firmware/lib755/jsmn-shadinger-1.0/jsmn.cpp.o
Compiling .pio/build/firmware/lib6fe/Wire/Wire.cpp.o
Archiving .pio/build/firmware/libcec/libLinkedList-1.2.3.a
Compiling .pio/build/firmware/lib7df/Ticker/Ticker.cpp.o
Indexing .pio/build/firmware/libcec/libLinkedList-1.2.3.a
Compiling .pio/build/firmware/lib44e/Unishox-1.0-shadinger/UnishoxStrings.cpp.o
Compiling .pio/build/firmware/lib44e/Unishox-1.0-shadinger/unishox.cpp.o
Archiving .pio/build/firmware/liba47/libUdpListener.a
Indexing .pio/build/firmware/liba47/libUdpListener.a
Compiling .pio/build/firmware/lib4bd/DNSServer/DNSServer.cpp.o
Compiling .pio/build/firmware/libd29/PubSubClient-EspEasy-2.7.12/PubSubClient.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/IRac.cpp.o
Archiving .pio/build/firmware/lib7df/libTicker.a
Archiving .pio/build/firmware/lib44e/libUnishox-1.0-shadinger
Indexing .pio/build/firmware/lib7df/libTicker.a
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/IRrecv.cpp.o
Indexing .pio/build/firmware/lib44e/libUnishox-1.0-shadinger
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/IRsend.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/IRtext.cpp.o
Archiving .pio/build/firmware/lib6fe/libWire.a
Archiving .pio/build/firmware/lib755/libjsmn-shadinger-1.0.a
Indexing .pio/build/firmware/lib6fe/libWire.a
Indexing .pio/build/firmware/lib755/libjsmn-shadinger-1.0.a
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/IRtimer.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/IRutils.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Airwell.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Aiwa.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Amcor.cpp.o
Archiving .pio/build/firmware/lib5c2/libESP8266WiFi.a
Archiving .pio/build/firmware/lib3b2/libESP8266httpUpdate.a
Indexing .pio/build/firmware/lib5c2/libESP8266WiFi.a
Indexing .pio/build/firmware/lib3b2/libESP8266httpUpdate.a
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Argo.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Carrier.cpp.o
Archiving .pio/build/firmware/lib428/libESP8266HTTPClient.a
Archiving .pio/build/firmware/lib4bd/libDNSServer.a
Indexing .pio/build/firmware/lib428/libESP8266HTTPClient.a
Indexing .pio/build/firmware/lib4bd/libDNSServer.a
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Coolix.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Corona.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Daikin.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Delonghi.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Denon.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Dish.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Doshisha.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Electra.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_EliteScreens.cpp.o
Archiving .pio/build/firmware/libd29/libPubSubClient-EspEasy-2.7.12.a
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Epson.cpp.o
Indexing .pio/build/firmware/libd29/libPubSubClient-EspEasy-2.7.12.a
Archiving .pio/build/firmware/libbf1/libesp-knx-ip-0.5.2.a
Indexing .pio/build/firmware/libbf1/libesp-knx-ip-0.5.2.a
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Fujitsu.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_GICable.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_GlobalCache.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Goodweather.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Gree.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Haier.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Hitachi.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Inax.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_JVC.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Kelvinator.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_LG.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Lasertag.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Lego.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Lutron.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_MWM.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Magiquest.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Metz.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Midea.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Mirage.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Mitsubishi.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_MitsubishiHeavy.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Multibrackets.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_NEC.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Neoclima.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Nikai.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Panasonic.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Pioneer.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_RC5_RC6.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Pronto.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_RCMM.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Samsung.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Sanyo.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Sharp.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Sherwood.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Sony.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Symphony.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Tcl.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Teco.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Technibel.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Toshiba.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Transcold.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Trotec.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Vestel.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Voltas.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Whirlpool.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Whynter.cpp.o
Compiling .pio/build/firmware/libebb/IRremoteESP8266-2.7.14/ir_Zepeal.cpp.o
Compiling .pio/build/firmware/lib80b/C2Programmer-1.0.0/c2.cpp.o
Compiling .pio/build/firmware/lib80b/C2Programmer-1.0.0/ihx.cpp.o
Compiling .pio/build/firmware/libf59/TasmotaSerial-3.1.0/TasmotaSerial.cpp.o
Compiling .pio/build/firmware/lib53f/rc-switch/RCSwitch.cpp.o
Compiling .pio/build/firmware/liba8c/stm32flash-1.0-tasmota/stm32flash.cpp.o
Compiling .pio/build/firmware/lib968/TasmotaModbus-1.2.0/TasmotaModbus.cpp.o
Compiling .pio/build/firmware/lib198/LibTeleinfo/LibTeleinfo.cpp.o
Compiling .pio/build/firmware/libb0d/Mutichannel_Gas_Sensor/MutichannelGasSensor.cpp.o
Compiling .pio/build/firmware/libeab/Adafruit_SGP30-1.2.0/Adafruit_SGP30.cpp.o
Compiling .pio/build/firmware/lib1ec/Adafruit_CCS811-1.0.0.14/Adafruit_CCS811.cpp.o
Compiling .pio/build/firmware/lib102/FrogmoreScd30/FrogmoreScd30.cpp.o
Compiling .pio/build/firmware/lib71f/SPI/SPI.cpp.o
Compiling .pio/build/firmware/libeea/Adafruit_MAX31865-1.1.0-custom/Adafruit_MAX31865.cpp.o
Compiling .pio/build/firmware/lib931/HPMA115S0/hpma115S0.cpp.o
Archiving .pio/build/firmware/libebb/libIRremoteESP8266-2.7.14.a
Compiling .pio/build/firmware/libb35/Adafruit_MCP9808_Tasmota/Adafruit_MCP9808.cpp.o
Indexing .pio/build/firmware/libebb/libIRremoteESP8266-2.7.14.a
Archiving .pio/build/firmware/lib80b/libC2Programmer-1.0.0.a
Archiving .pio/build/firmware/libf59/libTasmotaSerial-3.1.0.a
Indexing .pio/build/firmware/lib80b/libC2Programmer-1.0.0.a
Indexing .pio/build/firmware/libf59/libTasmotaSerial-3.1.0.a
Archiving .pio/build/firmware/lib968/libTasmotaModbus-1.2.0.a
Indexing .pio/build/firmware/lib968/libTasmotaModbus-1.2.0.a
Archiving .pio/build/firmware/libFrameworkArduinoVariant.a
Compiling .pio/build/firmware/lib1e7/LOLIN_HP303B/LOLIN_HP303B.cpp.o
Indexing .pio/build/firmware/libFrameworkArduinoVariant.a
Archiving .pio/build/firmware/lib53f/librc-switch.a
Compiling .pio/build/firmware/FrameworkArduino/Esp-frag.cpp.o
Indexing .pio/build/firmware/lib53f/librc-switch.a
Compiling .pio/build/firmware/FrameworkArduino/Esp-version.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/Crypto.cpp.o
Archiving .pio/build/firmware/lib1ec/libAdafruit_CCS811-1.0.0.14.a
Archiving .pio/build/firmware/libb0d/libMutichannel_Gas_Sensor.a
Indexing .pio/build/firmware/lib1ec/libAdafruit_CCS811-1.0.0.14.a
Indexing .pio/build/firmware/libb0d/libMutichannel_Gas_Sensor.a
Archiving .pio/build/firmware/liba8c/libstm32flash-1.0-tasmota
Archiving .pio/build/firmware/lib198/libLibTeleinfo.a
Indexing .pio/build/firmware/liba8c/libstm32flash-1.0-tasmota
Indexing .pio/build/firmware/lib198/libLibTeleinfo.a
Compiling .pio/build/firmware/FrameworkArduino/Esp.cpp.o
Archiving .pio/build/firmware/libeab/libAdafruit_SGP30-1.2.0.a
Indexing .pio/build/firmware/libeab/libAdafruit_SGP30-1.2.0.a
Compiling .pio/build/firmware/FrameworkArduino/FS.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/FSnoop.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/HardwareSerial.cpp.o
Archiving .pio/build/firmware/lib931/libHPMA115S0.a
Archiving .pio/build/firmware/libeea/libAdafruit_MAX31865-1.1.0-custom
Archiving .pio/build/firmware/lib102/libFrogmoreScd30.a
Indexing .pio/build/firmware/lib931/libHPMA115S0.a
Indexing .pio/build/firmware/libeea/libAdafruit_MAX31865-1.1.0-custom
Indexing .pio/build/firmware/lib102/libFrogmoreScd30.a
Compiling .pio/build/firmware/FrameworkArduino/IPAddress.cpp.o
Archiving .pio/build/firmware/libb35/libAdafruit_MCP9808_Tasmota.a
Archiving .pio/build/firmware/lib71f/libSPI.a
Compiling .pio/build/firmware/FrameworkArduino/MD5Builder.cpp.o
Indexing .pio/build/firmware/libb35/libAdafruit_MCP9808_Tasmota.a
Indexing .pio/build/firmware/lib71f/libSPI.a
Compiling .pio/build/firmware/FrameworkArduino/Print.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/Schedule.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/StackThunk.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/Stream.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/StreamString.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/Tone.cpp.o
Archiving .pio/build/firmware/lib1e7/libLOLIN_HP303B.a
Indexing .pio/build/firmware/lib1e7/libLOLIN_HP303B.a
Compiling .pio/build/firmware/FrameworkArduino/TypeConversion.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/Updater.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/WMath.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/WString.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/abi.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/base64.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/cbuf.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/cont.S.o
Compiling .pio/build/firmware/FrameworkArduino/cont_util.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_eboot_command.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_features.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_flash_quirks.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_flash_utils.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_i2s.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_main.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_noniso.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_phy.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_postmortem.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_si2c.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_sigma_delta.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_spi_utils.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_timer.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_waveform_phase.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_waveform_pwm.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_wiring.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_wiring_analog.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_wiring_digital.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_wiring_pulse.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_wiring_pwm.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/crc32.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/core_esp8266_wiring_shift.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/debug.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/flash_hal.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/gdb_hooks.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/heap.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/libb64/cdecode.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/libb64/cencode.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/libc_replacements.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/sntp-lwip2.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/spiffs/spiffs_cache.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/spiffs/spiffs_check.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/spiffs/spiffs_gc.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/spiffs/spiffs_hydrogen.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/spiffs/spiffs_nucleus.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/spiffs_api.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/sqrt32.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/time.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/uart.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/umm_malloc/umm_info.c.o
Compiling .pio/build/firmware/FrameworkArduino/umm_malloc/umm_integrity.c.o
Compiling .pio/build/firmware/FrameworkArduino/umm_malloc/umm_local.c.o
Compiling .pio/build/firmware/FrameworkArduino/umm_malloc/umm_malloc.cpp.o
Compiling .pio/build/firmware/FrameworkArduino/umm_malloc/umm_poison.c.o
Archiving .pio/build/firmware/libFrameworkArduino.a
Indexing .pio/build/firmware/libFrameworkArduino.a
Linking .pio/build/firmware/firmware.elf
/home/gitpod/.platformio/packages/toolchain-xtensa/bin/../lib/gcc/xtensa-lx106-elf/4.8.2/../../../../xtensa-lx106-elf/bin/ld: .pio/build/firmware/firmware.elf section `.text1' will not fit in region `iram1_0_seg'
collect2: error: ld returned 1 exit status
*** [.pio/build/firmware/firmware.elf] Error 1
========================= [FAILED] Took 35.84 seconds =========================

**Comment by drhideg** [comment]
It usually happens when you select too many feature/sensor. I think your needs should be narrowed down.
Can you give more information which feature you select and/or custom parameters you use?

**Comment by benzino77** [comment]
It's not a problem with the TasmoCompiler but with number of features you have selected. This tiny esp8266 board has limited amount of memory. Every feature in Tasmota consume a part of it (every release of Tasmota added new features, optimizations and address discovered bugs, so memory usage between Tasmota versions varies). Please have a look at #86 

You have three options:
1. deselect some features or
2. rethink the project and decide whether you can implement needed functionalities using more than one esp board or
3. `#undef` some features from features group in "Custom parameters" step

Ad. option 3
Lets say you have selected "Distance sensors" feature group. You can find which sensors are included in this group by checking [FEATURES_DESC](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md). You know that you will be using only SR04 distance sensor. In that case you can disable other distance sensors by entering:
```
#undef USE_VL53L0X
#undef USE_HRXL
#undef USE_DYP
#undef USE_VL53L1X
```
in the Custom parameters" step.

There is a small chance that it will release some memory for other features. If you want to combine "fat" features together, you have to choose option one or option two.

**Comment by motorrad** [comment]
Air/gas sensors
Amazon Alexa
Display Vcc
Energy sensors
IR basic
Rules
Timers
Web interface
RF transceiver
Temp/Hum sensors

Failed

**Comment by motorrad** [comment]
Air/gas sensors
Amazon Alexa
Energy sensors
Rules
Web interface

Working

**Comment by motorrad** [comment]
Seems that is the Reason why

**Comment by benzino77** [comment]
Display and IR support - those features are really "fat" in terms of memory.

**Comment by motorrad** [comment]
Air/gas sensors
Amazon Alexa
Display Vcc
Energy sensors
Rules
Timers
Web interface
RF transceiver
Temp/Hum sensors

Success :-)
