### ISSUE TITLE
Add volumes to DOCKERFILE to persist settings and gain access to created bin files

### ISSUE THREAD

**Issue by dkebler** [benzino77/tasmocompiler#130]
Poking around I can't seem to find where these files get created in container.

Anyway, it would be nice if the DOCKERFILE exposed some volumes for the `firmware` directory and also the `platformio.ini` and `user_config_override.h` files.  That way the settings can be persisted and also edited outside the container and the created bin files can be accessed without the download from the webUI.

```
app.get('/download/firmware.bin', (req, res) => {
  const firmwareFile = path.resolve(
    tasmotaRepo,
    'build_output/firmware/firmware.bin'
  );
  res.download(firmwareFile);
});

app.get('/download/firmware.bin.gz', (req, res) => {
  const firmwareCompressed = path.resolve(
    tasmotaRepo,
    'build_output/firmware/firmware.bin.gz'
  );
  res.download(firmwareCompressed);
});

app.get('/download/platformio.ini', (req, res) => {
  res.download(userPlatformioIni);
});

app.get('/download/user_config_override.h', (req, res) => {
  res.download(userConfigOvewrite);
});
```

**Comment by benzino77** [comment]
Why would one need to access those files inside docker container?
Settings will not be persisted because `platformio_override.ini` and `user_config_override.h` files are overwritten every time you hit _Compile_ button.

Anyway Tasmota source code is here: `/tmp/Tasmota` inside docker image.

**Comment by dkebler** [comment]
Ok, since exposed volumes are be ignored if not bound will you add to the DOCKERFILE?
`VOLUME /tmp/Tasmota/build_output/firmware`

Actaully I guess what I would like to load/persist is the  contents of custom parameters textbox field?  Is there a corresponding backend file for that field which is merged/appended into user_config_override.h before compilation?   If so can the directory where that lives also be mounted with VOLUME?

**Comment by benzino77** [comment]
`build_output/firmware` is created at the end of the compilation so I doubt docker will allow for that - to tell the truth I still don't get your use case.

There are only `platformio_override.ini` and `user_config_override.h` files created in version `v4.0.0-rc`.
Custom parameters textbox is appended at the end of `user_config_override.h`- you can download it at the end of compilation (by clicking on corresponding button) and then use it last part (custom parameters you've entered are appended at the end of that file) to copy-paste during the next compilation.

You can also use my docker image to build yours: 
```
FROM benzino77/tasmocompiler:4.0.0-rc
...
```
and do whatever you want.
