### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#135]
@benzino77

With latest build I see these warning

warning file-loader@2.0.0: Invalid bin field for "file-loader".
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader".

and when it finish to compile the browser open a web page but it's a blank.

**Comment by benzino77** [comment]
You have asked that couple months ago: #64

**Comment by bovirus** [comment]
@benizno77

The main problem is not the warning but the blank page in the web browser.

I doidn't see the fix for this in the article that you mentioned,

**Comment by benzino77** [comment]
TasmoCompiler does not open any web page! 
If you are using GitPod please read this issue carefully: #105

**Comment by benzino77** [comment]
... and I just noticed that this issue was also opened by you.

**Comment by bovirus** [comment]
I belieev that it was clear.

Tasmocompiler use gitpod to create the GUI.

I already done the try.
I delete the project in gitpod and I recreate a new project but I got the same error (new browser session with blank page).
No error during gitpod compilation (only warning) and after gipod complete compilation it page open new browser session but instead tasmocompiler web interface I got a blank page.

Tested with Google Chrome and Firefox on Windows 10 64bit,

Seome weeks ago I compiled a previous tasmocompielr version withe the same harwdare configuration without problem.

I will try later to checkj if it's a gitpod problem.

Thanks.

**Comment by benzino77** [comment]
I've checked three browsers. Everything **works as expected**. It is something on yours or as you suspect on GitPod side.
Try to clear cache/cookies/etc. on your browser. Eventually open new "Private Window" and from there go to GitPod site.

![brave](https://user-images.githubusercontent.com/15658235/112840878-21225f80-90a0-11eb-8ea9-993d07d6d5e9.png)
![chrome](https://user-images.githubusercontent.com/15658235/112840890-241d5000-90a0-11eb-9561-d2724aff321c.png)
![firefox](https://user-images.githubusercontent.com/15658235/112840902-28496d80-90a0-11eb-8951-bb8efdcdf0a7.png)

**Comment by bovirus** [comment]
Very strange.tested on 3 different computer.
 Same issues
![image](https://user-images.githubusercontent.com/1262554/112842210-9e9a9f80-90a1-11eb-92ef-2c9da4bae2c4.png)

![image](https://user-images.githubusercontent.com/1262554/112842332-ba9e4100-90a1-11eb-98df-d35400796587.png)

I will try again.

**Comment by bovirus** [comment]
It's smilar to the problem reported here

https://www.google.com/search?q=Gitpod+getting+blank&oq=Gitpod+getting+blank&aqs=chrome..69i57j69i60l3.350j0j4&sourceid=chrome&ie=UTF-8

**Comment by drhideg** [comment]
I don't know well Chrome but there are DevTools where you can check console and network output for errors if any.
Would you try browser without extensions?

**Comment by bovirus** [comment]
@benzino77 

Please re-open this issue.

No eeeror in teh console.
The problem is only wen you try to open web browser or open rpeview.
Nothing else.

Without gitpod extension isnot possible to compile it.

I etsetd not only with Chrome but also Firefox.
Same issues.
On several PC.

**Comment by benzino77** [comment]
**It is something on your side**. Here is the working GitPod on my Linux box (running Firefox). 

![linux-firefox](https://user-images.githubusercontent.com/15658235/112880293-8d19bd80-90ca-11eb-93af-8e7279690094.png)

As @drhideg mentioned: you should try disable your browser extensions (from the picture you posted its looks like you have a lot of them, but I would start with the GitPod browser extension itself)

![gitpod-extension2](https://user-images.githubusercontent.com/15658235/112880975-6dcf6000-90cb-11eb-850c-f162d9c86ce6.png)

**Comment by bovirus** [comment]
@benzino77 

**Please tajke that is not my personal issue.**

**Seems an issue about source code for all user that works on Windows.**

If I compile the same source under Linux it works fine.
The you and @drhideg compiled it udner Linux.
And this evening I tested that also in my Linux system it worked fine.
But any Windows system that i tested didn't work with same source code (updated vs previous version).
the previous version worked fien both with Windows and Linux.
Then probably same changes in source code break the Windows compatibility.

**Comment by bovirus** [comment]
I found several issues in 2021 about gitpd with Windows 10 and blank page like

https://community.gitpod.io/t/gitpod-getting-blank/2709

https://community.gitpod.io/t/workspace-wont-load-anymore/2684/6

https://github.com/gitpod-io/gitpod/issues/3114

**Comment by benzino77** [comment]
It works perfectly fine on Windows - first three screenshots I posted were from Windows 10.
Disable GitPod extension on your browser and try again. 


![gitpod-extension2](https://user-images.githubusercontent.com/15658235/112887842-ee925a00-90d3-11eb-87a9-21e8e20de3e5.png)

**Comment by bovirus** [comment]
@benzino.

I'm so sorry but I didn't understand your suggestion.

The Windows 10/Linux configuration is the same as in the past.
I loaded gitpod extension in Firefox and in Chrome (for both pltaform Windows and Linux).

The gitpod extension is mandatory to have the gitpod button If I open the github tasmocompiler repository.
Without gitpod extension I cannot laod/compile using gitpod.

With tasmocompiler 3.03 these configuration worked fine with both platform (Windows and Linux).

Without any changes inbrowser/Linxu/Windows configuration now version 4.0 works fine only on Linux.

In Windows 10, opening web browser, run gitpod from tasmocompiler github repository.
Using soruce 4.01 gitpod make all jobs without error then open anew page (port 3000).
But the openning page (tasmocompiler GUI is blank).
Note: in the past as Iexplained with 3.03 the same system worked fine.

With same PC in Linux, opening web browser, run gitpod from tasmocompiler github repository.
Gitpod make all jobs without error then open a browser new page (port 3000).
Then on Linux the tasmocmpielr GUI work fine.

Then now if I follow your suggestion and disable gitpod browser extension and I cannot see GITPOD button in github repository.

**Comment by benzino77** [comment]
> The gitpod extension is mandatory to have the gitpod button If I open the github tasmocompiler repository.
Without gitpod extension I cannot laod/compile using gitpod.

It is NOT mandatory! You don't have to have browser extension installed to run TasmoCompiler on GitPod.
Just click the link provided in the README or type this in your address field of your browser:
https://gitpod.io/#https://github.com/benzino77/tasmocompiler 
No browser extension is required!!

This is my last answer to your posts.

**Comment by drhideg** [comment]
You wont let us to help you, even it is out of the scope of this project.
Windows 10 20H2 (19042.870) Edge (Chrome inside), Crhome, Firefox all works well:
![Névtelen](https://user-images.githubusercontent.com/52567253/112954804-0a7f1580-913f-11eb-8c1c-14ad8eaa0e5c.png)

**Comment by bovirus** [comment]
@benzino77 

I'm so sorry but if you don't like that someone report an issue I'd like to avoid to do that.
As I explained 3.03 works fine in my Windows configuration without change nothing.
Then the problem is not gitpod extension (whty works with 3.03 source and not with 4.01)?

@drhideg 
Thanks for the report. It sound strange.
Tested on 5 different PCs (all with Windows 10 x64 updated at latest patches).
3 PC are on one kind of internet connect and other 2 on othe r connection type.
In all 5 PCs
- Tasmocompiler source 3.03 works fine
- Tasmocompielr 4.01 didn't GUI start fine (GUI blank page)

**Comment by drhideg** [comment]
If you start DevTools you got JS error on that blank page. Only Italian locale affected. Check this: https://github.com/benzino77/tasmocompiler/issues/134#issuecomment-809241685

**Comment by bovirus** [comment]
@drhideg 

Thanks for the report.
And what about tasmocompiler source code 3.03 in the same configuration works fine?

**Comment by drhideg** [comment]
You got that error beacuse of missing key:value pair in the translation. Maybe 3.0.3 does not contained that part (I am lazy to check date when that part added).

**Comment by bovirus** [comment]
@drhideg 

Thanks. 
Fixed issues and now itworks.
Very strange that Linux also with original Italian langiage without Vietnam string works fine anyway.

**Comment by bovirus** [comment]
@drhideg 

Thanks for the fix note. Now it works.

I found some new strings that could be translated.

https://github.com/benzino77/tasmocompiler/issues/137
