### ISSUE TITLE
Support for Tasmota Arduino core pre 2.6

### ISSUE THREAD

**Issue by Jason2866** [benzino77/tasmocompiler#14]
Hello again,

could you support the pre core 2.6.? It is much better than 2.5.2 because many issues are fixed.
It is the standard core for the development branch of Tasmota since a few weeks.
Take a look in the [platformio.ini](https://github.com/arendst/Sonoff-Tasmota/blob/development/platformio.ini) 
Is this possible without to much effort?
Thx! Greets Jason2866

**Comment by benzino77** [comment]
Sure. Check out the new master branch. 
I've made 2.6.x core default (just like in Tasmota platformio.ini).
I've also updated to the latest platformio (4.0.3) because I've noticed that Tasmota is no longer binded to 3.6.7 version in its gitpod configuration.
