### ISSUE TITLE
Can't build 1MB: Could not find 'eagle.flash.1m0.ld1m.ld'

### ISSUE THREAD

**Issue by schweini** [benzino77/tasmocompiler#15]
No matter what options I select if trying to compile for "Sonoffs (1MB)" in tasmotacompiler, compilation always fails with:

`Error: Could not find 'eagle.flash.1m0.ld1m.ld' LD script in LDPATH '/tmp/Sonoff-Tasmota/.pioenvs/custom /tmp/Sonoff-Tasmota/.pioenvs/custom/ld /home/gitpod/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lib /home/gitpod/.platformio/packages/framework-arduinoespressif8266/tools/sdk/ld /home/gitpod/.platformio/packages/framework-arduinoespressif8266/tools/sdk/libc/xtensa-lx106-elf/lib /home/gitpod/.platformio/packages/framework-arduinoespressif8266/tools/sdk/lib/NONOSDK22x'`

Compiling for WeMos (4MB) seems to work

**Comment by benzino77** [comment]
Thanks for report!
Try it now (you have to refresh your gitpod workspace or start a new one).

**Comment by schweini** [comment]
Seems to work now. Awesome!

Thanks for this awesome tool! Very useful!

**Comment by benzino77** [comment]
Glad to hear it.
