### ISSUE TITLE
tasmocompiler 4.1.4 - GUI - Increase lenght for WiFi password

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#150]
@benzino77 

In a future release could you please increase the lenght for WiFI password ex. to 16 chars without scrolling it?

![Snap14](https://user-images.githubusercontent.com/1262554/114177285-81d15800-993c-11eb-84f2-b8efcfbe504e.jpg)

Thanks.

**Comment by bovirus** [comment]
It seems that now is OK.

Thanks.

**Comment by benzino77** [comment]
I haven't changed anything in here ...

**Comment by benzino77** [comment]
Have you changed the size of font in your browser?

**Comment by bovirus** [comment]
No. No changes.

**Comment by benzino77** [comment]
It's really strange... The style definition for this field was not changed since... the beginning. It is still 160 chars width.
