### ISSUE TITLE
v. 4.2.4 - custom parameters seems not read correctly

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#166]
@benzino77 

Every time that your released a new tasmocompielr version I made a fork settings some specific pre-set some parameters for my configurations

**file src/component/AppStepper/CustomParametersStep.js**

customParams: '#define FIRMWARE_LITE',

**file src/component/AppStepper/WifiStep.js**

STA_SSID1: 'WiFiName',
STA_PASS1: 'WiFiPassword',

where WifiName and WifiPassword are SSID name and password of my Wifi network.

Customizing of wifi SSDID and password works.

Instead when i go to custom parameter I didn't find pre-set 

#define FIRMWARE_LITE

In the past it worked.

**Comment by drhideg** [comment]
In Custom parameters step, TextField is only updated when changed.
You can change code, to add your always wanted values like this:
https://github.com/benzino77/tasmocompiler/blob/master/src/components/AppStepper/CustomParametersStep.js#L16-L18
```javascript
    this.state = {
      customParams: '',
      customBovirus: '#define FIRMWARE_LITE\n',
    };
```
https://github.com/benzino77/tasmocompiler/blob/e760fee84811c1392e027bf8572dd0d527292287/src/components/AppStepper/CustomParametersStep.js#L56
```javascript
const { customParams, customBovirus } = this.state;
```
https://github.com/benzino77/tasmocompiler/blob/e760fee84811c1392e027bf8572dd0d527292287/src/components/AppStepper/CustomParametersStep.js#L85
```javascript
                value={customBovirus.concat(customParams)}
```

But I use saved text document which i copy into that field, and deselect all in Feature select step:
```
//----------
#ifdef CODE_IMAGE_STR
  #undef CODE_IMAGE_STR
#endif
#define CODE_IMAGE_STR "TCminimal"
#undef FIRMWARE_LITE
#undef FIRMWARE_SENSORS
#undef FIRMWARE_KNX_NO_EMULATION
#undef FIRMWARE_DISPLAYS
#undef FIRMWARE_IR
#undef FIRMWARE_IR_CUSTOM
#undef USE_ARDUINO_OTA
#undef USE_DOMOTICZ
#undef USE_HOME_ASSISTANT
#undef USE_TELEGRAM
#undef USE_KNX
#undef USE_ENHANCED_GUI_WIFI_SCAN
#undef USE_WEBSEND_RESPONSE
#undef USE_EMULATION
#undef USE_EMULATION_HUE
#undef USE_EMULATION_WEMO
#undef USE_CUSTOM
#undef USE_DISCOVERY
#undef USE_TIMERS
#undef USE_TIMERS_WEB
#undef USE_SUNRISE
#undef USE_PING
#undef USE_UNISHOX_COMPRESSION
#undef USE_RULES
#undef USE_SCRIPT
#undef ROTARY_V1
#undef USE_SONOFF_RF
#undef USE_RF_FLASH
#undef USE_SONOFF_SC
#undef USE_TUYA_MCU
#undef USE_ARMTRONIX_DIMMERS
#undef USE_PS_16_DZ
#undef USE_SONOFF_IFAN
#undef USE_BUZZER
#undef USE_ARILUX_RF
#undef USE_SHUTTER
#undef USE_DEEPSLEEP
#undef USE_EXS_DIMMER
#undef USE_HOTPLUG
#undef USE_DEVICE_GROUPS
#undef USE_PWM_DIMMER
#undef USE_PWM_DIMMER_REMOTE
#undef USE_KEELOQ
#undef USE_SONOFF_D1
#undef USE_LIGHT
#undef USE_WS2812
#undef USE_MY92X1
#undef USE_SM16716
#undef USE_SM2135
#undef USE_SONOFF_L1
#undef USE_ELECTRIQ_MOODL
#undef USE_LIGHT_PALETTE
#undef USE_DGR_LIGHT_SEQUENCE
#undef USE_SHELLY_DIMMER
#undef USE_COUNTER
#define USE_ADC_VCC
#undef USE_DS18x20
#undef USE_I2C
#undef USE_SPI
#undef USE_DISPLAY
#undef USE_MHZ19
#undef USE_SENSEAIR
#undef USE_PMS5003
#undef USE_NOVA_SDS
#undef USE_HPMA
#undef USE_SR04
#undef USE_DYP
#undef USE_SERIAL_BRIDGE
#undef USE_TCP_BRIDGE
#undef USE_MP3_PLAYER
#undef USE_AZ7798
#undef USE_PN532_HSU
#undef USE_ZIGBEE
#undef USE_RDM6300
#undef USE_IBEACON
#undef USE_GPS
#undef USE_HM10
#undef USE_MI_ESP32
#undef USE_HRXL
#undef USE_TASMOTA_CLIENT
#undef USE_OPENTHERM
#undef USE_MIEL_HVAC
#undef USE_AS608
#undef USE_ENERGY_SENSOR
#undef USE_PZEM004T
#undef USE_PZEM_AC
#undef USE_PZEM_DC
#undef USE_MCP39F501
#undef USE_SDM120
#undef USE_SDM630
#undef USE_DDS2382
#undef USE_DDSU666
#undef USE_SOLAX_X1
#undef USE_LE01MR
#undef USE_BL0940
#undef USE_TELEINFO
#undef USE_IEM3000
#undef USE_WE517
#undef USE_DHT
#undef USE_MAX31855
#undef USE_MAX31865
#undef USE_LMT01
#undef USE_IR_REMOTE
#undef USE_TM1638
#undef USE_HX711
#undef USE_TX20_WIND_SENSOR
#undef USE_TX23_WIND_SENSOR
#undef USE_WINDMETER
#undef USE_RC_SWITCH
#undef USE_RF_SENSOR
#undef USE_HRE
#undef USE_A4988_STEPPER
#undef USE_THERMOSTAT
#undef USE_PROMETHEUS
#undef DEBUG_THEO
#undef USE_DEBUG_DRIVER
//----------
#ifdef STA_SSID1
  #undef STA_SSID1
#endif
#define STA_SSID1	"WIFI_ESSID"
#ifdef STA_PASS1
  #undef STA_PASS1
#endif
#define STA_PASS1	"WIFI_PASSWORD"
#ifndef USE_WEBSERVER
  #define USE_WEBSERVER
#endif
#ifndef USE_ADC
  #define USE_ADC
#endif
#ifdef USE_ADC_VCC
  #undef USE_ADC_VCC
#endif
#ifndef USE_ENERGY_SENSOR
  #define USE_ENERGY_SENSOR
#endif
#ifndef USE_I2C
  #define USE_I2C
#endif
#ifndef USE_ADE7953
  #define USE_ADE7953
#endif
#ifndef USE_MQTT_TLS
  #define USE_MQTT_TLS
#endif
#ifndef USE_UNISHOX_COMPRESSION
  #define USE_UNISHOX_COMPRESSION
#endif
#ifndef USE_RULES
  #define USE_RULES
#endif
#ifndef USE_EXPRESSION
  #define USE_EXPRESSION
#endif
#ifndef SUPPORT_IF_STATEMENT
  #define SUPPORT_IF_STATEMENT
#endif
#ifndef MY_LANGUAGE
  #define MY_LANGUAGE hu_HU
#endif
//----------
```

**Comment by bovirus** [comment]
Before last month upadte this process worked fine.
Now Also If I save the custom parameters about firmware lit I didn't see it.

Thanks for the proposal changes. Your mod worked fine.

**Comment by drhideg** [comment]
Sorry to misleading you with an untested code. At least I can make benzino77 smile :)

The preferred way is to insert it manually, therefore do not need to maintan a fork for every release.
If you have really need to do that with that short `#define`, here is a working one:
https://github.com/benzino77/tasmocompiler/blob/e760fee84811c1392e027bf8572dd0d527292287/src/components/AppStepper/CustomParametersStep.js#L36
```js
      this.setState({ customParams: '#define FIRMWARE_LITE\n'.concat(ncp) });
```

**Comment by bovirus** [comment]
@drhideg 

I agree with you that the best way is to insert/select the options manually.
But when you want to test a new tasmota firmware vesrion every time

Set WiFi name
Set WiFi password
Select modules
Select LITE option (to reduce code size and flash it directly via web)

it's a boring job....

**Comment by benzino77** [comment]
Ad this to the `AvailableFeatures.js` file:
```javascript
const availableFeatures = [
  {
    name: 'bovirus',
    value: true,
    show: true,
    description: 'Bovirus settings',
    custom: '#define SUPER1\n#define SUPER2\n#define SUPER3\n#define SUPER4\n',
    boards: ['all'],
  },
  {
    name: 'airsensors',
    value: false,
    show: true,
```

It is rather simpler solution (you have to edit only one file and always in the same place) but as @drhideg has mentioned: why not to copy-paste your settings to Custom Parametrs  text field? It is even simpler than editing source code files!

PS.
Issues are for rising problems and errors with TasmoCompiler. If you need help or ask a question or something is not clear to you please open discussion with Q&A type selected:
![image](https://user-images.githubusercontent.com/15658235/115502914-f5952e00-a275-11eb-8176-108801db658d.png)

**Comment by drhideg** [comment]
For future readers: If you modify `AvailableFeatures.js`, your custom board name must include `esp32` in its name for **ESP32** based device, otherwise compile can be failed because of the used `build_flags` depends on boards name.

**Comment by bovirus** [comment]
Then I can create a list with all my custom settings  like

//----------
#define CODE_IMAGE_STR "TCminimal"
#define FIRMWARE_LITE
#define STA_SSID1	"WIFI_ESSID"
#define STA_PASS1	"WIFI_PASSWORD"
#define USE_WEBSERVER
#define FIRMWARE_IR
#define MY_LANGUAGE it_IT
//----------

Good. Thanks.
