### ISSUE TITLE
Add 2MB file Option

### ISSUE THREAD

**Issue by rt400** [benzino77/tasmocompiler#17]
Hi,
this amazing work that help me alot...
i used with ESP that have a 2MB Flash , can you add that option ?
thanks...

**Comment by ascillato** [comment]
Hi, there is no need to add a different memory maps. You can flash the actual file tasmocompiler makes. Making other memory map files is useless due Tasmota won't use the rest of the memory and also brokes the OTA capability for the default precompiled binaries.

**Comment by benzino77** [comment]
You can flash 1MB bin file to 2MB device as Adrian said. We already have similar discussion #5 
Changing the memory layout can be useful in two cases: 
- when the custom binary is larger than 512KB (but less than 681KB) and you want to use OTA to flush it without "sonoff-minimal" step
- when the custom binary you want to flush via OTA is larger than 681KB (you cannot use "sonoff-minimal" step)

But... as I can see in arduino core directories the `eagle.flash.2m.ld` memory layout file looks like this:
```
/* Flash Split for 2M chips */
/* sketch 1019KB */
/* spiffs 1004KB */
/* eeprom 20KB */

MEMORY
{
  dport0_0_seg :                        org = 0x3FF00000, len = 0x10
  dram0_0_seg :                         org = 0x3FFE8000, len = 0x14000
  iram1_0_seg :                         org = 0x40100000, len = 0x8000
  irom0_0_seg :                         org = 0x40201010, len = 0xfeff0
}

PROVIDE ( _SPIFFS_start = 0x40300000 );
PROVIDE ( _SPIFFS_end = 0x403FB000 );
PROVIDE ( _SPIFFS_page = 0x100 );
PROVIDE ( _SPIFFS_block = 0x2000 );

INCLUDE "../ld/eagle.app.v6.common.ld"
```

This layout divide memory in proportion:
1019KB for sketch (tasmota binary)
1004KB SPIFFS (lets say "filesystem" for files)

So even if you use 2m linker memory layout settings, you have no extra space for sketch/binary.

PS.
For clarity I assumed that, official bin file, divide memory in the way, that there is 1024KB available for sketch, but in fact it is 999KB

**Comment by ascillato** [comment]
The official Tasmota uses the 1mb memory map without spiffs. That allows to use 999kb for program and the rest 25kb for config and for wifi sdk related.

The 2mb memory map you proposed uses spiffs that will not allow an OTA bigger than the 1mb version. For that, you need to use the version without spiffs (provided by arduino).

Anyway it brokes any OTA capability from or to official precompiled Tasmota binaries.

The best and easy way is to have the same memory type of binaries (1mb no spiffs) in all your devices. In the case you want to upload by OTA a big binary (>512kb) by otaURL, Tasmota will automatically use the minimal firmware to free flash and then will be loaded that full binary (in the Tasmota wiki is explained that as OTAMagic)

So, there is no big gain on making an uncompatible 2mb version. 

Just for academic explanation, using a 2mb memory map firmware (no spiffs and that initially has to be flashed by serial and all consecutive OTA must be 2mb) will allow you to do OTA for firmwares of up to 999kb in one step without using the minimal interim firmware.

Also, all esp8266 chips can run only 1mb program. The rest of memory can only be used for data. So, in the case of a nodemcu with the maximum 16mb of memory, you can run a 1mb program + 1mb needed free flash for OTA + 14mb for data. That is the hardware limitation.

**Comment by ascillato** [comment]
Offtopic: @benzino77 amazing work you have done with Tasmocompiler!

**Comment by benzino77** [comment]
Thanks for kind words ;)
