### ISSUE TITLE
Custom parameter - Use a personal tasmota repository link

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#176]
@benzino77 

Could be possible to add in the GUI befroe to downlaod source code a speciifc link for a custom tasmota repository?

The default value for this could be the default tasmota repository address.

the default repository link value is 

https://github.com/arendst/Tasmota.git

and is included in the file

- Dockerfile
- server/config/config.js

Could be intersting to create test firmware using a special fork of current tasmota repsoitory to test in place new function.

Thanks.

**Comment by benzino77** [comment]
https://github.com/benzino77/tasmocompiler/issues/9
[compile-someone-fork-of-tasmota-code](https://github.com/benzino77/tasmocompiler/blob/master/ADVANCED.md#compile-someone-fork-of-tasmota-code)

**Comment by bovirus** [comment]
@benzino77 

My proposal is to add to GUI a line, before the option "Download source code", that contains by default tasmota github link, but can be edited to use another repository.

That to avoid as much as possible manul operation/editing.

**Comment by benzino77** [comment]
There couple of reasons why I will not implement it:
1. TasmoCompiler is for compiling Tasmota
2. TasmoCompiler is grounded on a assumption that it is simple and easy
3. Other Tasmota forks may not follow the Tasmota tags/branches standard which will cause errors and problems
4. If you are experienced enough to compile and test Tasmota forks it won't be a problem for you to change one or two lines in TasmoCompiler code
5. All the steps needed to compile someone else Tasmota fork is described in [ADVANCED](https://github.com/benzino77/tasmocompiler/blob/master/ADVANCED.md) file. There is a description how to do this locally, on gitpod and on docker - it will not guarantee that everything will work as expected.
