### ISSUE TITLE
[Request] Device Template Option

### ISSUE THREAD

**Issue by bohdan-s** [benzino77/tasmocompiler#18]
Hi,
I have been using TasmoCompiler in the past.
I recently got some new devices that need to use a Device Template to function.

On a fresh load / factory reset these switches turn on/off ever second (relay is on the Sonof-Basic Led1 GPIO pin.

Is it possible to add an option to add a template from the Template Wiki and set it as the default for the resulting .bin?

**Comment by benzino77** [comment]
I'm not sure you can define template and point it as active during compilation. You have to ask Tasmota guys. If it is possible than you can do this via "Custom parameter" step.

**Comment by localhost61** [comment]
@bohdan-s It's generally not a good idea to target Tasmota to a specific device, when you'll get more devices you will have to compile different versions when only one would have been sufficient.

The recommended way to do is process in two steps, flash first and then configure.

For configuring there are many different methods:
The easiest and safest way would be to forge a backlog string and paste in the WebUI console  using well documented commands in the [wiki](https://github.com/arendst/Tasmota/wiki/Commands)
for instance, something like:   _(example extracted from this recent [thread](https://github.com/arendst/Tasmota/issues/6821))_
`Backlog Template {"NAME":"Lingan SWA1","PIO":[0,0,0,0,158,21,0,0,0,17,0,0,0],"FLAG":0,"BASE":18}; Module 0; WebPassword REMOVED; SSID1 REMOVED; Password1 REMOVED; MqttHost REMOVED; MqttUser REMOVED; MqttPassword REMOVED; Hostname front_room_lamp; MqttClient front_room_lamp; Topic front_room_lamp; FriendlyName1 Front room lamp; SetOption13 1; SetOption32 20; TelePeriod 10;`

Once you achieved to obtain a setup that fit your needs, record a copy of this string for later use and remember to upgrade it each time you modify the settings. Almost every setting is achievable using the WebUI console commands.

**Comment by bohdan-s** [comment]
@localhost61 yes, i get hoe to do it. The issue is that these switches will flash the relay on reset until configured.
So if someone resets the switch (by leaning on it for example) then the light will constantly flash on/off every second until I update the template / run the backlog command.

I was looking for a failsafe way for devices to NEVER get in a use case where they are in an unusable state.

**Comment by localhost61** [comment]
@bohdan-s  Now I understand ;-)

**Comment by benzino77** [comment]
@localhost61 please ask people on Tasmota Discord channel how to handle such situation.
