### ISSUE TITLE
5.2.1 - Custom parameters contains by default 3 newlines

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#182]
@benzino77 

Testing new 5.2.1 but seems was the same in previous version when I go to Custom parametrs list it contains 3 new lines.

![image](https://user-images.githubusercontent.com/1262554/117429352-4455ef80-af27-11eb-9693-5c6119effaf9.png)

What's the matter?

If I cancel all default newlines it appeara an example in grey of commands 

![image](https://user-images.githubusercontent.com/1262554/117429228-1ec8e600-af27-11eb-98dd-b829e127111a.png)

Thanks.

**Comment by benzino77** [comment]
It should be fixed now.
