### ISSUE TITLE
Tooltip error

### ISSUE THREAD

**Issue by drhideg** [benzino77/tasmocompiler#187]
Caught my attention with an interesting tooltip bug while doing https://github.com/benzino77/tasmocompiler/pull/185.

It's in the latest Docker image version (5.1.1.) and in the latest Release (5.2.2).

When browser in full screen the features rendered in a 7x4 grid.
Web interface placed in 2,4 and it's tooltip placed to 5,4 position (if top left is 1,1).
5,4 position is exactly the same, where `Web interface` is placed, when the grid is rendered as 6x5 if I change browser a bit slimmer.
This behaviour is observed on `MQTT over TLS` feature, and maybe others affected too.

Pictures taken with up to date Win10 and Firefox.
![tooltip1](https://user-images.githubusercontent.com/52567253/117686744-741b2680-b1b7-11eb-9f81-e008dd94659c.png)
![tooltip2](https://user-images.githubusercontent.com/52567253/117686769-78474400-b1b7-11eb-97bd-03824d6d92bf.png)

Strange is with Chrome `MQTT over TLS` not affected, only `Web interface`, with Firefox both.

In https://github.com/benzino77/tasmocompiler/pull/185 features is re-ordered itself on hover any board or feature with tooltip so in that tooltips are in place where it's need to be placed, but re-rendering is not looking good :)

**Comment by claymore666** [comment]
This is an old issue - I was not able to reproduce it by now. I guess this can be closed. (Tested both Chrome and Firefox)

**Comment by drhideg** [comment]
This one probably fixed in #185 with https://github.com/benzino77/tasmocompiler/pull/185/commits/66e20a51b8665b50c010ade8a768f8256b38ffff and a lot of things have changed.
