### ISSUE TITLE
Error - Tasmocompiler 5.3.1 - Unexpected end of JSON input

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#194]
Using latest 5.3.1 source code, in Itian web configuration when I select compielr after few second get 

Unexpected end of JSON input

![image](https://user-images.githubusercontent.com/1262554/119674181-459a7e00-be3c-11eb-9a5a-c951ff78069e.png)

**Comment by drhideg** [comment]
Check your installation first. You should see flag icons before languages:
![it](https://user-images.githubusercontent.com/52567253/119678891-36b5ca80-be40-11eb-8187-95739dbf3705.png)

**Comment by bovirus** [comment]
I didn't see the Italy flag.

I compiled it tasmocmpiler source via gitpod but I ddin't get flag icon.
