### ISSUE TITLE
Improvement - Add GUI button to create (set by default) Light firmware

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#195]
For me probably most of the users didn't have the knowledge to add custom parameters.

One of most used function is LIGHT firmware to have a firmware less then 500 KB to update it via web browser.

I believe that add an option to create a LIGHT firmware (options set by default) can help a lot the basic users.

Thanks.

**Comment by drhideg** [comment]
Read benzino's comment on [#111](https://github.com/benzino77/tasmocompiler/pull/111#issuecomment-757868318).

**Comment by bovirus** [comment]
I know it.

The Firmware layout is mroe or less the same fucntion that now you enabled for board.
Also for board teh suer can setup it via custom paramaters.
But usinga  selection avoid many errotrs.

As I mentioned most of the "basic" users don't knows very well the use of custom parameters.
A simple selection in the GUI 

Firmware Light (default)
Firmware Standard
Firmware minimal

that are the typical firmware layout for most of the suer are enough.
 
And help the user as you made for the boards.

**Comment by drhideg** [comment]
I tried to implement that once with half success, it's on my TODO list, with individual sensors/features.
At the moment you can help benzino to update [README.md](https://github.com/benzino77/tasmocompiler/blob/master/README.md) to let the users know how they can achieve the desired effect.

**Comment by benzino77** [comment]
Please read discussion on PR #111, especially Jason2866 [comment](https://github.com/benzino77/tasmocompiler/pull/111#issuecomment-763792602).

There are lite and minimal builds from Tasmota itself. Those are available [here](http://ota.tasmota.com/tasmota/release/) (for stable) and [here ](http://ota.tasmota.com/tasmota/) (for development version).

**Comment by bovirus** [comment]
@benzino77 

I know it but as you can see is not available a LIte not English version.

My scope is enable most oif user with multilanguage interface create a not English lite version that they can update via eb browser.
