### ISSUE TITLE
Trying to install tasocompiler, step 5, yarn install fails?

### ISSUE THREAD

**Issue by dachshund-digital** [benzino77/tasmocompiler#199]
Trying to install tasocompiler, step 5, yarn install fails?  Did the following...

\# cd /root
\# git clone https://github.com/benzino77/tasmocompiler.git
\# cd ./tascompiler
\# yarn install

Result...
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`

Step 5 states to navigate into the git clone directory and execute yarn install.  So what is the issue?

**Comment by dachshund-digital** [comment]
Weird was a session issue?  I logout out of the PuTTy session, logged back in, and then yarn install worked!  Nuts.

**Comment by elzershark** [comment]
sudo apt remove cmdtest
sudo apt remove yarn
sudo npm install -g yarn
