### ISSUE TITLE
Where's the Binary

### ISSUE THREAD

**Issue by meingraham** [benzino77/tasmocompiler#2]
Piotr,

I didn't find the /tmp folder (i.e., `/tmp/Sonoff-Tasmota/.pioenvs/custom`). It doesn't show up in the VSC file explorer. and in the VSC terminal panel if tried to find firmware.bin as well as change directory to tmp.

For now, I am fine with using the links that come up in the TasmoCompiler dialog. However, if there is an error in the compile, those links aren't rendered. In one case, I had made an error with adding custom parameters... but since I could not find the user_config_override that had been created, it was difficult to understand where I'd made my mistake.

Thanks.

Mike

P.S. There is a typo in your dialog for the custom parameters:

Below you can enter custom parameters, which will be included at the end of user_config_**_overwrite_**.h file. If you don't know what it is, just click Next.

P.P.S. On your readme where you credit me & Jason for deploying on Gitpod - your missing the 'a' in @Jason2866

**Comment by benzino77** [comment]
Hi Mike,
Thanks for finding typos :)

Are you trying to find firmware.bin file on gitpod? If so:
Press `ctrl+c` on gitpod console (to stop tasmocompiler) then have a look at steps in the image below:
![image](https://user-images.githubusercontent.com/15658235/57552136-36d2f280-736b-11e9-8905-99069829010f.png)

**Comment by benzino77** [comment]
You have to stop tasmocompiler **after** compilation. Only after compilation there will be `.pioenvs` directory and `firmware.bin` file

**Comment by meingraham** [comment]
Perfect. Thanks.

Could you include the information from your last two posts in your README? Also, you mention that you will be able to download the three files, but you may want to explain that you provide those links. And, be clear that those links will only happen if the compilation is successful. Otherwise you need the ctrl-c route.

BTW, TasmoCompiler is now linked [here](https://github.com/arendst/Sonoff-Tasmota/wiki/Compiling-Tasmota-on-Gitpod). 

Mike

**Comment by benzino77** [comment]
Sure I will create _Troubleshooting_ section.
You are right that there is no information:
1. when and where the links to download files will be available
2. the links wont show up if the compilation failed

If the compilation failed there should be possibility to click back button to move to the previous step (or steps). All the information you entered before clicking compile button should persist. It doesn't show up for you?

**Comment by meingraham** [comment]
Thanks Piotr.

I forgot to mention one other issue that is probably related to Gitpod. You may be able to understand where it comes from though. If one goes through the regular compilation process of selecting the options and selecting `Compile`, everything works as expected. If one then clicks `Back` to change some options or even to fix some issues (e.g., the custom parameters), and then tries to compile again, the compile just spins and spins and never completes. The only way I found to get rid of this issue is to stop the workspace and start over.

**Comment by benzino77** [comment]
Mike,
Do you see any message on "Compiling progress" field during this never ending spins?

PS.
I don't think that you need to stop the whole gitpod workspace and start it again. Try to refresh the page.

**Comment by meingraham** [comment]
Piotr,

Well, I can't reproduce the issue today! Compiles every time even when I go `Back` and forward many times in a single session.

If you can just go ahead and update the README to include the information on the where to look for the file links and if they are not available due to a compile error, the way to get to the folder where the files reside I think we're good for the foreseeable moment.

Let's see how Tasmota users take to use of this facility.

Cheers!

Mike

**Comment by benzino77** [comment]
I have made some changes to gitpod workspace start. Now the TasmoCompiler is opened in new browser tab instead of sidebar. 
I've also created ADVANCED.md file with some _lower level_ description for Gitpod and Docker. There is additional information in README.md __when__ download links will show up.

Hope it now looks better.

**Comment by meingraham** [comment]
Piotr,

Nice enhancements to the documentation! My only suggestion would be to add a link to the ADVANCED article in the main README. Since ADVANCED is only a file in the list of modules, users may not notice it. Add some text to the README like, "If you have problems with the compiler, please refer to the ADVANCED tips for more information."

I like having the compiler start in a new tab. Again, a little explanation on what the "Open Preview" and "Open Browser" do and that the user has to click on one of them in order to get the TasmoCompiler dialog to display. Otherwise, for inexperienced users, they may not notice or know what to do. Some aren't confident enough to just try stuff fearing that they may mess something up. It won't, of course, because they can just blow away the workspace. But having it documented will likely avoid any issues... or questions to you :wink:

Mike

**Comment by benzino77** [comment]
Mike, 
Sure. Thanks for suggestions.

**Comment by benzino77** [comment]
Done.
