### ISSUE TITLE
Support for Tasmota v7.0.0.1 and up

### ISSUE THREAD

**Issue by thxthx0** [benzino77/tasmocompiler#20]
I think there is an issue because of the change to all code references from Sonoff to Tasmota
in compile development

error message:
`Cannot write to /tmp/Sonoff-Tasmota/sonoff/user_config_override.h: Error: ENOENT: no such file or directory, open '/tmp/Sonoff-Tasmota/sonoff/user_config_override.h'`

THX

**Comment by benzino77** [comment]
You are right. There is no `sonoff` folder inside repo root directory anymore. Now it is `tasmota`.
You can make PR or wait few days - I will try to fix it in the coming week.

**Comment by thxthx0** [comment]
Thanks a lot @benzino77 and for all of your work 👍 

No problem I'll wait (I think I'm not familiar enough with it to do a PR).

**Comment by benzino77** [comment]
I will not find a time slot to fix this in this week. Will do my best to do this next week. Sorry.

**Comment by rt400** [comment]
@benzino77 i add a PR for you that make the change...work for me , now you need to create a docker image or its make it automatic ?

**Comment by benzino77** [comment]
I've created new TasmoCompiler version which should be fine with Tasmota git repository transitions. 
Docker images are on their way.
