### ISSUE TITLE
Error - v. 5.3.2 didn't detect OS language and strted in English

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#201]
@benzino77 

My system is Windows 10 x64 Profesional Italian.

The previous tasmocompilrr source version always started in Italian.

Now the last version 5.3.2 seems started in English.

For me I beleive that the program should check OS language and if it's available the same tasmocompielr languag should start by default with this language.

**Comment by benzino77** [comment]
TasmoCompiler will not detect OS language but browser. Change your browser first language to your prefered one:

![image](https://user-images.githubusercontent.com/15658235/120159349-66285680-c1f5-11eb-99a9-7696dd38b30e.png)
![image](https://user-images.githubusercontent.com/15658235/120159591-abe51f00-c1f5-11eb-96dc-17e4db324b80.png)

![image](https://user-images.githubusercontent.com/15658235/120159411-7809f980-c1f5-11eb-93ce-5861bef6bae1.png)

**Comment by bovirus** [comment]
@benzino77 

By default it's the settings of my system.

And I used the same browser configuration with all tasmocompiler versione except the latest.

Please don't close a ticket about a software issues without a confirm by the user that your solution proposed is working for the user

In my case it didn't work (it's already as you explained) but in my system started in English.

Thanks.

**Comment by bovirus** [comment]
![image](https://user-images.githubusercontent.com/1262554/120199052-1791b100-c223-11eb-9962-0f9c55a8200a.png)

![image](https://user-images.githubusercontent.com/1262554/120199134-3001cb80-c223-11eb-890d-4d7fe10ae72b.png)

**Comment by benzino77** [comment]
In the top right corner you can  click on the "Globe Icon" and choose one of the supported languages.

![how_to_change_gui_language](https://user-images.githubusercontent.com/15658235/120220214-b4147d00-c23c-11eb-9961-73c224992b56.png)

**Comment by bovirus** [comment]
@benzino77 

I know it.

My question is why on previous version started in Italian an now with latest version started in English?

**Comment by benzino77** [comment]
The easiest way to find it out is to check the changes made in the code.  On the main github project page you have to click on [Commits](https://github.com/benzino77/tasmocompiler/commits/master) link. This will let you review the changes introduced by particular commits. Commits on the lists are ordered descending so you can start reviewing them from top to bottom.

**Comment by bovirus** [comment]
@benzino77 

Sorry but I beleieve that my scope is only to report the issue.
I didn't have the knowledge and the time to check the source to identify where the problem is.
I believe that it's in charge to the developer.
