### ISSUE TITLE
3.5.3 - GUI (italian) issues

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#205]
@benzino77 

![image](https://user-images.githubusercontent.com/1262554/120846606-aaf41a80-c572-11eb-8442-0c01263a3827.png)

The option to show password (ey icon) is overlap on "password" text

![image](https://user-images.githubusercontent.com/1262554/120846661-bf381780-c572-11eb-804c-39e75f27c7da.png)

"Generic" is untranslated (it was translated before...)

**Comment by benzino77** [comment]
It is fixed now.
The "Generic" part was never translated in TasmoCompiler - you've beed told about that:
#137
#181
#196

**Comment by benzino77** [comment]
You've been told in the comment to #181 that `stepFeaturesBoardGeneric` is not used and will be removed or changed. 

**There was no TasmoCompiler version in which this part was translated**. It was introduced to translation files but never used in the code and the GUI. 

You've been told that if you want to introduce translation changes [make a PR](https://github.com/benzino77/tasmocompiler/issues/137#issuecomment-810791987)

Please stop reopening the same case over and over again.

**Comment by bovirus** [comment]
@benzino77 

**Generic not tramslated**

I'm so sorry what you told seems not true.
"Generic" is currently used in GUI.
Please check the screenshot.

![image](https://user-images.githubusercontent.com/1262554/120977636-d5f98c80-c773-11eb-94db-91fe1466ecc6.png)

Differently what you told the function is not removed.
Then for me until you will remove you will have the option to translate.

**_Wifi password string overlap_**

About the problem reported of overlap it seems that you didn't fixed.
Just you sued a workaropund.
You reduced the string lenght (now is only"password").
My requestt is to have more space for this string (not reduce the string).

![image](https://user-images.githubusercontent.com/1262554/120977481-a9457500-c773-11eb-8073-553118127428.png)

Thanks.

**Comment by benzino77** [comment]
I have asked you many times to read carefully what I have wrote to you in comments to many PRs and Issues - you choose different path. It is related not only to this case but to many other you rised. In such situation I had no choice but report your behaviour to GitHub. 

Ti ho chiesto molte volte di leggere attentamente ciò che ti ho scritto nei commenti a molte PR e Issue: scegli una strada diversa. È legato non solo a questo caso, ma a molti altri che sei risorto. In tale situazione non ho avuto altra scelta che segnalare il tuo comportamento a GitHub.
