### ISSUE TITLE
Script feature not listed under Configuration

### ISSUE THREAD

**Issue by ottelo9** [benzino77/tasmocompiler#217]
I compiled a new Tasmota Version with feature: Home Assistant, Script and web interface.

Under custom parameters I add 
#ifndef USE_SML_M
#define USE_SML_M
#endif

Then compiled the firmware. I upgrade my ESP with that new firmware (gz) (Tasmota 9.5.0.5) and everything works like before. But I can't see the script menu under configuration anymore?? But my previosly entered script (Tasmota 9.2.0) seems to work.

**Comment by ottelo9** [comment]
Can anyone confirm this?

**Comment by benzino77** [comment]
It's holliday time so many people are on their vacations. 
Please take your `user_config_override.h` file (available to download after finishing compilation) and ask experts on Tasmota [discord ](https://discord.gg/Ks2Kzd4) channel if there is everything needed to have those menu entries.

**Comment by ottelo9** [comment]
This was my fault. The script is under Console -> Script and not under Configuration :(
