### ISSUE TITLE
USE_ENERGY_DUMMY causes energy measurements to appear on devices without energy monitoring

### ISSUE THREAD

**Issue by AndreKR** [benzino77/tasmocompiler#219]
I had the problem that on a Shelly 1, which does not have energy monitoring, energy measurements are shown and transmitted, even though no GPIO has been configured for energy monitoring.

It [turned out](https://github.com/arendst/Tasmota/issues/12970) that this is because USE_ENERGY_DUMMY is enabled in my Firmware, which I had compiled with TasmoCompiler.

I think USE_ENERGY_DUMMY is a rather special feature and should probably be disabled, even for firmwares that support actual energy monitors.

**Comment by ascillato** [comment]
Not a Tasmocompiler bug.

When selecting ENERGY MEASUREMENTS, Tasmocompiler adds also ENERGY DUMMY SENSOR. This is expected and correct.
If you don't need and you don't want energy measurements (neither with a power measurement chip or by a dummy sensor) you should not select energy measurements in Tasmocompiler.

Energy Dummy will count power consumption using a fixed voltage value + a fixed current value and the time the relay is ON.
Those values are configured in the same way as the calibration of the power measurement chip (please, see the docs for that).

**Comment by AndreKR** [comment]
I see. My intention was to have a firmware that can do everything I need, but it will only actually do it when it is configured to do so.

**Comment by ascillato** [comment]
In that case, In Tasmocompiler select ENERGY MONITORING and then add the following in the CUSTOM PARAMETER section:

#undef USE_ENERGY_DUMMY
