### ISSUE TITLE
Custom parameter set in CustomParametersStep.jss not read

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#227]
@benzino77 

I made a fork of your last repository making some changes in my fork

- Custom link for tasmota repository fork (file 'Dockefile' and 'config.js') - OK
- Custom default settings for features (file 'AvailableFeatures.js') - OK
- Custom defuilt setting for Wifi (file 'WifiStep.js') - OK
- Set byd efault a custom default parameter 'FIRMWARE_LITE' in 'CustomParametersStep.js' - NOK

I tried to setup the default option '#define FIRMWARE_LITE' in ' CustomParametersStep.js' as

      customParams: '#define FIRMWARE_LITE', 

but seems that it didn't work because when I run gitpod compilation from my fork the custom parameter box is empty.

**Comment by benzino77** [comment]
You have asked that question 6 months ago: #166 , and I gave you an answer.
