### ISSUE TITLE
Multiple custom parameters

### ISSUE THREAD

**Issue by crispy78** [benzino77/tasmocompiler#228]
I've got multiple devices that I fit with different configurations.
I've created something like a weatherstation that needs more sensors enabled than my Sonoff S20.
With every new development release I'm building 4 versions of Tasmota; minimal, regular, sensors (with aditional sensors) and a zbbridge. It would be great if I could save my settings, name them and select the config needed for that particular build.

It would also be great if I could name the output file before compilation. Instead of firmware.bin I would like it to be compiled as tasmota-minimal.bin for example.

**Comment by benzino77** [comment]
I will leave this issue open so maybe someone will pick it up.

As a quick tip I will point you to the `user_config_override.h` file which can be downloaded at the end of the compilation. You can use it as your "save settings file" just copy its content and paste in "Custom parameters" field  next time you will compile your binary. 
Custom parameters are  _**always**_ added at the end of produced `user_config_override.h` file so will override any other settings configured by "Features step". The only thing you need to choose is board type.

The name of the binary file can be changed when you click the button to save the file, but you have to change browser default setting to ask where to save each file before downloading. You can then name your binary however you want.

Brave:
![brave](https://user-images.githubusercontent.com/15658235/140931144-d5ca051d-5cb2-4760-ac29-5c1ccd125c3a.png)

Chrome:
![chrome](https://user-images.githubusercontent.com/15658235/140931172-6add04ce-26f5-4e8c-a5d0-b382783bd2b0.png)

Firefox:
![firefox](https://user-images.githubusercontent.com/15658235/140931194-5e1ed466-0b97-48c4-aeaf-a24823eaa0ba.png)

You can also leave default setting and rename the file manually after you download it.

ps.

> With every new development release I'm building 4 versions of Tasmota

Do not try to fix things which are not broken ;)

**Comment by crispy78** [comment]
@benzino77 You are a godsend with the save-as remark. I use MS EDGE and found it's setting, see attached image.
![EDGE](https://user-images.githubusercontent.com/42983001/141178667-e70609ab-41a1-45eb-a639-74e0f7e0d6d6.jpg)
