### ISSUE TITLE
Cant compile binary with IR

### ISSUE THREAD

**Issue by jerry1333** [benzino77/tasmocompiler#230]
Trying compile firmware with IR module but it ends with error:
`Can not remove temporary directory `/tmp/Tasmota/.pio/build`. Please remove it manually to avoid build issues
Error: Invalid '/tmp/Tasmota/platformio.ini' (project configuration file): 'No section: 'irremoteesp_full''
Finished. Exit code: 1.`

![Zrzut ekranu 2021-11-18 214754](https://user-images.githubusercontent.com/984193/142494399-06dc11ce-5204-4b8f-a730-5c23ab8225cc.png)
![Zrzut ekranu 2021-11-18 214808](https://user-images.githubusercontent.com/984193/142494403-8c098ff0-c423-4fc8-85e9-2f093ac87442.png)

**Comment by benzino77** [comment]
Yes this is a bug in TasmoCompiler have a look here:  https://discord.com/channels/479389167382691863/790187952416358460/909469405862309909

I don't have a time to fix it now. As a workaround you can deselect IR support feature, and add appropriate entries for IR in "Custom parameters" field.

ps.
dam znać w tym wątku jak będzie fix ;)

**Comment by benzino77** [comment]
It should be fixed now. Check the new version and let me know whether everything works for you as expected.

**Comment by jerry1333** [comment]
Now it works beautifully!
Thank you golden boy and merry Christmas!

**Comment by benzino77** [comment]
Wesołych świąt.
