### ISSUE TITLE
Could not install package

### ISSUE THREAD

**Issue by sputnik1984** [benzino77/tasmocompiler#231]
Tried to start Docker - Immage on Synology x86 Processor (DS218+). Web GUI works well but after clicking "compile" the following issue apears:

Processing firmware (framework: arduino; platform: https://github.com/platformio/platform-espressif32.git#feature/arduino-idf-master; board: esp32_4M)
--------------------------------------------------------------------------------
Tool Manager: Installing espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r1
Error: Could not install package 'espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r1' for 'linux_x86_64' system
Finished. Exit code: 1.

I have tried several older versions - same issue.

Same problem for me on the "Gitpod" - Onlinecompiler.

Kind regards. Thank you for your work!

**Comment by sputnik1984** [comment]
Sorry. There was a simple DNS Problem in my Network that caused the Problem.

**Comment by benzino77** [comment]
DNS is the root of all problems... always ;)

**Comment by sputnik1984** [comment]
maybe that also explains some of the problems between men and women ;-)
