### ISSUE TITLE
TasmoCompiler stops with  /bin/sh: 1: pio: not found in Gitpod

### ISSUE THREAD

**Issue by Gura74** [benzino77/tasmocompiler#232]
Hi,
I can’t get tasmocompiler to work in a Gitpod workspace: TasmoCompiler v7.0.4 starts, but when I press the compile button the following is displayed:

 /bin/sh: 1: pio: not found
Finished. Exit code: 127.  

Last week (Dec 1st) it still worked - that workspace unfortunately is not available anymore. As I’m an absolute beginner I do not even know if this issue related to TasmoCompiler at all or if I'm doing something wrong in Gitpod. According to the terminal output in the workspace, platformio is built correctly, but some warnings about '/home/gitpod/.local/bin' not being in the PATH follow:

` The script async-json-rpc-server is installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.`
(some more scripts beeing in the same directory follow).

I pressed crtl+c to stop the server and added the path with `export PATH=$PATH: /home/gitpod/.local/bin`.
Restarting the server with node server/server.js  from /workspace/tasmocompiler doesn’t seem to work either: no error is returned, but also no port is opened.

Any tip?

**Comment by benzino77** [comment]
Hmmm. 
> I pressed crtl+c to stop the server and added the path with export PATH=$PATH: /home/gitpod/.local/bin.

Do it again but start the application by `node server/app.js`.  
Something has changed on gitpod or platformio side. I will try to fix it.

**Comment by benzino77** [comment]
It is fixed.

**Comment by Gura74** [comment]
Works again – thank you, really a very nice tool!
