### ISSUE TITLE
solo1 dev does not compile

### ISSUE THREAD

**Issue by Jason2866** [benzino77/tasmocompiler#240]
Probably fixed with #239

**Comment by dupan99** [comment]
Have the same problem. No compile of solo1 possible.

**Comment by benzino77** [comment]
Yes, it can be it. To compile Solo1 board with Tasmocompiler you have to choose `v10.0.0` version of Tasmota instead of `development`.
I will do my best to push new `development` branch of TasmoCompiler which will follow current bleeding edge Tasmota `development` branch in following days - I'm really short of time.

**Comment by benzino77** [comment]
I've just pushed `development` branch of TasmoCompiler which is compatible with current Tasmota `development` branch.
For now, you can use it via gitpod by pointing to this branch:
https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/development

I will also push docker image `benzino/tasmocompiler:development` later.

**Comment by oldcrazyeye** [comment]
> I've just pushed development branch of TasmoCompiler which is compatible with current Tasmota development branch.
> For now, you can use it via gitpod by pointing to this branch:
> https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/development
> 
> I will also push docker image benzino77/tasmocompiler:development later.

Thanks for the great work! I added a template to unraid based on your image just this morning. So this fix will be great!

**Comment by benzino77** [comment]
Docker image is available to pull. All you need to do is:
`docker pull benzino77/tasmocompiler:development`
