### ISSUE TITLE
error: 'class TwoWire' has no member named 'readTransmission'

### ISSUE THREAD

**Issue by tremichl** [benzino77/tasmocompiler#242]
Compiling esp32 generic development failed with error: 

`/tmp/Tasmota/tasmota/xsns_44_sps30.ino:104:8: error: 'class TwoWire' has no member named 'readTransmission'; did you mean 'endTransmission'?
   Wire.readTransmission(SPS30_ADDR,twi_buff,dlen,1, NULL);
        ^~~~~~~~~~~~~~~~`

What can I do?

**Comment by benzino77** [comment]
That's not TasmoCompiler error/message. It comes from sensor driver. Ask dev team on [discord](https://discord.gg/Ks2Kzd4) channel - you will find there a lot of helpful people. Before you ask a question there, prepare all necessary information: sensors you've selected, Tasmota version, etc..

**Comment by Jason2866** [comment]
@tremichl We know it is NOT compiling. We did not touch the driver since we have no device to test (may brake esp8266). If we change it needs testing with a ESP8266 and a ESP32. Could you do the tests?

**Comment by tremichl** [comment]
Of course I can test it on both ESP32 and ESP8266 once I have a successfully compiled ESP32 file. At the moment same sensors and displays are working fine on ESP8266. Compile error only at ESP32. Displays itself are also working on precompiled  tasmota32-display.bin.

**Comment by Jason2866** [comment]
@tremichl  Please test, I have added a esp8266 and a ESP32 build. If it works I will submit a PR to Tasmota repo. Change is here https://github.com/Jason2866/Tasmota/tree/sps30

[Tasmota_SPS30.zip](https://github.com/benzino77/tasmocompiler/files/7840317/Tasmota_SPS30.zip)

**Comment by tremichl** [comment]
@Jason2866 Flashing with ESP_flasher: tasmota.bin and tasmota32.bin is possible. tasmota32.factory.bin causes an error (magic Byte ff) Hope that helps. Thanks!

**Comment by Jason2866** [comment]
factory.bin is okay when not possible. It is a one file firmware which needs to be flashed with esptool at address 0x0. The result is the same as when you flash the tasmota32.bin with ESP_flasher.
Does the SPS30 work with the ESP32?

**Comment by tremichl** [comment]
Yes SPS30 compiled and flashed with my needed sensors successfully. Great, Thanks!
