### ISSUE TITLE
Cant compile v11.0.0 ESP32

### ISSUE THREAD

**Issue by MDeeApp** [benzino77/tasmocompiler#252]
TasmoCompiler v7.1.0
Compiling v11 in gitpot for ESP32 generic (default settings) fails with the following errors:

> Compiling .pio/build/firmware/lib411/ESP32-HomeKit/json_parser.c.o
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino: In destructor 'Log_line::~Log_line()':
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino:41:7: error: 'berry_free' was not declared in this scope
>        berry_free(log_line);
>        ^~~~~~~~~~
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino:41:7: note: suggested alternative: 'memp_free'
>        berry_free(log_line);
>        ^~~~~~~~~~
>        memp_free
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino: In member function 'char* Log_line::allocate(size_t)':
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino:47:7: error: 'berry_free' was not declared in this scope
>        berry_free(log_line);
>        ^~~~~~~~~~
> Compiling .pio/build/firmware/lib411/ESP32-HomeKit/mu_srp.c.o
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino:47:7: note: suggested alternative: 'memp_free'
>        berry_free(log_line);
>        ^~~~~~~~~~
>        memp_free
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino:49:24: error: 'berry_malloc' was not declared in this scope
>      log_line = (char*) berry_malloc(size);
>                         ^~~~~~~~~~~~
> /tmp/Tasmota/tasmota/xdrv_52_0_berry_struct.ino:49:24: note: suggested alternative: 'memp_malloc'
>      log_line = (char*) berry_malloc(size);
>                         ^~~~~~~~~~~~
>                         memp_malloc

**Comment by benzino77** [comment]
Try to use development version of TasmoCompiler.

**Comment by MDeeApp** [comment]
Works with development version. Is there a way to use the development version within gitpot?

**Comment by benzino77** [comment]
Sure. There is a section in README with a gitpod link to run development version of TC.

**Comment by MDeeApp** [comment]
Thank you, I missed that one.
Just in case anyone missed it too, that' s the link: 
[https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/development](https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/development)
