### ISSUE TITLE
Gitpod - AvailableFeatures.js - Custom parameter #define FIRMWARE_LITE not working anymore

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#259]
@benzino77 

I want tod efine by default '#define FIRMWARE_LITE' as by default when I compilie project.

As you sugegsted I added the part in bold at the end of 'AvailableFeatures.js' file.

  {
    name: 'USE_SPI',
    value: false,
    show: false,
    description: 'stepFeaturesSPIDesc',
    boards: ['all'],
  },
  **_{
    name: 'bovirus',
    value: true,
    show: true,
    description: 'Preimposta parametri personalizzati',
    custom: '#define FIRMWARE_LITE',
    boards: ['all'],
  },_**

It worked in the apst bt not now anymore.
I I left this part the project compile with gitpod without error but when it try to open child window in the browser to run GUI it stopped.

If I remove the part in bold it works.

How can restroe this functionality to avoid to type everey time in custom param,eter the string

#define FIRMWARE_LITE

Thanks.

**Comment by benzino77** [comment]
You have asked this question at least twice: #227, #166 and you've been told what you have to do.

Please, please, please stop asking over and over again the same question and carefully read answers you already have. There has to be an "new line" (\n) character at the end:
```C
custom: '#define FIRMWARE_LITE\n',
```

**Comment by bovirus** [comment]
@benzino77 

First of all I can say that you absoltely unpolite in your answer.
If you think that there was an error on "\n" you can hust report this.
Any addition coments as you posted are not necesaary.

Second you cannot close something if you are not sure that your suggestion solve teh problem.
You have tow ait the confiorm that the problem was fixed.
And is not in this case.

If I post it it's becauise I follow the sugegstions (Iand I say thanks for this) but now didn't work.

I added \n

{
name: 'bovirus',
value: true,
show: true,
description: 'Preimposta parametri personalizzati',
custom: '#define FIRMWARE_LITE\n',
boards: ['all'],
},

but if didnt work,.
In Gitpod at the end of compilation when run it open on port 3000 a new browser web page but blank

If I remove

{
name: 'bovirus',
value: true,
show: true,
description: 'Preimposta parametri personalizzati',
custom: '#define FIRMWARE_LITE\n',
boards: ['all'],
},

it works.

**Comment by benzino77** [comment]
The problem is here:
```js
{
  name: 'bovirus',
  value: true,
  show: true,
  description: 'Preimposta parametri personalizzati', // <---- problem
  custom: '#define FIRMWARE_LITE\n',
  boards: ['all'],
},
```
This should be language file entry:
```js
{
  name: 'bovirus',
  value: true,
  show: true,
  description: 'stepBovirusDesc', // <---- changed
  custom: '#define FIRMWARE_LITE\n',
  boards: ['all'],
},
```
and then in translation files (i suggest to add this entry to all of them) `src/locales/<language>.json` you have to add description for that feature:

```json

  "stepFeaturesBluetoothDesc": "Bluetooth",
  "stepFeaturesBluetoothTooltip": "Aggiunge supporto ble e ble-bridge",
  "stepBovirusDesc": "Bovirus", <--- Feature description
  "stepFeaturesI2CDesc": "Supporto I2C",
  "stepFeaturesSPIDesc": "Supporto SPI",
```

There is no matter where is will be defined, at the beginning, the end or the middle of the `availableFeatures` object.

**Comment by bovirus** [comment]
@benzino77 

Thanks for the update

Can I avoid teh sue of new file language.json with a system like this

{
  name: 'bovirus',
  value: true,
  show: true,
  ;description: 'Preimposta parametri personalizzati', // <---- problem
  custom: '#define FIRMWARE_LITE\n',
  boards: ['all'],
},

then no provide info for this?

**Comment by benzino77** [comment]
No. You have to have description for the feature.

**Comment by bovirus** [comment]
@benzino77 

Thanks.
