### ISSUE TITLE
ESP32 on aarch64

### ISSUE THREAD

**Issue by baz-fr** [benzino77/tasmocompiler#270]
Hi

Debian Buster with Armbian Linux 4.19.69-meson64
Docker Engine - Community Version: 19.03.13
TasmoCompiler v8.0.1

When I select ESP32 options :

```
Tool Manager: Installing espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Error: Could not find the package with 'espressif/toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3' requirements for your system 'linux_aarch64'
Finished. Exit code: 1.
```

**Comment by benzino77** [comment]
Hi,
That message is not related to TC. As I can see platformio has a problem with finding proper toolchain for your architecture (linux_aarch64). Yo have couple of options: 
- try to run TC on other architecture (especially do not use 64bit kernel)
- try to use standard Tasmota build
- contact esspressif/platformio maintainers and try to resolve that issue with them

It is also worth to check this conversation: https://github.com/platformio/platform-espressif32/issues/753

**Comment by baz-fr** [comment]
Hi,

Thanks for this answer.
In a first time, I think I'll make a other temporary docker server on a Raspberry Pi (currently on a Odroid C2) to use your wonderfull tool.
Thank you for TC

**Comment by Jason2866** [comment]
Support has been added form espressif. https://github.com/platformio/platform-espressif32/issues/753#issuecomment-1157363441
