### ISSUE TITLE
can't compile Tasmota

### ISSUE THREAD

**Issue by ArturZurawski** [benzino77/tasmocompiler#272]
Hi. First of all thank you for awesome GUI compiler for Tasmota. Super easy to use! ❤️ 

Recently I encountered the problem while compiling Tasmota. It throws at me:

```
********************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
********************************************************************************

Processing firmware (platform: https://github.com/tasmota/platform-espressif8266/releases/download/v2.7.4.9/platform-espressif8266-2.7.4.9.zip; framework: arduino; board: esp8266_1M)
--------------------------------------------------------------------------------
Platform Manager: Installing https://github.com/tasmota/platform-espressif8266/releases/download/v2.7.4.9/platform-espressif8266-2.7.4.9.zip
Downloading
Unpacking
Platform Manager: espressif8266 @ 2.7.4+9 has been installed!
Platform Manager: Removing espressif8266 @ 2.7.4+9
Platform Manager: espressif8266 @ 2.7.4+9 has been removed!
Error: Development platform 'espressif8266' is not compatible with PlatformIO Core v5.2.4 and depends on PlatformIO Core >=6.0.2.

Finished. Exit code: 1.
```

I tried both dev and latest docker image of Tasmocompiler. I'm trying to build Tasmota from dev branch, but also tried 11.0.0 and 11.1.0 - I'm quite sure one of those used to work in the past.

I'm not sure if this is something that you could help me with, but maybe at least I might get some hints on how to solve it.

Thanks in advance.

**Comment by benzino77** [comment]
Artur,
Thanks for reporting the issue. I've just pushed new docker images `v8.0.2` and `development` to dockerhub so you have to pull new ones. The problem was with `platformio` package bundled with docker images (it was too old). Now it includes `platforion v6.0.2`  and it looks, it solves the issue. Please check it on your side.

PS.
Pozdrawiam ze słonecznego Trójmiasta ;)

**Comment by ArturZurawski** [comment]
Worked like like a charm! Thank you for such a fast fix.

Pozdrawiam również!
