### ISSUE TITLE
It does not work anymore

### ISSUE THREAD

**Issue by rdu** [benzino77/tasmocompiler#273]
Unfortunately, the Docker container (direct code was not tested) no longer works. The following error message is displayed when trying to create an image:

```
Downloading
Unpacking
Platform Manager: espressif8266 @ 2.7.4+9 has been installed!
Platform Manager: Removing espressif8266 @ 2.7.4+9
Platform Manager: espressif8266 @ 2.7.4+9 has been removed!
Error: Development platform 'espressif8266' is not compatible with PlatformIO Core v5.2.4 and depends on PlatformIO Core >=6.0.2.

Finished. Exit code: 1.

```

**Comment by rdu** [comment]
Yesterday the ESP32 still worked - but in the meantime it doesn't work anymore either:

Processing firmware (framework: arduino; platform: https://github.com/tasmota/platform-espressif32/releases/download/v.2.0.3/platform-espressif32-v.2.0.3.zip; board: esp32_4M)
--------------------------------------------------------------------------------
Platform Manager: Installing https://github.com/tasmota/platform-espressif32/releases/download/v.2.0.3/platform-espressif32-v.2.0.3.zip
Downloading
Unpacking
Platform Manager: espressif32 @ 2.0.3 has been installed!
Error: Unknown development platform 'espressif32'
Finished. Exit code: 1.

**Comment by benzino77** [comment]
[Link](https://github.com/benzino77/tasmocompiler/issues/272)

**Comment by rdu** [comment]
Thank you, now works again without any problems!

I close this issue now!
