### ISSUE TITLE
Add ESP32 S3 support

### ISSUE THREAD

**Issue by imkebe** [benzino77/tasmocompiler#274]

**Comment by benzino77** [comment]
This board is added to the newest `main` and `development` version. Docker images are on their way.

P.S.
Tak między nami Sławek (widzę że jesteś z "branży") - chciałbyś dostać takie zgłoszenie/dodanie funkcjonalności jakie tutaj zgłosiłeś? Jedna linijka, cztery słowa  (w temacie) i to wszystko. Bez jakiegoś kontekstu/opisu  w stylu "Tasmota od niedawna wspiera tą płytkę (link do tej informacji albo wycinek z `plaftormio.ini`) w wersji produkcyjnej, staje się coraz bardziej popularna (jakiś kolejny link ze specyfikacją, opisem, przypadkami użycia itd.) i fajnie by było mieć dla niej wsparcie po stronie TC".

To pytanie retoryczne... miłego Tasmotowania.

**Comment by imkebe** [comment]
Wybacz. Planowałem tam coś więcej wpisać ale długi weekend i zapomniałem o temacie. Szczerze mówiąc to jakoś nieświadomie wysłało się te zgłoszenie draft, chyba przy okazji wymuszenia zamknięcia systemu (gdzie klikałem zapisz, enter, zapisz, enter).

**Comment by benzino77** [comment]
Luz ;) Miłego (reszty) weekendu.
