### ISSUE TITLE
AvailableFeature.js - Customize features for FIRMWARELITE

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#285]
@benzino77 
@drhideg 

In the past to add an option to setup by default a custom option for FIRMARELITE you sugegsted me to adeed this code

  {
    name: 'bovirus',
    value: true,
    show: true,
    description: 'stepCustomParameters',
    custom: '#define FIRMWARE_LITE\n',
    boards: ['all'],
  },

to this file

/src/component/AppStepper/FeatureStep/AvailableFeatures.js

but in this new version (9.0.0/9.01) it seems that didn't work (at the end didn't start the wizard).

There is a way to use a fuction like this?
Any suggestion?

Thanks.

**Comment by drhideg** [comment]
As i remember, you must set the description at least in the english
translation.

bovirus ***@***.***> ezt írta (időpont: 2022. jún. 20., H
17:41):

**Comment by bovirus** [comment]
@drhideg 

Thanks. Fixed.
