### ISSUE TITLE
failing compilation  : Development platform 'espressif8266' is not compatible with PlatformIO Core v5.2.3 and depends on PlatformIO Core >=6.0.2.

### ISSUE THREAD

**Issue by ouinouin** [benzino77/tasmocompiler#291]
Platform Manager: Installing https://github.com/tasmota/platform-espressif8266/releases/download/v2.7.4.9/platform-espressif8266-2.7.4.9.zip
Unpacking
Platform Manager: espressif8266 @ 2.7.4+9 has been installed!
Platform Manager: Removing espressif8266 @ 2.7.4+9
Platform Manager: espressif8266 @ 2.7.4+9 has been removed!
Error: Development platform 'espressif8266' is not compatible with PlatformIO Core v5.2.3 and depends on PlatformIO Core >=6.0.2.

Finished. Exit code: 1.

got this while compiling, (i use the docker image development).
any hint ? 
regards.

**Comment by benzino77** [comment]
Hi,

**The Hint**: since a month or more there is new version of TC (including the development branch). Pull the fresh one.
