### ISSUE TITLE
Previous Versions of Firmware

### ISSUE THREAD

**Issue by heffneil** [benzino77/tasmocompiler#296]
Is there a way, and can we add one if not, to select a previous version of the firmware to compile?  I am running 12.02 with some special options and need to roll back to the 11.x but I don't know how or if it is possible.  I can't use an off the shelf firmware because I require the special options.

**Comment by heffneil** [comment]
Oh thats great! Would be nice to get a dropdown on the first step to pick which firmware version you want to use?

**Comment by benzino77** [comment]
No. It is impossible. TasmoCompiler has to follow changes in Tasmota. Those changes are incompatible with other versions of Tasmota. If you want to compile Tasmota v11.x you have to choose TasmoCompiler 8.x. 
Even that you can see Tasmota version v12.x in TasmoCompiler v8.x there is a big chance that you won't be able to compile v12.x on v8.x.

**Comment by heffneil** [comment]
Ok - I don't understand fully but it doesn't matter. Thanks for the tip I was able to make a older version firmware and all seems right in the world again! Thanks!
