### ISSUE TITLE
ESP32C3 does not compile

### ISSUE THREAD

**Issue by ivlis** [benzino77/tasmocompiler#297]
All default, tasmocompiler 9.0.1

```
Compiling .pio/build/tasmota32c3/liba9a/mp3_shine_esp32/l3loop.cpp.o
Compiling .pio/build/tasmota32c3/liba9a/mp3_shine_esp32/l3mdct.cpp.o
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp: Assembler messages:
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:101: Error: unrecognized opcode `mulsh a4,a4,s11'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:103: Error: unrecognized opcode `mulsh a7,t5,t4'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:104: Error: unrecognized opcode `mulsh a7,t5,t4'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:105: Error: unrecognized opcode `mulsh a7,t5,t4'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:106: Error: unrecognized opcode `mulsh a7,t5,t4'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:107: Error: unrecognized opcode `mulsh a7,t5,t4'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:108: Error: unrecognized opcode `mulsh a7,t5,t4'
lib/libesp32_audio/mp3_shine_esp32/src/l3mdct.cpp:109: Error: unrecognized opcode `mulsh a7,t5,t4'
*** [.pio/build/tasmota32c3/liba9a/mp3_shine_esp32/l3mdct.cpp.o] Error 1
lib/libesp32_audio/mp3_shine_esp32/src/l3loop.cpp: Assembler messages:
lib/libesp32_audio/mp3_shine_esp32/src/l3loop.cpp:411: Error: unrecognized opcode `mulsh a4,s11,a4'
lib/libesp32_audio/mp3_shine_esp32/src/l3loop.cpp:419: Error: unrecognized opcode `mulsh a5,s11,a5'
lib/libesp32_audio/mp3_shine_esp32/src/l3loop.cpp:141: Error: unrecognized opcode `mulsh a4,a4,a4'
*** [.pio/build/tasmota32c3/liba9a/mp3_shine_esp32/l3loop.cpp.o] Error 1
========================= [FAILED] Took 136.96 seconds =========================
Environment    Status    Duration
-------------  --------  ------------
tasmota32c3    FAILED    00:02:16.956
==================== 1 failed, 0 succeeded in 00:02:16.956 ====================

Finished. Exit code: 1.
```

**Comment by evlo** [comment]
I have just tried it on gitpod and thought it is gitpod issue, did you tried locally?

**Comment by mtannertdev** [comment]
I can confirm this issue with Tasmota 12.1.x. I run this in a docker container and build locally, same errors as above.

**Comment by ivlis** [comment]
I'm running locally. @evlo I tried your DEFS - same error as above.

I also tried compiling the dev branch of Tasmota for esp32c3 using the cli - no errors.

**Comment by benzino77** [comment]
For now you can choose Tasmota version up to `v12.0.2` in the Tasmota Version dropdown field. Probably there is a change in platformio configuration for C3 boards in `v12.1.0` and up, which are not handled by TasmoCompiler. I'm currently out of time to look at this, but if there are no importatnt changes for you in Tasmota `v12.1.0` or `v12.1.1` you can always use `v12.0.x`.

**Comment by evlo** [comment]
Also note with older then latest UART for smart meter does not work correctly for smart meter stuff, but as ivlis mentioned it works from cli, even cli in gitpod. So that might be option for someone too.

**Comment by mtannertdev** [comment]
> I'm currently out of time to look at this, but if there are no importatnt changes for you in Tasmota `v12.1.0` or `v12.1.1` you can always use `v12.0.x`.

I can appreciate the lack of time to dig into this. Regrettably 'v12.1.1' added 'Support for 5-channel light dimmer driver SM2335 used in SwitchBot Color Bulbs', which I need.

I do enjoy this project and use it quite heavily for all my other devices. Thank you!

**Comment by ivlis** [comment]
@mtannertdev yeah, that's exactly the reason I wanted to recompile my builds...

As an alternative, you can use: https://github.com/tasmota/docker-tasmota
Not as cool as tasmocompiler but does the job.

**Comment by benzino77** [comment]
Fortunately it was fairly easy to fix. New version `v9.0.2` is pushed to dockerhub. Enjoy.
