### ISSUE TITLE
fatal error: OneWire.h: No such file or director

### ISSUE THREAD

**Issue by firig** [benzino77/tasmocompiler#298]
I just now tried tasmocompiler for the first time, following the excellent article https://cgomesu.com/blog/Esp32cam-tasmota-webcam-server/#webcam-server-additional-configurations.
So, selecting "ESP32 Webcam" and adding "Temp/Hum Sensors" and otherwise accepting all defaults.

**Comment by benzino77** [comment]
For some reason some sensor are incompatible with Webcam board. If you don't use them you can select "Temp/Hum Sensors" and then in "Custom parameters" put those lines:
```C
#undef USE_DS18x20
#undef USE_MAX31865
#undef USE_MCP9808
#undef USE_HP303B
```
For more information about that I encourage you to go  Tasmota discord channel where you can find people from Tasmota Dev team. There is a chance that they will provide you more information about that problem.
