### ISSUE TITLE
Tasmota pio core32 changes in development

### ISSUE THREAD

**Issue by Jason2866** [benzino77/tasmocompiler#299]
Hi @benzino77,

since today, there is no more a difference for solo1 and ITEAD devices (NSPanel, ZigbeeBridgePro) in Tasmota Platformio setup. The definitions for this two platforms are gone ;-) The magic is now done in our Platformio Platform fork by installing always all three frameworks. The selection for the special ones is done as a compile flag (for ITEAD) or in boards.json (solo1). Details in merge [PR](https://github.com/arendst/Tasmota/pull/16644)

**Comment by benzino77** [comment]
Thanks! Changes introduced in TasmoCompiler `development` branch.

**Comment by Jason2866** [comment]
Great. Fixed, that was fast. Should i close or left open for information?
