### ISSUE TITLE
Feature Request replace core 2.5.0 with 2.5.1

### ISSUE THREAD

**Issue by Jason2866** [benzino77/tasmocompiler#3]
Bugfix release 2.5.1 is out. 
To use it you can use my Repo for Platformio since The Platformio crew didnt do an update yet

`platform                  = https://github.com/Jason2866/platform-espressif8266.git#Tasmota`

**Comment by benzino77** [comment]
What should be entered in `platformio.ini` file for 2.5.1 core version?
Now it is:
`platform  = espressif8266@~2.0.4`
for 2.5.0

**Comment by Jason2866** [comment]
We worked the same time :-)

**Comment by benzino77** [comment]
Mainly my `platformio.ini` template file is based on Tasmotas `platformio.ini` (with some very small modifications).
Let's agree that I will try to follow Tasmotas `platformio.ini` with changes.

**Comment by Jason2866** [comment]
I will do a PR on Tasmota Github. Maybe it needs some time to merge since Theo is in holiday

**Comment by benzino77** [comment]
That's a good way to do this. I will leave this issue open, and wait for your PR to be merged. Then I will change the TasmoCompiler `platformio.ini` template file.

PS.
The file is located in `tasmocompiler/server/compile` folder of the project. It is almost _vanilla_ Tasmota `platformnio.ini` file which is modified before compilation, and copied to Tasmota source code folder.
So maybe you can do two PRs one to Tasmota, and after it will be merged to TasmoCompiler? :)

**Comment by Jason2866** [comment]
PR https://github.com/arendst/Sonoff-Tasmota/pull/5784

**Comment by Jason2866** [comment]
PR is merged in Tasmota dev version

**Comment by benzino77** [comment]
Jason could you please check `pa/core251` branch?
https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/pa/core251

If you will be ok with this I will merge it to master and build new docker image.

**Comment by benzino77** [comment]
Done.
