### ISSUE TITLE
Compile doesnt work with feature zigbee

### ISSUE THREAD

**Issue by wimpie007** [benzino77/tasmocompiler#30]
Just doesnt complete when selecting option 'zigbee'
last output:

Linking .pioenvs/custom/firmware.elf
Welcome stranger!

Then it stays there...  Deselecting zigbee will compile it without problems,

**Comment by benzino77** [comment]
When it says "Welcome stranger" there is problem with WebSocket communication (well, this is not a real problem but confusion where to send messages). Usually this is caused by more than one web browser tab opened with Tasmocompiler.

**Comment by wimpie007** [comment]
Thanks for the answer! seems to be right! 
A window that is blocked by an ad-blocker seems to be enough to make it go nuts...
Thanks!
