### ISSUE TITLE
9.2.0 - Use of different tasmota repository

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#304]
@benzino77 

Before 9.2.0 I used instead original tasmota repository a personal fork of tasmota with some personal changes on language files.

original = https://github.com/arendst/Tasmota.git

my fork = https://github.com/bovirus/Tasmota.git

I changed the relative string in

/Docker - line 8
/src/config.confiug.js - line 5

With this new 9.20 version if I did it I got an error of un unexpected 

(;

With this new tasmocompiler 9.20 version is possible to use a fork of tasmota official github repository?

My fork contains only "development" branch (not other).
Is this the problem?

---- log

Successfully built platformio
Installing collected packages: aiofiles, ajsonrpc, bottle, typing-extensions, zipp, importlib-metadata, click, colorama, pyparsing, packaging, marshmallow, pyelftools, pyserial, certifi, charset-normalizer, idna, urllib3, requests, semantic-version, sniffio, anyio, starlette, tabulate, h11, uvicorn, wsproto, ifaddr, async-timeout, zeroconf, platformio
  The script async-json-rpc-server is installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts pyserial-miniterm and pyserial-ports are installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script normalizer is installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script tabulate is installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The script uvicorn is installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  The scripts pio, piodebuggdb and platformio are installed in '/home/gitpod/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed aiofiles-22.1.0 ajsonrpc-1.2.0 anyio-3.6.2 async-timeout-4.0.2 bottle-0.12.23 certifi-2022.9.24 charset-normalizer-2.1.1 click-8.1.3 colorama-0.4.6 h11-0.14.0 idna-3.4 ifaddr-0.2.0 importlib-metadata-5.0.0 marshmallow-3.18.0 packaging-21.3 platformio-6.1.5 pyelftools-0.29 pyparsing-3.0.9 pyserial-3.5 requests-2.28.1 semantic-version-2.10.0 sniffio-1.3.0 starlette-0.21.0 tabulate-0.9.0 typing-extensions-4.4.0 urllib3-1.26.12 uvicorn-0.19.0 wsproto-1.2.0 zeroconf-0.39.4 zipp-3.10.0
/workspace/tasmocompiler/server/config/config.js:19
);
^

SyntaxError: Unexpected token ')'
    at wrapSafe (internal/modules/cjs/loader.js:1070:16)
    at Module._compile (internal/modules/cjs/loader.js:1120:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/workspace/tasmocompiler/server/git/git.js:9:73)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)

**Comment by benzino77** [comment]
> My fork contains only "development" branch (not other).
Is this the problem?

Yes. From version 9.2.0 `master`  branch (stable) of TasmoCompiler will allow to choose only stable versions of Tasmota. On the other hand `development` branch of TasmoCompiler will allow to choose only `development` branch of Tasmota.

What you need to do is change one line in `package.json` [file](https://github.com/benzino77/tasmocompiler/blob/20d55b38f5814cc527eb840f2d4b9ef47b5711a5/package.json#L3)

change line:
`version: 9.2.0`
to 
`version: 9-development`

or anything you want but the string need to contain _dev_ phrase (i.e. bovirus-dev or myversion-development).
