### ISSUE TITLE
Can You Please add french locale ?

### ISSUE THREAD

**Issue by BugsBunny1403** [benzino77/tasmocompiler#306]
I prepare an translation to french can create necessary file for this translate and after i can translate the locale file please. I ask this because i am not a good at devellopement and i wouldn't broke or fail a task.

**Comment by bovirus** [comment]
@BugsBunny1403 

Make a fork of original tasmocompiler project

Thake the english locale file (righ click on int -> save as)

https://raw.githubusercontent.com/benzino77/tasmocompiler/master/src/locales/en.json

Save it as "fr.json".
Edit and translate the strings between " " after ":".

If you want to check the syntaxc of json file you can load here

https://jsonlint.com/

If need more help post here.

**Comment by benzino77** [comment]
@BugsBunny1403 Lets make it super simple ;)

1. Save the content of the file ([link here](https://raw.githubusercontent.com/benzino77/tasmocompiler/master/src/locales/en.json)) somewhere on your computer. Right click anywhere inside the window and choose "save as" (it should work similarly in any browser you use)

![image](https://user-images.githubusercontent.com/15658235/200187040-c879f627-6dd4-4786-9476-561239842384.png)

2. Edit content of the file you saved in step 1 in any text editor you like and change all English sentences to French. You need to change only the right side of the of the `key: value` pair. I marked the part to change on the screenshot below:
![Screenshot from 2022-11-06 19-04-53](https://user-images.githubusercontent.com/15658235/200187462-894d3bb6-a7d3-4790-a5b5-13e2bb414202.png)

3. When you finish translation, upload the changed file here (just drag and drop it) and I will do the rest.

**Comment by benzino77** [comment]
Hey @BugsBunny1403 do you want to still add French translation?

**Comment by Flobul** [comment]
Hey.
I just made translations in PR there https://github.com/benzino77/tasmocompiler/pull/331
See ya
