### ISSUE TITLE
Please build tasmota-minimal.bin.gz as well as tasmota.bin.gz

### ISSUE THREAD

**Issue by elmicha** [benzino77/tasmocompiler#309]
Hi,

it would be great if TasmoCompiler could build a tasmota-minimal.bin.gz automatically, so that we could point the OtaUrl to http://our_computer:3000/download/tasmota.bin.gz.

If there is a http://our_computer:3000/download/tasmota-minimal.bin.gz, Tasmota automatically flashes this before the tasmota.bin.gz.

Thank you for TasmoCompiler!

**Comment by benzino77** [comment]
Hi,

I'm not sure it is possible. To build minimal binary TasmoCompiler should run compiling process twice: one to build binary with your settings and then second run to build minimal binary for Tasmota version you choose.

**Comment by benzino77** [comment]
I will leave this issue open so one could pick this up and make PR for that.

**Comment by Jason2866** [comment]
Why not using the provided precompiled Tasmota minimal version?
Minimal is always without any not needed driver.

**Comment by bovirus** [comment]
@Jason2866

I made a small change to original source code in my repository to enable (by default) Lite version that enable me to upgrade it via web.
 
I beleive that this option is useful for most of the user.

**Comment by benzino77** [comment]
> Why not using the provided precompiled Tasmota minimal version? Minimal is always without any not needed driver.

There can be ANY minimal version of the binary or there should be minimal version corresponding to build version?
In other words:  do one need to use minimal version v12.1.1 if version v12.1.1 is build or minimal version can be v12.0.2 and build version is  other than v12.0.2?

**Comment by benzino77** [comment]
That is a good information I think. @elmicha it looks like I can package minimal binary with TasmoCompiler, so one could point the TasmoCompiler URI to update its device.

**Comment by benzino77** [comment]
Try the `development` version of TasmoCompiler as described [here](https://github.com/benzino77/tasmocompiler#development-version) and let me know if that works for you.
