### ISSUE TITLE
language/cz-CZ.h: No such file or directory

### ISSUE THREAD

**Issue by davepee** [benzino77/tasmocompiler#31]
When I changed language to Czech I got error message: 

tasmota/i18n.h:557:37: fatal error: language/cz-CZ.h: No such file or directory
   #include INCLUDE_FILE(MY_LANGUAGE)
                                     
compilation terminated.
*** [.pioenvs/custom/src/tasmota.ino.cpp.o] Error 1
========================= [FAILED] Took 34.41 seconds =========================
Finished. Exit code: 1.

**Comment by benzino77** [comment]
Thats because Czech language file is called cs-CZ.h not cz-CZ.h - it is fixed now. If you are using docker images you have to pull new version.
Thanks for reporting issue!
