### ISSUE TITLE
Compile failure when Berry scripting is deselected...?

### ISSUE THREAD

**Issue by somni-a** [benzino77/tasmocompiler#311]
Hey benzino77, hope all is well in Poland.
After experiencing compile failures with multiple board types (although, all are ESP32) on both development and release paths, I realized it must be something I'm doing wrong.  I believe I narrowed it down to unchecking the Berry scripting.  Once I left that alone (checked by default), it compiled with no issues.  If it is relevant, I always compile with Display support.
Not a big deal now that I know what to do...but any thoughts or ideas?  Thanks, Greg

**Comment by benzino77** [comment]
I do believe that Berry Scripting is mandatory for ESP32 boards. That is why Berry Scripting is checked by default for ESP32 boards. For more information why it is (or not) mandatory for ESP32 boards I will direct you to Tasmota Discord Channel. There are plenty of people (including core Tasmota Dev Team) which will provide you more information about that.

**Comment by somni-a** [comment]
benzino77,
Thanks, the default checks make sense.  To anyone finding this in the future....leave default checks in place and only add in additional options as needed.  (to ensure code compile success)
