### ISSUE TITLE
Compiling end with Exit code 1

### ISSUE THREAD

**Issue by Sprollonis** [benzino77/tasmocompiler#312]
Hi,

just updatet to Tasmocompiler v9.21 Tried to compile esp32_webcam.bin. Compiler alwas ends with Exit.Code 1. Seems compiler do not find OneWire.h.

Could you help pls.

Thanks Sprollonis

Compiling .pio/build/tasmota32-webcam/lib767/Wire/Wire.cpp.o
/tmp/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_52_3_berry_onewire.ino:26:10: fatal error: OneWire.h: No such file or directory

*****************************************************************
* Looking for OneWire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:OneWire.h"
* Web  > https://registry.platformio.org/search?q=header:OneWire.h
*
*****************************************************************

 #include <OneWire.h>
          ^~~~~~~~~~~
compilation terminated.
*** [.pio/build/tasmota32-webcam/src/tasmota.ino.cpp.o] Error 1
========================= [FAILED] Took 91.69 seconds =========================

Environment       Status    Duration
----------------  --------  ------------
tasmota32-webcam  FAILED    00:01:31.688
==================== 1 failed, 0 succeeded in 00:01:31.688 ====================
Finished. Exit code: 1.

**Comment by benzino77** [comment]
https://github.com/benzino77/tasmocompiler/issues/298

**Comment by Sprollonis** [comment]
...thanks - now it works fine!

Sprollonis
