### ISSUE TITLE
Error:Unable to get TAGS

### ISSUE THREAD

**Issue by Kugeleis** [benzino77/tasmocompiler#317]
Starting the latest tasmocompiler (v9.2.1) on gitpod, the GUI runs into this error after clicking 'Download source'.

**Comment by benzino77** [comment]
That is because there is "strange" tag on Tasmota side: `v12.3.1old` which cannot be parsed by TasmoCompiler.

**Comment by benzino77** [comment]
TasmoCompiler should now work better.
