### ISSUE TITLE
Option for ESP32S3 board "qio_opi" needed

### ISSUE THREAD

**Issue by rug1024** [benzino77/tasmocompiler#334]
I love using TasmoCompiler. I tried to use the development version to build firmware for my ESP32S3.
By default TasmoCompiler sets "board = esp32s3-qio_qspi", I cannot override this parameter.
PSRAM will not be detected on boot when wrong board type is set (needed for I2S audio streaming).
Can you make it possible to compile for "esp32s3-qio_**opi**" board too?
For now it is only possible to build correct firmware with PlatformIO for this board, but it is much more time consuming.

**Comment by benzino77** [comment]
I don't want to overload TasmoCompiler GUI with too many options. I want it to be as simple as possible. It will eventually confuse users: *"Should I use QSPI or OPI?"*. QSPI is a default option in Tasmota for S3 boards so I want to keep it like this.


But you can build your own version of Tasmocompiler (that is a beauty of Open Source!!!)
1. Fork Tasmocompiler repository
2. Change `src/components/AppStepper/FeaturesStep/AvailableBoards.js` file

Locate the `esp32s3` board definition in the file above (starting from line 333), and change the `board` part:

```js
 {
    name: 'esp32s3',
    chip_type: 'esp32',
    description: 'ESP32 S3',
    default: false,
    show: true,
    platformio_entries: {
      extends: 'env:tasmota32_base',
      board: 'esp32s3-qio_opi', <--- THIS IS THE LINE YOU NEED TO CHANGE
      // eslint-disable-next-line
      build_flags: '${env:tasmota32_base.build_flags}',
      lib_ignore: ['TTGO TWatch Library', 'Micro-RTSP', 'epdiy'],
    },
    platformio_env_name: 'tasmota32s3',
    tooltip: '',
    include_features: ['berry', 'ufilesys', 'rules'],
    exclude_features: [],
    defines: {},
  },
```
You can also define additional S3 definition to keep ability to choose between them. You need to duplicate the board definition definition and assure distinct names:
```js
 {
    name: 'esp32s3-qspi', <---- NAME
    chip_type: 'esp32',
    description: 'ESP32 S3 QSPI',
    default: false,
    show: true,
    platformio_entries: {
      extends: 'env:tasmota32_base',
      board: 'esp32s3-qio_qspi',
      // eslint-disable-next-line
      build_flags: '${env:tasmota32_base.build_flags}',
      lib_ignore: ['TTGO TWatch Library', 'Micro-RTSP', 'epdiy'],
    },
    platformio_env_name: 'tasmota32s3',
    tooltip: '',
    include_features: ['berry', 'ufilesys', 'rules'],
    exclude_features: [],
    defines: {},
  },
 {
    name: 'esp32s3-opi', <---- NAME
    chip_type: 'esp32',
    description: 'ESP32 S3 OPI',
    default: false,
    show: true,
    platformio_entries: {
      extends: 'env:tasmota32_base',
      board: 'esp32s3-qio_opi',
      // eslint-disable-next-line
      build_flags: '${env:tasmota32_base.build_flags}',
      lib_ignore: ['TTGO TWatch Library', 'Micro-RTSP', 'epdiy'],
    },
    platformio_env_name: 'tasmota32s3',
    tooltip: '',
    include_features: ['berry', 'ufilesys', 'rules'],
    exclude_features: [],
    defines: {},
  },
```



Then build your own version of Tasmocompiler docker image:
```sh
docker build -t my-tasmocompiler .
docker run --rm --name tasmocompiler -p 3000:3000 my-tasmocompiler
```

If you are using Gitpod, just push your changes to the GitHub repo and point gitpod to it:
https://gitpod.io/#https://github.com/rug1024/tasmocompiler

Happy Tasmotizing ;)

**Comment by rug1024** [comment]
I had to learn that it's really **that easy**! Thank you!
Firmware is working fine.
