### ISSUE TITLE
Enabling Air/Gas Sensors doesn't enable SGP40

### ISSUE THREAD

**Issue by richard-scott** [benzino77/tasmocompiler#335]
i2scan shows the sensor address but I've had to also enable USE_SGP40 to get this sensor to show up.

**Comment by benzino77** [comment]
Hi,
Sure, because it is not included in there: [FEATURES_DESC](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md) ;)

PR's are welcome ;)

**Comment by benzino77** [comment]
Completely forgot about that one - sorry for that. I've added `USE_SGP4X` in a group of "Air/gas sensors". It is now available i `development` branch of TasmoCompiler.
