### ISSUE TITLE
Litte Feature Request link to main website

### ISSUE THREAD

**Issue by bobybobybob** [benzino77/tasmocompiler#338]
Something very simple and practical. Please put a link here at TasmoCompiler so that you can check more conveniently if there is a new version or not. Currently I have two bookmarks

**Comment by benzino77** [comment]
What you mean by that?

**Comment by benzino77** [comment]
I get your point. I will think about it.

**Comment by benzino77** [comment]
![Screenshot from 2023-02-26 17-01-47](https://user-images.githubusercontent.com/15658235/221421679-3e9321af-accb-4874-ad76-31e9eecbc1de.png)

I've added small Github icon to the application AppBar. When clicked new tab is opened with project Github page.

**Comment by bobybobybob** [comment]
Thank very you much
