### ISSUE TITLE
Add in the interface selection for custom preset

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#340]
@benzino77 

Could you please add in GUI after board selection a multi selction of custom pre-set like

firmware lite option
enable homekit
etc
 
in this way can help a lot of user to create custom version (ex. lite or homekit) with base functions.

**Comment by benzino77** [comment]
> firmware lite option enable 

No.

> homekit 

I will think about it.

> etc

What stands behind this?

**Comment by bovirus** [comment]
Why "What stands behind this?"

My scope is very simple to understand.
It's enable more users to use powerful functions (like Firware lite or HomeKit) withourt a big knowledge and manual changes to the interface.

I didn't understand why "Home Kit" yes and "Firmware lite" no.

"Firmware lite" is one of most usfeul function because you can create a firmware that can be uploaded directly in one step (instead original bigger firmware that require two speps - first minimal firmware then full firmware).

To do that you should manual setup (every time), knowledge it and setup it.

If you have just a "Special option" area in your interface (after board selection) where a user can select some special custom package set (as "Firmware Lite" or "HomeKit") it can add automatically the relative instructions in custom parameters that can help thousand of users to use it.

**Comment by benzino77** [comment]
The [OTA magic](https://tasmota.github.io/docs/Upgrading/) is already included in `development` branch and it will be finally included in `master` branch. Have a look here: #309. You are able to point TasmoCompiler URL in OTA URL field and there should be `minimal` version applied before full version.

>If you have just a "Special option" area in your interface (after board selection) where a user can select some special custom package set (as "Firmware Lite" or "HomeKit") it can add automatically the relative instructions in custom parameters that can help thousand of users to use it.

The beauty of Open Source is that you can do whatever you want and customize the software for your needs.  Feel free to customize TasmoCompiler in a way you need or want!

**Comment by bovirus** [comment]
@benzino77 

Thanks for the OTA magic.

Currently in my branch I added by default the Firmware lite option by default.

My scope is to avoid to modify any of your new build but to have this if it's possible in stable branch.

Thanks.

**Comment by Jason2866** [comment]
The Lite firmware ONLY exists since the crappy Sonoff Basic R2 is not able to run the standard Tasmota version. The reason is the bad bad power supply which can't handle the few mA more current needed sometimes! from the full Tasmota version.
It does not exist because of upgrading.

**Comment by bovirus** [comment]
@Jason2866 

As I know is not a problem of mA but about the flash size that cannot contain two copies of full firmware but contain two copies of lite firmware (under 512KB) and the tasmota device switch the new firmware when complete the loading of new firmware.

**Comment by Jason2866** [comment]
@bovirus  You are wrong. For flashing which does not work because target and/or current firmware is to big the `minimal` variant is used.

**Comment by bovirus** [comment]
@Jason2866 

To flash directly on some units with a flash size of 1MB you and you want to flash via webui you should have a firmare with a size <512KB (to laod it in second part oif teh flash and sawp it when is complete):
You can do it with minimal (but require then a second step to flash a full firmware) or flash Lite firmware (that is under 512KB) and don't require an addition step.
Then the Lite flash scoip is toi use webui and avoid a second flash step.

**Comment by Jason2866** [comment]
@bovirus  side effect of lite Version. Since Andre Thomas and i created the variant lite we know what the reason is for creating ;-)
The orig. name was "Sonoff-basic". Go back in Tasmota releases and issues and you will find.
