### ISSUE TITLE
Build is missing Modbus features with Modbus checked.

### ISSUE THREAD

**Issue by JanX2** [benzino77/tasmocompiler#344]
Thank you for this awesome project!

I tried to get a custom build for either ESP32 devkit or a generic ESP8266 including Modbus bridge and Modbus TCP functionality. The default Tasmota release for ESP32 (tasmota32.bin) contains only the Modbus bridge functionality so this seemed the only way.

I’m using gitpod.io.

At first I simply tried to use the web interface to set up my build:
Tasmota source code
WiFi configuration (my Wifi)
Select features (with Modbus checked)
Custom parameters (none)
Select version and compile (latest version)

That didn’t work: ModBr RX and ModBr TX were missing from the “Module parameters” for the pins in the Tasmota web UI. 

So I tried the official tasmota32.bin and that got me to at least get Modbus serial working. The Modbus TCP apparently isn’t enabled in the official builds. This means for example the that console command “ModbusTCPStart 502” will fail with “RESULT = {"Command":"Unknown"}”.

Then I tried Tasmota again via gitpod.io. Same settings as above, but this time with Modbus checked and these “Custom parameters”
```
#ifndef USE_MODBUS_BRIDGE
#define USE_MODBUS_BRIDGE       // Add support for software Modbus Bridge (+3k code)
#define USE_MODBUS_BRIDGE_TCP   // Add support for software Modbus TCP Bridge (Must also enable USE_MODBUS_BRIDGE)
#endif
```

Still no dice.

And finally:
```
#ifndef USE_MODBUS_BRIDGE
#define USE_MODBUS_BRIDGE       // Add support for software Modbus Bridge (+3k code)
#endif
#ifndef USE_MODBUS_BRIDGE_TCP
#define USE_MODBUS_BRIDGE_TCP   // Add support for software Modbus TCP Bridge (Must also enable USE_MODBUS_BRIDGE)
#endif
```

And again so support for either “ModBr RX“ or “ModBr TX” for the pins and “ModbusTCPStart 502” is still failing.

I’m at all out of ideas about what to try next. Any pointers? What am I missing?

Thank you again!

**Comment by benzino77** [comment]
Jan, try to contact Tasmota Dev Team on discord. As stated here: https://tasmota.github.io/docs/Modbus-Bridge this functionality should be enabled by:
```c
#ifndef USE_MODBUS_BRIDGE
#define USE_MODBUS_BRIDGE       // Add support for software Modbus Bridge (+3k code)
#define USE_MODBUS_BRIDGE_TCP   // Add support for software Modbus TCP Bridge (Must also enable USE_MODBUS_BRIDGE)
#endif
```
and exactly that is enabled by TasmoCompiler when Modbus Bridge is selected as the feature (described [here](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md))

For sure you have to assign GPIO pins in your Tasmota configuration for Modbus to work properly (docs mentioned above)

**Comment by JanX2** [comment]
Thanks @benzino77! I got Modbus working with the official release as stated. But not the TCP bridge.

**Comment by lyazide** [comment]
> Thank you for this awesome project!
> 
> I tried to get a custom build for either ESP32 devkit or a generic ESP8266 including Modbus bridge and Modbus TCP functionality. The default Tasmota release for ESP32 (tasmota32.bin) contains only the Modbus bridge functionality so this seemed the only way.
> 
> I’m using gitpod.io.
> 
> At first I simply tried to use the web interface to set up my build: Tasmota source code WiFi configuration (my Wifi) Select features (with Modbus checked) Custom parameters (none) Select version and compile (latest version)
> 
> That didn’t work: ModBr RX and ModBr TX were missing from the “Module parameters” for the pins in the Tasmota web UI.
> 
> So I tried the official tasmota32.bin and that got me to at least get Modbus serial working. The Modbus TCP apparently isn’t enabled in the official builds. This means for example the that console command “ModbusTCPStart 502” will fail with “RESULT = {"Command":"Unknown"}”.
> 
> Then I tried Tasmota again via gitpod.io. Same settings as above, but this time with Modbus checked and these “Custom parameters”
> 
> ```
> #ifndef USE_MODBUS_BRIDGE
> #define USE_MODBUS_BRIDGE       // Add support for software Modbus Bridge (+3k code)
> #define USE_MODBUS_BRIDGE_TCP   // Add support for software Modbus TCP Bridge (Must also enable USE_MODBUS_BRIDGE)
> #endif
> ```
> 
> Still no dice.
> 
> And finally:
> 
> ```
> #ifndef USE_MODBUS_BRIDGE
> #define USE_MODBUS_BRIDGE       // Add support for software Modbus Bridge (+3k code)
> #endif
> #ifndef USE_MODBUS_BRIDGE_TCP
> #define USE_MODBUS_BRIDGE_TCP   // Add support for software Modbus TCP Bridge (Must also enable USE_MODBUS_BRIDGE)
> #endif
> ```
> 
> And again so support for either “ModBr RX“ or “ModBr TX” for the pins and “ModbusTCPStart 502” is still failing.
> 
> I’m at all out of ideas about what to try next. Any pointers? What am I missing?
> 
> Thank you again!

I have the same issue. I checked the Modbus Bridge but can not get the "MODBr" RX and TX in the web configuration.
Did you get this solved?

**Comment by JanX2** [comment]
@lyazide 
The only fix I found is to roll my own binary locally. This may have changed since that.

**Comment by nonix** [comment]
Hi I am sorry to add firewood into this older bug report. However, I have hit the exact same issue today.
Using tasmocompiler with selection of "ModBus Bridge" the Modbus bridge will not get compiled in.
After a short exchange with Sfromis [Discord chat](https://discord.com/channels/479389167382691863/490244847568158751/1213876922614939748)

It was clear and confirmed that Tasmocompiler has a typo in the \#define USE_MODBUSBRIDGE instead of correct on: \#define USE_MODBUS_BRIDGE 
Note: the underscore between MODBUS and(_) BRIDGE. Hope this helps a bit.

**Comment by nonix** [comment]
> Jan, try to contact Tasmota Dev Team on discord. As stated here: https://tasmota.github.io/docs/Modbus-Bridge this functionality should be enabled by:
> 
> ```c
> #ifndef USE_MODBUS_BRIDGE
> #define USE_MODBUS_BRIDGE       // Add support for software Modbus Bridge (+3k code)
> #define USE_MODBUS_BRIDGE_TCP   // Add support for software Modbus TCP Bridge (Must also enable USE_MODBUS_BRIDGE)
> #endif
> ```
> 
> and exactly that is enabled by TasmoCompiler when Modbus Bridge is selected as the feature (described [here](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md))
> 
> For sure you have to assign GPIO pins in your Tasmota configuration for Modbus to work properly (docs mentioned above)

Seem like a typo, the underscores are missing (just cut & paste from Tasmocompiled FW 13.3.0)
```
#ifdef USE_MODBUSBRIDGE
  #undef USE_MODBUSBRIDGE
#endif
#define USE_MODBUSBRIDGE

```
>

**Comment by benzino77** [comment]
Thanks for this finding! Great job. I will fix it soon.

**Comment by benzino77** [comment]
I've push changes to `development` branch (link to  [gitpod](https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/development)) and `benzino77/tasmocompiler:development` docker image. @nonix  could you please check if this is working as expected now?

**Comment by benzino77** [comment]
I'm glad to hear it. Thanks for your help! I will release new stable version as soon as I have some free time.
