### ISSUE TITLE
Failed compilation for tasmota32-webcam and Temperature/humidity sensors feature

### ISSUE THREAD

**Issue by suisk1ptitmotard** [benzino77/tasmocompiler#345]
Hello,
I have a compilation error with the "Temperature/humidity sensors" feature. (if disable this option the compilation works)

Thanks for your help

Processing tasmota32-webcam (board: esp32-fix; framework: arduino; platform: https://github.com/tasmota/platform-espressif32/releases/download/2023.01.01/platform-espressif32.zip)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32-fix.html
PLATFORM: Espressif 32 (2023.1.1) > Espressif Generic ESP32 >= 4M Flash, PSRAM with fix, Tasmota 2880k Code/OTA, 320k FS
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 2.0.6 
 - tool-esptoolpy @ 1.40404.0 (4.4.4) 
 - tool-mklittlefs @ 1.203.210628 (2.3) 
 - tool-mkspiffs @ 2.230.0 (2.30) 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Converting tasmota.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ strict
Found 46 compatible libraries
Scanning dependencies...
Dependency Graph
|-- EEPROM 24C128_256_521
|   |-- Wire @ 2.0.0
|-- FFat @ 2.0.0
|   |-- FS @ 2.0.0
|-- FS @ 2.0.0
|-- HttpClient light for Berry @ 1.0
|   |-- HTTPUpdate @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- Update @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- HTTPClient @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- WiFiClientSecure @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- ESP32-to-ESP8266-compat @ 0.0.2
|   |   |-- WiFi @ 2.0.0
|   |   |-- WebServer @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- FS @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- HTTPUpdate @ 2.0.0
|   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- Update @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |-- ESPmDNS @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- TLS mini client derived from Arduino @ 1.0
|   |   |-- WiFi @ 2.0.0
|   |   |-- BearSSL @ 0.6
|   |   |-- ESP32-to-ESP8266-compat @ 0.0.2
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WebServer @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- FS @ 2.0.0
|   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- HTTPUpdate @ 2.0.0
|   |   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- Update @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- ESPmDNS @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|-- UdpListener @ 1.0
|-- Unishox Compressor Decompressor highly customized and optimized for ESP8266 and Tasmota @ 1.0
|-- TLS mini client derived from Arduino @ 1.0
|   |-- WiFi @ 2.0.0
|   |-- BearSSL @ 0.6
|   |-- ESP32-to-ESP8266-compat @ 0.0.2
|   |   |-- WiFi @ 2.0.0
|   |   |-- WebServer @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- FS @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- HTTPUpdate @ 2.0.0
|   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- Update @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |-- ESPmDNS @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|-- Zip-readonly-FS @ 1.0
|   |-- FS @ 2.0.0
|   |-- TasmotaLList @ 1.0
|-- Berry Tasmota mapping @ 1.0
|   |-- Berry @ 7.0
|   |   |-- re1.5 @ 0.9
|   |-- Berry mapping to C @ 1.0
|   |   |-- Berry @ 7.0
|   |   |   |-- re1.5 @ 0.9
|   |-- ccronexpr
|   |-- Zip-readonly-FS @ 1.0
|   |   |-- FS @ 2.0.0
|   |   |-- TasmotaLList @ 1.0
|   |-- FS @ 2.0.0
|   |-- LittleFS @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- Unishox Compressor Decompressor highly customized and optimized for ESP8266 and Tasmota @ 1.0
|-- Berry @ 7.0
|   |-- re1.5 @ 0.9
|-- Berry int64 implementation for 32 bits architceture @ 1.0
|   |-- Berry @ 7.0
|   |   |-- re1.5 @ 0.9
|   |-- Berry mapping to C @ 1.0
|   |   |-- Berry @ 7.0
|   |   |   |-- re1.5 @ 0.9
|-- Berry mapping to C @ 1.0
|   |-- Berry @ 7.0
|   |   |-- re1.5 @ 0.9
|-- Berry Matter protocol implementation @ 0.1
|   |-- Berry @ 7.0
|   |   |-- re1.5 @ 0.9
|   |-- Berry mapping to C @ 1.0
|   |   |-- Berry @ 7.0
|   |   |   |-- re1.5 @ 0.9
|-- headers
|   |-- EEPROM @ 2.0.0
|   |-- ESP32-to-ESP8266-compat @ 0.0.2
|   |   |-- WiFi @ 2.0.0
|   |   |-- WebServer @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- FS @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- HTTPUpdate @ 2.0.0
|   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- Update @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |-- ESPmDNS @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- ccronexpr
|-- ESP32-to-ESP8266-compat @ 0.0.2
|   |-- WiFi @ 2.0.0
|   |-- WebServer @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |-- HTTPClient @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- HTTPUpdate @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- Update @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- ESPmDNS @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|-- re1.5 @ 0.9
|-- Micro-RTSP @ 0.1.6
|   |-- WiFi @ 2.0.0
|-- DHT sensor library @ 1.4.3
|-- DNSServer @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- ESP Mail Client @ 1.2.0
|   |-- ESP32-to-ESP8266-compat @ 0.0.2
|   |   |-- WiFi @ 2.0.0
|   |   |-- WebServer @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- FS @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- HTTPUpdate @ 2.0.0
|   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- Update @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |-- ESPmDNS @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- Ethernet @ 2.0.0
|   |   |-- WiFi @ 2.0.0
|   |-- FS @ 2.0.0
|   |-- SD @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |   |-- SPI @ 2.0.0
|   |-- LittleFS @ 2.0.0
|   |   |-- FS @ 2.0.0
|   |-- SD_MMC @ 2.0.0
|   |   |-- FS @ 2.0.0
|-- Ethernet @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- JSMN JSON parser customized and optimized for ESP8266 and Tasmota @ 1.0
|-- TasmotaLList @ 1.0
|-- LinkedList
|-- LittleFS @ 2.0.0
|   |-- FS @ 2.0.0
|-- PubSubClient @ 2.8
|-- Ext-printf @ 1.0
|-- SD @ 2.0.0
|   |-- FS @ 2.0.0
|   |-- SPI @ 2.0.0
|-- SD_MMC @ 2.0.0
|   |-- FS @ 2.0.0
|-- SPI @ 2.0.0
|-- TasmotaSerial @ 3.6.0
|   |-- ESP32-to-ESP8266-compat @ 0.0.2
|   |   |-- WiFi @ 2.0.0
|   |   |-- WebServer @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- FS @ 2.0.0
|   |   |-- HTTPClient @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |-- HTTPUpdate @ 2.0.0
|   |   |   |-- HTTPClient @ 2.0.0
|   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |   |-- WiFiClientSecure @ 2.0.0
|   |   |   |   |   |-- WiFi @ 2.0.0
|   |   |   |-- Update @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|   |   |-- ESPmDNS @ 2.0.0
|   |   |   |-- WiFi @ 2.0.0
|-- Ticker @ 2.0.0
|-- WiFiClientSecure @ 2.0.0
|   |-- WiFi @ 2.0.0
|-- Wire @ 2.0.0
|-- base64 @ 1.1.1
|-- BearSSL @ 0.6
|-- WebServer @ 2.0.0
|   |-- WiFi @ 2.0.0
|   |-- FS @ 2.0.0
Building in release mode
*** use provided user_config_override.h as planned ***
*** use provided platformio_override.ini as planned ***
Compiling .pio/build/tasmota32-webcam/src/tasmota.ino.cpp.o
Compiling .pio/build/tasmota32-webcam/src/tasmota_support/homekit.c.o
Compiling .pio/build/tasmota32-webcam/src/tasmota_xsns_sensor/xsns_62_esp32_mi_homekit.c.o
Building .pio/build/tasmota32-webcam/bootloader.bin
esptool.py v4.5-dev
Creating esp32 image...
Merged 1 ELF section
Successfully created esp32 image.
Generating partitions .pio/build/tasmota32-webcam/partitions.bin
Compiling .pio/build/tasmota32-webcam/lib767/Wire/Wire.cpp.o
/tmp/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_52_3_berry_onewire.ino:26:10: fatal error: OneWire.h: No such file or directory

*****************************************************************
* Looking for OneWire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:OneWire.h"
* Web  > https://registry.platformio.org/search?q=header:OneWire.h
*
*****************************************************************

 #include <OneWire.h>
          ^~~~~~~~~~~
compilation terminated.
*** [.pio/build/tasmota32-webcam/src/tasmota.ino.cpp.o] Error 1
========================= [FAILED] Took 17.33 seconds =========================
Environment       Status    Duration
----------------  --------  ------------
tasmota32-webcam  FAILED    00:00:17.331
==================== 1 failed, 0 succeeded in 00:00:17.331 ====================

Finished. Exit code: 1.

**Comment by benzino77** [comment]
#312 
#298
