### ISSUE TITLE
Can you please add support for USE_PING?

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [benzino77/tasmocompiler#35]
As described in https://github.com/arendst/Tasmota/pull/8119

**Comment by benzino77** [comment]
Sure. For now you can put `#define USE_PING` in "Custom parameters" step.

**Comment by MarkCiliaVincenti** [comment]
I tried this and got an "Upload buffer miscompare" error.

**Comment by benzino77** [comment]
![image](https://user-images.githubusercontent.com/15658235/79039651-0d59c100-7be3-11ea-94ad-2c051eef3b8a.png)

This works for me.
