### ISSUE TITLE
Upload buffer miscompare

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [benzino77/tasmocompiler#36]
I'm trying to use this tool, but every time I'm trying to upload the new firmware it keeps throwing an error "Upload buffer miscompare".

**Comment by ascillato** [comment]
"Upload buffer miscompare" means that your firmware is bigger than the available space in your flash. As explained in the docs, you need to flash the MINIMAL version FIRST, to free space, and THEN flash your full version.

**Comment by MarkCiliaVincenti** [comment]
Thanks!

**Comment by benzino77** [comment]
Thanks @ascillato!
