### ISSUE TITLE
Including BLE support causes an error: NimBLEDevice.h

### ISSUE THREAD

**Issue by gdudek** [benzino77/tasmocompiler#361]
Can't compile in BLE support.

    "bluetooth": true,
    "USE_BLE_ESP32": true,

on board esp32webcam

leads to the error:

compile /tmp/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_79_esp32_ble.ino:148:10: fatal error: NimBLEDevice.h: No such file or directory

**Comment by benzino77** [comment]
Hi,

Which version of TasmoCompiler are you using? The stable one `v10.4.x` or `development`?

**Comment by gdudek** [comment]
This was with v10.4.0

**Comment by benzino77** [comment]
You have to ask Tasmota Dev Team. Have a look here: https://github.com/arendst/Tasmota/blob/d72f3b99782fb926e0fa57c62b914cafea9c2478/tasmota/include/tasmota_configurations_ESP32.h#L197

This is a standard set of defines and undefines for Webcam board. For some reason BLE support for this board is disabled (undefined) by default. You can also read other threads here (https://github.com/benzino77/tasmocompiler/issues/345) and on Tasmota GitHub page related to Webcam board (https://github.com/arendst/Tasmota/issues/18078)

**Comment by gdudek** [comment]
Thanks for this.  It's apparently a performance choice that arises due to the heavy requirements when using the webcam.

**Comment by gdudek** [comment]
Thanks for this. It's apparently a performance choice that arises due to the heavy requirements when using the webcam.  In theory, both might be enabled if used judiciously (and might fit in memory), but it would invite subsequent problems.
