### ISSUE TITLE
esp32-cam ai-thinker compile with BME280 fails

### ISSUE THREAD

**Issue by ubeaut** [benzino77/tasmocompiler#364]
I am trying to compile with temp/hum support the compile fails.

I am not a programmer and don't really nderstand this stuff but here is the error:
*****************************************************************
* Looking for OneWire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:OneWire.h"
* Web  > https://registry.platformio.org/search?q=header:OneWire.h
*
*****************************************************************

 #include <OneWire.h>
          ^~~~~~~~~~~
compilation terminated.
*** [.pio/build/tasmota32-webcam/src/tasmota.ino.cpp.o] Error 1
========================= [FAILED] Took 19.40 seconds =========================

**Comment by benzino77** [comment]
It is a known feature of Webcam module. Please have a look at those discussions:

https://github.com/benzino77/tasmocompiler/issues/298
https://github.com/benzino77/tasmocompiler/issues/303
https://github.com/benzino77/tasmocompiler/issues/312
https://github.com/benzino77/tasmocompiler/issues/326
https://github.com/benzino77/tasmocompiler/issues/345
