### ISSUE TITLE
Compile tasmota, add "option -DUSE_4K_RSA" problem

### ISSUE THREAD

**Issue by wei1980okb** [benzino77/tasmocompiler#365]
Hi, I have a problem and need help with compiling tasmota.
I added "MQTT over TLS" firmware support through "TasmoCompiler v11.0.0", and the compilation was successful.
But now through tasmota web setting and testing, it is found that the TLS certificate used by the server is RSA 4096, and tasmota connects to mosquito.
The console reports the following error "08:09:07.056 MQT: TLS connection error: 56
08:09:07.060 MQT: Connection failed: 192.168.1.2:2884, rc -2. Retry countdown: 120 seconds"
mosquito reported the following error:
1690010243: New connection from 192.168.1.18:55734 on port 1884.
1690010246: Client <unknown> disconnected: Protocol error.

Find out through the official link below:
=========
https://tasmota.github.io/docs/TLS/#limitations
================

The server certificate must have an RSA private key (max 2048 bits) and the certificate must be signed with RSA and SHA256 hash. This is the case with default LetsEncrypt certificates. ESP32 supports by default RSA private keys up to 4096 bits, ESP8266 must be compiled with option -DUSE_4K_RSA to support 4096 private keys.

==========================

I don't know how this "option -DUSE_4K_RSA" is added in "TasmoCompiler".

**Comment by benzino77** [comment]
Hi,

In the "Custom parameters" step, put that in the text field:
```C
#ifdef USE_4K_RSA
  #undef USE_4K_RSA
#endif
#define USE_4K_RSA
```

**Comment by wei1980okb** [comment]
> 
Hi, thank you very much for your guidance
According to your method, I recompiled the firmware, and the compilation was successful. After flashing the firmware test, the error "Client disconnected: Protocol error." in the previous article still appeared, and tasmota could not connect to mosquitto.
I don’t know whether it’s the “USE_4K_RSA” adding problem, or tasmota has another problem. I use tls to connect to mosquitto through nodered’s mqtt in, and everything is normal. Please advise. Thanks

**Comment by wei1980okb** [comment]
Thank You
