### ISSUE TITLE
esp32 webcam, missing librarys temp/hum sensors

### ISSUE THREAD

**Issue by roschme** [benzino77/tasmocompiler#366]
Hi benzino77,

i've here an issue with compiling tasmota for esp32 webcam with(!) support for temp/hum sensors.
Seems to me that the needed librarys (eg. onewire.h) are not loaded when selecting ESP32 webcam option.
If i use generic ESP32 then all librarys will be (pre) loaded and the compiling shows success.

gipod or local docker, development or stable branch: same behaviour

thank you for your work! tasmocompiler is very, very helpful!

**Comment by benzino77** [comment]
Hi,

Have a look here: https://github.com/benzino77/tasmocompiler/issues/364
