### ISSUE TITLE
Can't compile tasmota32 13.1.0 as depends on PlatformIO Core >=6.1.9.

### ISSUE THREAD

**Issue by poggenpower** [benzino77/tasmocompiler#373]
If selecting esp32/generic as board, the compile job is failing with:
``` 
Error: Development platform 'espressif32' is not compatible with PlatformIO Core v6.1.7 and depends on PlatformIO Core >=6.1.9.
```
I am unsure if the `PlatfromIO Core` version is controlled by tasmocompiler, if not let me know.

**Comment by poggenpower** [comment]
Forgot to say, that I have used the container. Rebuilding it, solves the issue, because the latest platformio version is pulled. 
@benzino77 can you kick of an new build job, that the docker image gets updated. Thanks

**Comment by benzino77** [comment]
Thanks for the report Thomas! I've already pushed new docker images, so you can check them on your side.

**Comment by poggenpower** [comment]
Yes can confirm, the fresh pulled "latest" image compiles trough.
