### ISSUE TITLE
Problem with ESP32 and bluetooth: NimBLEDevice.h

### ISSUE THREAD

**Issue by Smandurlo** [benzino77/tasmocompiler#375]
I am trying to compile an ESP32 with bluetooth and mitsubishi miel hvac. I was able in the past, now I am not able anymore. It happens when I select bluetooth or I try to add #define USE_MI_ESP32

It is related with the bluetooth option, it doesn't matter what I select, the moment I add bluetooth I get this error:

/tmp/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_79_esp32_ble.ino:148:10: fatal error: NimBLEDevice.h: No such file or directory

**********************************************************************
* Looking for NimBLEDevice.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:NimBLEDevice.h"
* Web  > https://registry.platformio.org/search?q=header:NimBLEDevice.h
*
**********************************************************************

 #include <NimBLEDevice.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio/build/tasmota32/lib8ec/freetype/smooth/smooth.c.o
*** [.pio/build/tasmota32/src/tasmota.ino.cpp.o] Error 1
========================= [FAILED] Took 48.93 seconds =========================

Environment    Status    Duration
-------------  --------  ------------
tasmota32      FAILED    00:00:48.928
==================== 1 failed, 0 succeeded in 00:00:48.928 ====================
Finished. Exit code: 1.

**Comment by benzino77** [comment]
Hi,

It looks like there is something wrong when Tasmota v13.1.0 is chosen (v13.0.0 works fine on my side).
Please contact Tasmota Dev Team (via Discord channel) and describe that situation.

**Comment by Smandurlo** [comment]
I found out the "problem" and the solution: https://github.com/arendst/Tasmota/discussions/19663

**Comment by benzino77** [comment]
I've made some tweaks on my side to be compatible with the latest changes in Tasmota. Could you please check the new version of TC?

**Comment by Smandurlo** [comment]
yes, it works now :-)

**Comment by Smandurlo** [comment]
fixed
