### ISSUE TITLE
Unattended/programmatic compile

### ISSUE THREAD

**Issue by milkpirate** [benzino77/tasmocompiler#377]
Hey,

can I compile a binary without using the web interface? Like mounting a config file into the container and start the compile via `exec` or just `run`? Is that possible?

Best regards

**Comment by benzino77** [comment]
TC is not intended to use it that way... but theoretically it should be possible.
Have you try to use https://github.com/tasmota/docker-tasmota? You can prepare your `user_config_override.h` and `platformio_override.ini` using TasmoCompiler (those files are available to download at the end of TC compilation) and use them with `docker-tasmota` (but I never use this tool).

For other possibilities have a look at official Tasmota documentation: https://tasmota.github.io/docs/Compile-your-build/

**Comment by milkpirate** [comment]
Oh thanks, will have a look! :+1:
