### ISSUE TITLE
[feature request] add ESP8266 4MB build variant

### ISSUE THREAD

**Issue by bam80** [benzino77/tasmocompiler#380]
And/or allow custom `platformio_override.ini`, beside `user_config_override.h` one.

**Comment by benzino77** [comment]
There is such possibility in TasmoCompiler to compile for 4MB boards:
![image](https://github.com/benzino77/tasmocompiler/assets/15658235/fd306d8c-2f54-44e7-bac0-20ecb442f5f9)

It will use 4M2M memory layout.

I'm not sure if adding additional step "Custom platformio entries" will not be too "overwhelming" for inexperienced users (TasmoCompiler was build for quick, not complicated, easy to use tool for not so "tech savvy" users).
On the other hand I can see that such functionality can be useful. I can imagine that there can be a switch called "tech savvy mode" which will show additional possibilities/features/available settings in TasmoCompiler GUI. Then more advanced users could set more advanced features.

I will leave this issue open so maybe one will pick it up and implement such functionality.

Happy Tasmotizing!

**Comment by bam80** [comment]
Thank you, that 4M option is rather hidden because my device is not Wemos/NodeMCU, so it was not obvious this option suits too

**Comment by benzino77** [comment]
You are right... it is called "Wemos/NodeMCU" just because those are the most (I believe) popular 4MB board. Some additional information is added to the "description" of the feature when you point your mouse cursor on that.
