### ISSUE TITLE
Support for Tasmota V13.3

### ISSUE THREAD

**Issue by Noschvie** [benzino77/tasmocompiler#381]
Hello

please add support for version 13.3

thanks!

https://github.com/benzino77/tasmocompiler/blob/1424e68f19763bcc5d888579b09804e5ab67c37f/server/config/config.js#L7

**Comment by bam80** [comment]
I want it too, would you make a PR maybe?

**Comment by benzino77** [comment]
I will have a look at that... next year ;)

Happy Tasmotizing!!

**Comment by benzino77** [comment]
It is already there. You can use gitpod or docker image (pull the new one) and there should be `v13.3.0` Tasmota available.
