### ISSUE TITLE
make latest Tasmota release always available to build

### ISSUE THREAD

**Issue by bam80** [benzino77/tasmocompiler#382]
https://github.com/benzino77/tasmocompiler/blob/26ebd63917a73baaafb3cdb93bd9e290a1d8eab4/server/config/config.js#L7
this needs to be bumped every now and then,
could we make latest release always available persistently?

Otherwise, issues like that are to be opened:
#381

**Comment by Noschvie** [comment]
Explained [comment #362](https://github.com/benzino77/tasmocompiler/issues/362#issuecomment-1609085109)
