### ISSUE TITLE
HDMI CEC flag not working?

### ISSUE THREAD

**Issue by claybratt** [benzino77/tasmocompiler#384]
I am trying to compile an version with the #define USE_HDMI_CEC set in the user_config_override.h but I cant tell if its compiling correctly

Edit Ok never mind, I don't know why it wouldn't work but I just figured out how to do it properly

**Comment by benzino77** [comment]
You should not edit `user_config_override.h` when using TasmoCompiler. For such changes the "Custom parameters" text field is dedicated: 
https://github.com/benzino77/tasmocompiler#how-to-use-custom-parameters
Everything you put in this text field will be added _**at the end**_ of the `user_config_override.h` file before starting compilation. You can download `user_config_override.h` file used for compilation and examine its body:
![image](https://github.com/benzino77/tasmocompiler/assets/15658235/cd004aa3-016e-42ec-a8e9-d66937b22950)
