### ISSUE TITLE
ESP32-S2 & S3 missing Bluetooth feature option.

### ISSUE THREAD

**Issue by mrjackson** [benzino77/tasmocompiler#386]
Bluetooth is not available under the features for the S2 and S3 model.
It is listed under all the other ESP32 models.

**Comment by benzino77** [comment]
Hi,

Sorry for the lag in a response. Does S2 module have BT capabilities?

S2 module: https://www.espressif.com/sites/default/files/documentation/esp32-s2_datasheet_en.pdf
S3 module: https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf

It looks like only S3 have BT included... but I might be wrong.
I will try to add S3 to the list of boards with BT capabilities soon. For now you can always use "Custom parameters" text field to put all `#define`'s that are needed for BT to work.

**Comment by mrjackson** [comment]
You are right, S2 does not have BT (I was working with a S3 and looked at all the other boards when making the issue). You learn something every day!
I'll try the #define if you don't get it done before I get a few minutes.
Thanks

**Comment by benzino77** [comment]
Thanks for pointing out the shortcomings. It should be fixed now. 
Happy Tasmotizing!
