### ISSUE TITLE
Modify tasmocompiler to read personal fork of tasmota branch

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#39]
@benzino77 

If I want to test personal change of source code/webUi before to propose a PR to the original source code could be intersting to add an option to load source tree from a personal fork on Github.

Could be possible to implement this?

Thanks. KR.

**Comment by benzino77** [comment]
Sure. It's open source. You can clone repo, make changes and create pull request.

**Comment by bovirus** [comment]
@benzino77 

Sorry for my not clear explanation.

My request if you can modify teh source of tasmocompiler to read not only master/development tasmota official repository but also for eample a personal fork (available on my github account) of tasmota firmware, where I'm testing some changes to GUI/source code.

In this way I compile the firmware by my personal rfork and then I can test in place,.

Thanks.

**Comment by benzino77** [comment]
Now, I'm on the same page. Have a look here: [ADVANCED USAGE](https://github.com/benzino77/tasmocompiler/blob/master/ADVANCED.md)

There is a section how to compile your own fork of Tasmota. It is not updated (I forgot about it) and there should be `/tmp/Tasmota` not `/tmp/Sonoff-Tasmota` but in general you will suss the intention.

**Comment by bovirus** [comment]
@benzino77 

Thanks for the info.
I believe that could be add in home page of your repository as info.

Thanks a lot for your compiler.

**Comment by benzino77** [comment]
Your fork, has to have `development` branch to let `Tasmocompiler` work properly.

**Comment by bovirus** [comment]
@benzino77

I found in Winddows a way 

- to create the local copy of github repository
 - set as development brach
- replace language (to ets)

Then if you could just enable and option in the brwse this folder/repository could semplify the process.

Thanks. KR.
