### ISSUE TITLE
shutters : energy not defined in this scope

### ISSUE THREAD

**Issue by ouinouin** [benzino77/tasmocompiler#390]
Hi, got a compilation error  on tasmocompiler V11 , while compiling tasmota 13.1.0 
error was : energy : not defined in this scope,  the error occured while compiling the shutter thing.
i guess there is now a  dependency to the energy sensors on the shutter code.

i compiled again , WITH the energy tickbox ticked, and then got a success.
i dont know if your interface manages the dependencies of this kind automatically, just in case i report this , if this can help a bit some people lost with compilation errors.

indeed thanks for this software, this is very helpful to test features of tasmota.

**Comment by benzino77** [comment]
Hi,

Thanks for the hint. 
Yes I have implemented "dependencies" mechanism in TC so it need to be adjusted.

**Comment by Justdigit** [comment]
I am having the same issue..... why is this build not precompiled somewhere?

**Comment by benzino77** [comment]
Thanks for pointing out the shortcomings. It should be fixed now. 
Happy Tasmotizing!
