### ISSUE TITLE
No compile libc17/ESP8266Audio/AudioGeneratorAAC.cpp.o] Error 4

### ISSUE THREAD

**Issue by pikitry** [benzino77/tasmocompiler#395]
Hello, 
First of all, thank you very much for your work, I just discovered it and it is fantastic.
My version is TasmoCompiler v11.4.0
I have this problem when trying to compile version 13.4.0 in Spanish with the Shutters and Blinds feature:
Processing tasmota (platform: https://github.com/tasmota/platform-espressif8266/releases/download/2024.01.01/platform-espressif8266.zip; framework: arduino; board: esp8266_1M)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
-DCONFIG_TASMOTA_FLASHMODE_DOUT
*** use provided user_config_override.h as planned ***
*** use provided platformio_override.ini as planned ***
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp8266_1M.html
PLATFORM: Espressif 8266 (2024.1.1) > Espressif Generic ESP8266 Tasmota 1M sketch NO FS
HARDWARE: ESP8266 80MHz, 80KB RAM, 972.00KB Flash
PACKAGES: 
 - framework-arduinoespressif8266 @ 2.7.6 
 - tool-esptoolpy @ 1.40700.0 (4.7.0) 
 - toolchain-xtensa @ 2.40802.200502 (4.8.2)
Converting tasmota.ino
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ strict
Found 103 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Adafruit CCS811 Library @ 1.0.0
|-- Adafruit MAX31865 library @ 1.0.1
|-- Adafruit MCP9808 Library @ 1.1.2
|-- Adafruit PM25 AQI Sensor @ 1.0.6
|-- Adafruit SGP30 Sensor @ 1.2.0
|-- Adafruit SGP40 Sensor @ 1.1.0
|-- Adafruit VEML7700 Library @ 1.0.0
|-- Adafruit seesaw Library @ 1.3.1
|-- ESP8266Audio @ 1.9.5
|-- BME8563
|-- EEPROM 24C128_256_521
|-- I2Cdevlib-Core
|-- LibTeleinfo @ 1.1.5
|-- MPU6050 I2C
|-- Mutichannel_Gas_Sensor @ 0.0.1
|-- NTP Library
|-- OpenTherm Library @ 0.9.0
|-- Process_control @ 1.0.0
|-- ScioSense ENS16x @ 8.0.0
|-- ScioSense ENS210 @ 3.0.0
|-- Sensirion I2C SGP41 @ 0.1.0
|-- SevenSegmentTM1637 @ 1.1.0
|-- UdpListener @ 1.0
|-- Unishox Compressor Decompressor highly customized and optimized for ESP8266 and Tasmota @ 1.0
|-- VL53L0X @ 1.0.2
|-- VL53L1X @ 1.0.1
|-- TLS mini client derived from Arduino @ 1.0
|-- C2Programmer @ 1.0.0
|-- headers
|-- cc1101 @ 1.0
|-- ESP8266WebServer @ 1.0
|-- ams @ 1.0
|-- arduino-mcp2515-1.0.1
|-- A4988_Stepper @ 0.0.1
|-- Adafruit Fingerprint Sensor Library @ 2.1.0
|-- Adafruit GFX Library @ 1.5.6
|-- Adafruit LED Backpack Library @ 1.1.6
|-- Adafruit SH1106-gemu-1.0 @ 1.0
|-- Adafruit SSD1306 @ 1.3.0
|-- Adafruit SSD1331 OLED Driver Library for Arduino @ 1.2.0
|-- Adafruit TSL2591
|-- Arduino ST7789 Library @ 0.9.5
|-- DNSServer @ 1.1.1
|-- DS2480 Library @ 0.1.0
|-- ESP8266HTTPClient @ 1.2
|-- ESP8266SAM @ 1.0.1
|-- ESP8266WiFi @ 1.0
|-- ESP8266httpUpdate @ 1.3
|-- ESP8266mDNS @ 1.2
|-- ESPFtpServer @ 0.1.0
|-- FT5206_Library @ 1.0.0
|-- FrogmoreScd30
|-- FrogmoreScd40
|-- GT911
|-- ILI9341 @ 1.0.0
|-- IRremoteESP8266 @ 2.8.6
|-- JSMN JSON parser customized and optimized for ESP8266 and Tasmota @ 1.0
|-- KeeloqLib @ 1.1
|-- TasmotaLList @ 1.0
|-- LOLIN_HP303B @ 1.0.0
|-- LedControl @ 1.0.6
|-- LinkedList
|-- LiquidCrystal_I2C
|-- LittleFS(esp8266) @ 0.1.0
|-- MFRC522 @ 1.4.7
|-- MLX90640
|-- MPU_accel
|-- NeoPixelBus @ 2.6.7
|-- NewPing @ 1.9.1
|-- OneWire @ 2.3.2
|-- PubSubClient @ 2.8
|-- RA8876 @ 1.0.2
|-- rc-switch @ 1.0.0
|-- RF24 @ 1.3.3
|-- Ext-printf @ 1.0
|-- SD(esp8266) @ 2.0.0
|-- SPI @ 1.0
|-- SSD3115 @ 1.0
|-- ESP8266SdFat @ 1.1.0
|-- Sensirion I2C SEN5X @ 0.2.0
|-- TM1638plus @ 1.7.0
|-- TasmotaModbus @ 3.6.0
|-- TasmotaSerial @ 3.6.0
|-- Ticker @ 1.0
|-- Joba_Tsl2561 @ 2.0.10
|-- Wire @ 1.0
|-- XPT2046_Touchscreen
|-- base64 @ 1.1.1
|-- BME68x
|-- Waveshare esp 2.9 inch e-paper display driver @ 1.0
|-- Waveshare esp 4.2 inch e-paper display driver @ 1.0
|-- Display renderer @ 1.0
|-- ESP KNX IP Library @ 0.5.2
|-- HPMA115S0 Arduino Library @ 1.0.0
|-- stm32_flash @ 1.0.0
|-- BearSSL @ 0.6
|-- universal display Library @ 0.1
Building in release mode
Compiling .pio/build/tasmota/src/tasmota.ino.cpp.o
Generating LD script .pio/build/tasmota/ld/local.eagle.app.v6.common.ld
Compiling .pio/build/tasmota/lib964/Wire/Wire.cpp.o
Compiling .pio/build/tasmota/lib1ec/Adafruit_CCS811-1.0.0.14/Adafruit_CCS811.cpp.o
Compiling .pio/build/tasmota/libbb1/SPI/SPI.cpp.o
Archiving .pio/build/tasmota/lib964/libWire.a
Archiving .pio/build/tasmota/lib1ec/libAdafruit_CCS811-1.0.0.14.a
Indexing .pio/build/tasmota/lib964/libWire.a
Indexing .pio/build/tasmota/lib1ec/libAdafruit_CCS811-1.0.0.14.a
Compiling .pio/build/tasmota/libeea/Adafruit_MAX31865-1.1.0-custom/Adafruit_MAX31865.cpp.o
Compiling .pio/build/tasmota/libb35/Adafruit_MCP9808_Tasmota/Adafruit_MCP9808.cpp.o
Archiving .pio/build/tasmota/libbb1/libSPI.a
Indexing .pio/build/tasmota/libbb1/libSPI.a
Compiling .pio/build/tasmota/lib6c0/Adafruit_BusIO/Adafruit_BusIO_Register.cpp.o
Archiving .pio/build/tasmota/libb35/libAdafruit_MCP9808_Tasmota.a
Indexing .pio/build/tasmota/libb35/libAdafruit_MCP9808_Tasmota.a
Archiving .pio/build/tasmota/libeea/libAdafruit_MAX31865-1.1.0-custom
Indexing .pio/build/tasmota/libeea/libAdafruit_MAX31865-1.1.0-custom
Compiling .pio/build/tasmota/lib6c0/Adafruit_BusIO/Adafruit_I2CDevice.cpp.o
Compiling .pio/build/tasmota/lib6c0/Adafruit_BusIO/Adafruit_SPIDevice.cpp.o
Compiling .pio/build/tasmota/libcbb/Adafruit_PM25AQI-1.0.6/Adafruit_PM25AQI.cpp.o
Compiling .pio/build/tasmota/libeab/Adafruit_SGP30-1.2.0/Adafruit_SGP30.cpp.o
Archiving .pio/build/tasmota/lib6c0/libAdafruit_BusIO.a
Indexing .pio/build/tasmota/lib6c0/libAdafruit_BusIO.a
Compiling .pio/build/tasmota/lib55b/Adafruit_SGP40-1.1.0/Adafruit_SGP40.cpp.o
Archiving .pio/build/tasmota/libcbb/libAdafruit_PM25AQI-1.0.6.a
Indexing .pio/build/tasmota/libcbb/libAdafruit_PM25AQI-1.0.6.a
Compiling .pio/build/tasmota/lib55b/Adafruit_SGP40-1.1.0/sensirion_voc_algorithm.c.o
Compiling .pio/build/tasmota/lib616/Adafruit_VEML7700/Adafruit_VEML7700.cpp.o
Archiving .pio/build/tasmota/libeab/libAdafruit_SGP30-1.2.0.a
Indexing .pio/build/tasmota/libeab/libAdafruit_SGP30-1.2.0.a
Compiling .pio/build/tasmota/lib1dd/Adafruit_seesaw_soilsensor_1.3.1/Adafruit_seesaw.cpp.o
Archiving .pio/build/tasmota/lib55b/libAdafruit_SGP40-1.1.0.a
Indexing .pio/build/tasmota/lib55b/libAdafruit_SGP40-1.1.0.a
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/BearSSLHelpers.cpp.o
Archiving .pio/build/tasmota/lib616/libAdafruit_VEML7700.a
Indexing .pio/build/tasmota/lib616/libAdafruit_VEML7700.a
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/CertStoreBearSSL.cpp.o
Archiving .pio/build/tasmota/lib1dd/libAdafruit_seesaw_soilsensor_1.3.1.a
Indexing .pio/build/tasmota/lib1dd/libAdafruit_seesaw_soilsensor_1.3.1.a
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiClientSecureAxTLS.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiServer.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiServerSecureAxTLS.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiServerSecureBearSSL.cpp.o
Compiling .pio/build/tasmota/lib4d9/ESP8266WiFi/WiFiUdp.cpp.o
Compiling .pio/build/tasmota/libd4f/ESP8266HTTPClient/ESP8266HTTPClient.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/FatFile.cpp.o
Archiving .pio/build/tasmota/lib4d9/libESP8266WiFi.a
Indexing .pio/build/tasmota/lib4d9/libESP8266WiFi.a
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/FatFileLFN.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/FatFilePrint.cpp.o
Archiving .pio/build/tasmota/libd4f/libESP8266HTTPClient.a
Indexing .pio/build/tasmota/libd4f/libESP8266HTTPClient.a
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/FatFileSFN.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/FatVolume.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/FmtNumber.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/StdioStream.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/fstream.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/istream.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/FatLib/ostream.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/MinimumSerial.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SdCard/SdSpiCard.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SdCard/SdSpiCardEX.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SdCard/SdioCardEX.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SdCard/SdioTeensy.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SpiDriver/SdSpiESP8266.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SpiDriver/SdSpiParticle.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SpiDriver/SdSpiSAM3X.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SpiDriver/SdSpiSTM32.cpp.o
Compiling .pio/build/tasmota/lib483/ESP8266SdFat/SpiDriver/SdSpiTeensy3.cpp.o
Compiling .pio/build/tasmota/lib255/SDFS/SDFS.cpp.o
Compiling .pio/build/tasmota/lib2c3/SD/SD.cpp.o
Archiving .pio/build/tasmota/lib483/libESP8266SdFat.a
Indexing .pio/build/tasmota/lib483/libESP8266SdFat.a
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceBuffer.cpp.o
Archiving .pio/build/tasmota/lib2c3/libSD.a
Indexing .pio/build/tasmota/lib2c3/libSD.a
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceFS.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceFunction.cpp.o
Archiving .pio/build/tasmota/lib255/libSDFS.a
Indexing .pio/build/tasmota/lib255/libSDFS.a
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceHTTPStream.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceICYStream.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceID3.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourcePROGMEM.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceSD.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceSPIRAMBuffer.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileSourceSTDIO.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioFileStream.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioGeneratorAAC.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioGeneratorFLAC.cpp.o
Compiling .pio/build/tasmota/libc17/ESP8266Audio/AudioGeneratorMIDI.cpp.o
xtensa-lx106-elf-g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
*** [.pio/build/tasmota/libc17/ESP8266Audio/AudioGeneratorAAC.cpp.o] Error 4
========================= [FAILED] Took 170.41 seconds =========================

Environment    Status    Duration
-------------  --------  ------------
tasmota        FAILED    00:02:50.410
==================== 1 failed, 0 succeeded in 00:02:50.410 ====================
Finished. Exit code: 1.

Thanks for all

**Comment by benzino77** [comment]
Hi,
> xtensa-lx106-elf-g++: internal compiler error: Killed (program cc1plus)

This one indicates rather problem with compiler itself. What platform are you using to build your Tasmota binary? 
Gitpod? Docker container? Are you running TasmoCompiler on RaspberryPi?

**Comment by pikitry** [comment]
Hi 
I use a docker container in a RaspberryPi
Thanks for the reponse

**Comment by benzino77** [comment]
That may be a problem. If you look thru history of the issues here you will find that there was a problem here and there with "toolchains" and "copilers" on RPi. This is not a problem with RPi, Tasmota or TasmoCompiler but with "tools" needed to compile. 
If you have possibility to use regular PC or gitpod (have a look at documentation of TasmoCompiler how to use it on gitpod) that may bring better results.

**Comment by pikitry** [comment]
In a regular pc with Windows 11 work perfecto, thanks for all
