### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mtibi75** [benzino77/tasmocompiler#397]
The last week was everything fine, i can compile custom firmware. Tasmocompiler not changed, i use development docker version.
The compile log:

Processing tasmota32s3 (board: esp32s3-qio_qspi; framework: arduino; platform: https://github.com/tasmota/platform-espressif32/releases/download/2024.04.11/platform-espressif32.zip)
--------------------------------------------------------------------------------
Platform Manager: Installing https://github.com/tasmota/platform-espressif32/releases/download/2024.04.11/platform-espressif32.zip
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Platform Manager: espressif32@2024.4.11 has been installed!
Platform Manager: Removing espressif32 @ 2024.4.11
Platform Manager: espressif32@2024.4.11 has been removed!
IncompatiblePlatform: Development platform 'espressif32' is not compatible with PlatformIO Core v6.1.13 and depends on PlatformIO Core >=6.1.14.

Finished. Exit code: 1.

Can you help me?
Thanks, mtibi75

**Comment by benzino77** [comment]
You need to pull new docker image:
```sh
docker pull benzino77/tasmocompiler:development
```
I just pushed new image with newer `platformio` version bundled inside.

**Comment by mtibi75** [comment]
Thanks, this helped. I thought it was the latest version because watchtower is enabled, but version number is static: TasmoCompiler v11.0.0-dev. This confused me a bit..:-)
