### ISSUE TITLE
BME680 Sensor

### ISSUE THREAD

**Issue by bobybobybob** [benzino77/tasmocompiler#402]
I don't know if this is a problem of the compiler or of Tasmota itself. 

ESP32 Generic, leave everything as in the default settings. In the details 

#define USE_I2C  
#define USE_ENS16x 
#define USE_SCD40
#define USE_BH1750
#define USE_BME68X 
#define USE_SEN5X
#define USE_EXPRESSION 
#define SUPPORT_IF_STATEMENT

The BME680 sensor is not displayed in Tasmota. 

It only appears when I also add #define USE_BMP.

**Comment by benzino77** [comment]
Hi,

BME68X is not included in any feature group I suppose. Have a look [at features description](https://github.com/benzino77/tasmocompiler/blob/master/FEATURES_DESC.md)

**Comment by benzino77** [comment]
Try the `development` version of TasmoCompiler. It should now include `BME68x` in Temp-Hum-Pres feature group.

**Comment by bobybobybob** [comment]
Sorry, I have to run everything through a translator and write about it too. 
The Tasmota people write https://tasmota.github.io/docs/BME680/  

: When compiling your build add the following to user_config_override.h:

#ifndef USE_BME68X
#define USE_BME68X // Enable support for BME680/BME688 sensor using Bosch BME68x library (+6k9 code)
#endif

With other sensor things this has also worked so far with your very useful software. 

![bvc](https://github.com/benzino77/tasmocompiler/assets/23042717/c4610915-abbc-44dc-bf30-180a84adbc34)

**Comment by bobybobybob** [comment]
Thank you

**Comment by benzino77** [comment]
```C
#ifndef USE_BME68X
#define USE_BME68X // Enable support for BME680/BME688 sensor using Bosch BME68x library (+6k9 code)
#endif
```

TasmoCompiler should now include those lines ;)
