### ISSUE TITLE
Tasmocomp 12 - RF-Transceiver

### ISSUE THREAD

**Issue by bobybobybob** [benzino77/tasmocompiler#403]
TASMOCOMPILER V12.0.0

no Problem with ESP8266, ESP Generic  but

ESP32 C3  + RF-Transceiver + Bluetooth

/tmp/Tasmota/tasmota/tasmota_xdrv_driver/xdrv_17_rcswitch.ino:43:10: fatal error: RCSwitch.h: No such file or directory

******************************************************************
* Looking for RCSwitch.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:RCSwitch.h"
* Web  > https://registry.platformio.org/search?q=header:RCSwitch.h
*
******************************************************************

   43 | #include <RCSwitch.h>
      |          ^~~~~~~~~~~~
compilation terminated.

**Comment by benzino77** [comment]
Can you please try `development` version of TasmoCompiler?
Here is a description
https://github.com/benzino77/tasmocompiler?tab=readme-ov-file#development-version

Please give me a feedback if the fix solves the issue for you.

**Comment by bobybobybob** [comment]
Hello

yes development version work well with tasmo32 c3 + bluethooth + rf

Environment    Status    Duration
-------------  --------  ------------
tasmota32c3    SUCCESS   00:14:23.267
========================= 1 succeeded in 00:14:23.267 =========================
Finished. Exit code: 0.
