### ISSUE TITLE
[compilation error] xnrg_15_teleinfo.ino:38:10: fatal error: LibTeleinfo.h: No such file or directory

### ISSUE THREAD

**Issue by miky2k** [benzino77/tasmocompiler#405]
`********************************************************************************
If you like PlatformIO, please:
- star it on GitHub > https://github.com/platformio/platformio-core
- follow us on LinkedIn to stay up-to-date on the latest project news > https://www.linkedin.com/company/platformio/
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
********************************************************************************

Processing tasmota32c2 (board: esp32c2; framework: arduino; platform: https://github.com/tasmota/platform-espressif32/releases/download/2024.05.13/platform-espressif32.zip)
--------------------------------------------------------------------------------
Platform Manager: Installing https://github.com/tasmota/platform-espressif32/releases/download/2024.05.13/platform-espressif32.zip
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Platform Manager: espressif32@2024.5.13 has been installed!
Tool Manager: Installing https://github.com/tasmota/arduino-esp32/releases/download/3.0.0.240529/framework-arduinoespressif32.zip
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: framework-arduinoespressif32@3.0.0+sha.14a0ebd has been installed!
Tool Manager: Installing espressif/toolchain-riscv32-esp @ 12.2.0+20230208
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: toolchain-riscv32-esp@12.2.0+20230208 has been installed!
Tool Manager: Installing espressif/tool-xtensa-esp-elf-gdb @ ~12.1.0
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-xtensa-esp-elf-gdb@12.1.0+20221002 has been installed!
Tool Manager: Installing espressif/tool-riscv32-esp-elf-gdb @ ~12.1.0
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-riscv32-esp-elf-gdb@12.1.0+20221002 has been installed!
Tool Manager: Installing https://github.com/tasmota/esptool/releases/download/v4.7.3/esptool.zip
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-esptoolpy@4.7.3 has been installed!
Tool Manager: Installing tasmota/tool-mklittlefs @ ^3.2.0
Downloading 0% 10% 20% 30% 40% 50% 60% 70%
Unpacking 0% 10% 20%
Tool Manager: tool-mklittlefs@3.2.0 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40700.0
Downloading 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Tool Manager: tool-scons@4.40700.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
Nothing more to solidify
-DCONFIG_TASMOTA_FLASHMODE_QIO
*** use provided user_config_override.h as planned ***
*** use provided platformio_override.ini as planned ***
CONFIGURATION: https://docs.platformio.org/page/boards/espressif32/esp32c2.html
PLATFORM: Espressif 32 (2024.5.13) > Espressif Generic ESP32-C2 = 4M Flash, Tasmota 2880k Code/OTA, 320k FS
HARDWARE: ESP32C2 120MHz, 272KB RAM, 4MB Flash
DEBUG: Current (cmsis-dap) External (cmsis-dap, esp-bridge, esp-prog, iot-bus-jtag, jlink, minimodule, olimex-arm-usb-ocd, olimex-arm-usb-ocd-h, olimex-arm-usb-tiny-h, olimex-jtag-tiny, tumpa)
PACKAGES: 
 - framework-arduinoespressif32 @ 3.0.0+sha.14a0ebd 
 - tool-esptoolpy @ 4.7.3 
 - tool-mklittlefs @ 3.2.0 
 - tool-riscv32-esp-elf-gdb @ 12.1.0+20221002 
 - tool-xtensa-esp-elf-gdb @ 12.1.0+20221002 
 - toolchain-riscv32-esp @ 12.2.0+20230208
Converting tasmota.ino
Installing Python dependencies
Collecting wheel>=0.35.1
  Downloading https://files.pythonhosted.org/packages/c7/c3/55076fc728723ef927521abaa1955213d094933dc36d4a2008d5101e1af5/wheel-0.42.0-py3-none-any.whl (65kB)
Collecting zopfli>=0.2.2
  Downloading https://files.pythonhosted.org/packages/d1/ea/aebc67ec54aacfdb07c823066cc06cc49b89ed753b8ce6c117de03f30c42/zopfli-0.2.2-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (704kB)
Collecting tasmota-metrics>=0.4.3
  Downloading https://files.pythonhosted.org/packages/9f/e4/40e7292f92c9093b228fbd66d662092314cd8244a37557f57aff412c904e/tasmota_metrics-0.4.3-py3-none-any.whl
Collecting pyyaml (from tasmota-metrics>=0.4.3)
  Downloading https://files.pythonhosted.org/packages/cd/e5/af35f7ea75cf72f2cd079c95ee16797de7cd71f29ea7c68ae5ce7be1eda0/PyYAML-6.0.1.tar.gz (125kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
Building wheels for collected packages: pyyaml
  Running setup.py bdist_wheel for pyyaml: started
  Running setup.py bdist_wheel for pyyaml: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e6/c6/ef/4e8ee93f1b79fc90562f1600d47189799f8213023d9dadafa2
Successfully built pyyaml
Installing collected packages: wheel, zopfli, pyyaml, tasmota-metrics
  Found existing installation: wheel 0.32.3
    Not uninstalling wheel at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'wheel'. No files were found to uninstall.
Successfully installed pyyaml-6.0.1 tasmota-metrics-0.4.3 wheel-0.42.0 zopfli-0.2.2
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ strict
Found 84 compatible libraries
Scanning dependencies...
Dependency Graph
|-- Adafruit CCS811 Library @ 1.0.0
|-- Adafruit MAX31865 library @ 1.0.1
|-- Adafruit MCP9808 Library @ 1.1.2
|-- Adafruit PM25 AQI Sensor @ 1.0.6
|-- Adafruit SGP30 Sensor @ 1.2.0
|-- Adafruit SGP40 Sensor @ 1.1.0
|-- Adafruit VEML7700 Library @ 1.0.0
|-- Adafruit seesaw Library @ 1.3.1
|-- BME8563
|-- EEPROM 24C128_256_521
|-- FFat @ 2.0.0
|-- FS @ 2.0.0
|-- HttpClient light @ 1.0
|-- I2Cdevlib-Core
|-- MPU6050 I2C
|-- Mutichannel_Gas_Sensor @ 0.0.1
|-- esp-nimble-cpp @ 1.4.1
|-- SPL06-007 @ 0.1.0
|-- ESP Mail Client @ 3.4.9
|-- ScioSense ENS16x @ 8.0.0
|-- ScioSense ENS210 @ 3.0.0
|-- Sensirion I2C SGP41 @ 0.1.0
|-- UdpListener @ 1.0
|-- Unishox Compressor Decompressor highly customized and optimized for ESP8266 and Tasmota @ 1.0
|-- VL53L0X @ 1.0.2
|-- VL53L1X @ 1.0.1
|-- TLS mini client derived from Arduino @ 1.0
|-- Zip-readonly-FS @ 1.0
|-- Berry @ 7.0
|-- Berry Tasmota mapping @ 1.0
|-- Berry int64 implementation for 32 bits architecture @ 1.0
|-- Berry mapping to C @ 1.0
|-- Berry animation library for WS2812 leds @ 0.1
|-- Berry custom template @ 0.1
|-- Berry Matter protocol implementation @ 0.1
|-- headers
|-- ccronexpr
|-- WebServer @ 2.0.0
|-- ESP32-to-ESP8266-compat @ 0.0.2
|-- re1.5 @ 0.9
|-- Adafruit TSL2591
|-- Micro-RTSP @ 0.1.6
|-- DHT sensor library @ 1.4.3
|-- DNSServer @ 2.0.0
|-- Ethernet @ 2.0.0
|-- FrogmoreScd30
|-- FrogmoreScd40
|-- IRremoteESP8266 @ 2.8.6
|-- JSMN JSON parser customized and optimized for ESP8266 and Tasmota @ 1.0
|-- TasmotaLList @ 1.0
|-- LOLIN_HP303B @ 1.0.0
|-- LinkedList
|-- LittleFS @ 2.0.0
|-- MLX90640
|-- MPU_accel
|-- NeoPixelBus @ 2.6.7
|-- OneWire @ 2.3.2
|-- PubSubClient @ 2.8
|-- Ext-printf @ 1.0
|-- SD @ 2.0.0
|-- SD_MMC @ 2.0.0
|-- SPI @ 2.0.0
|-- Sensirion I2C SEN5X @ 0.2.0
|-- TasmotaModbus @ 3.6.0
|-- TasmotaSerial @ 3.6.0
|-- Ticker @ 2.0.0
|-- Joba_Tsl2561 @ 2.0.10
|-- WiFiHelper @ 1.0.0
|-- WiFi @ 2.0.0
|-- Wire @ 2.0.0
|-- base64 @ 1.1.1
|-- BME68x
|-- HPMA115S0 Arduino Library @ 1.0.0
|-- BearSSL @ 0.6
Building in release mode
Compiling .pio/build/tasmota32c2/src/tasmota.ino.cpp.o
Building .pio/build/tasmota32c2/bootloader.bin
Generating partitions .pio/build/tasmota32c2/partitions.bin
esptool.py v4.7.3
Creating esp32c2 image...
Merged 1 ELF section
Successfully created esp32c2 image.
Compiling .pio/build/tasmota32c2/lib767/Wire/Wire.cpp.o
Compiling .pio/build/tasmota32c2/lib1ec/Adafruit_CCS811-1.0.0.14/Adafruit_CCS811.cpp.o
Compiling .pio/build/tasmota32c2/liba96/SPI/SPI.cpp.o
Compiling .pio/build/tasmota32c2/libeea/Adafruit_MAX31865-1.1.0-custom/Adafruit_MAX31865.cpp.o
Compiling .pio/build/tasmota32c2/libb35/Adafruit_MCP9808_Tasmota/Adafruit_MCP9808.cpp.o
Compiling .pio/build/tasmota32c2/lib6c0/Adafruit_BusIO/Adafruit_BusIO_Register.cpp.o
Compiling .pio/build/tasmota32c2/lib6c0/Adafruit_BusIO/Adafruit_I2CDevice.cpp.o
Compiling .pio/build/tasmota32c2/lib6c0/Adafruit_BusIO/Adafruit_SPIDevice.cpp.o
In file included from tasmota/include/i18n.h:893,
                 from /tmp/Tasmota/tasmota/tasmota.ino:32:
tasmota/language/it_IT.h:797: warning: "D_GPIO_ASR650X_TX" redefined
  797 | #define D_GPIO_ASR650X_TX               "ASR650x - TX"
      | 
tasmota/language/it_IT.h:794: note: this is the location of the previous definition
  794 | #define D_GPIO_ASR650X_TX               "ASR650X - Tx"
      | 
tasmota/language/it_IT.h:798: warning: "D_GPIO_ASR650X_RX" redefined
  798 | #define D_GPIO_ASR650X_RX               "ASR650x - RX"
      | 
tasmota/language/it_IT.h:795: note: this is the location of the previous definition
  795 | #define D_GPIO_ASR650X_RX               "ASR650X - Rx"
      | 
Compiling .pio/build/tasmota32c2/libcbb/Adafruit_PM25AQI-1.0.6/Adafruit_PM25AQI.cpp.o
/tmp/Tasmota/tasmota/tasmota_xnrg_energy/xnrg_15_teleinfo.ino:38:10: fatal error: LibTeleinfo.h: No such file or directory

*********************************************************************
* Looking for LibTeleinfo.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:LibTeleinfo.h"
* Web  > https://registry.platformio.org/search?q=header:LibTeleinfo.h
*
*********************************************************************

   38 | #include "LibTeleinfo.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio/build/tasmota32c2/libeab/Adafruit_SGP30-1.2.0/Adafruit_SGP30.cpp.o
*** [.pio/build/tasmota32c2/src/tasmota.ino.cpp.o] Error 1
Compiling .pio/build/tasmota32c2/lib55b/Adafruit_SGP40-1.1.0/Adafruit_SGP40.cpp.o
========================= [FAILED] Took 116.98 seconds =========================

Environment    Status    Duration
-------------  --------  ------------
tasmota32c2    FAILED    00:01:56.980
==================== 1 failed, 0 succeeded in 00:01:56.980 ====================
Finished. Exit code: 1.
`
![immagine](https://github.com/benzino77/tasmocompiler/assets/6616232/b5eb1406-7bad-4b18-a7ed-a72be8dc5034)

**Comment by miky2k** [comment]
Fresh pulled docker image.

**Comment by benzino77** [comment]
Can you please try development version of TasmoCompiler?
Here is a description
https://github.com/benzino77/tasmocompiler?tab=readme-ov-file#development-version

Please give me a feedback if the fix solves the issue for you.

**Comment by miky2k** [comment]
Environment    Status    Duration
-------------  --------  ------------
tasmota32c2    SUCCESS   00:02:33.241
========================= 1 succeeded in 00:02:33.241 =========================
Finished. Exit code: 0.

**Comment by miky2k** [comment]
The flag that create troubles is energy sensors, but in developer seems ok.
