### ISSUE TITLE
ESP32c2 with bluetooth checked results in image without Bluetooth

### ISSUE THREAD

**Issue by Stephan3** [benzino77/tasmocompiler#407]
Hello.

I tried to use tasmocpmpiler to compile image with bluetooth support to use my MI Beacon devices.
So i checked Bluetooth box and defined in extra paramenter s

```
#define USE_MI_ESP32
#define USE_BLE_ESP32  
```

Image does compile without any errors. The resulting image flashes without issue but then there is no BLE option in configuration. What Magic did i miss? 

BR
Stephan

**Comment by Stephan3** [comment]
Thanks for pointing me there. Not a tasmotacompiler issue then -> Close

**Comment by benzino77** [comment]
...I think that using development versions of TasmoCompiler and Tasmota, BLE should work (based on changes introduced by @Jason2866) 
https://github.com/arendst/Tasmota/pull/21685

When the new stable versions of Tasmota will be released then it will also work in stable version of TasmoCompiler - at least I think it should ;)

**Comment by Stephan3** [comment]
Thanks again :) , i will try to find out how to do it with tasmotacompiler and gitpod.io

**Comment by Jason2866** [comment]
C2 and BLE with Tasmota will not work statisfying

**Comment by Stephan3** [comment]
> C2 and BLE with Tasmota will not work statisfying

Damn. I hoped that it will be a option to read my MI sensors arround as an Inwall solution. I do have those "shelly clones" from ebay, that are C2. Havent found other tasmota/BLE ready devices elsewere

**Comment by Jason2866** [comment]
Buy orig. Shellys ;-)

**Comment by Stephan3** [comment]
"the Internet" told me that they arent easy to flash anymore since last generation. I will look into that

**Comment by Jason2866** [comment]
You have to watch, do **NOT** buy Matter capable devices.
