### ISSUE TITLE
Compiling esp32 Webcam with Ultrasonic Sensor support results in "missing NewPing.h"

### ISSUE THREAD

**Issue by andreasbehnke** [benzino77/tasmocompiler#408]
Some dependency seems to be missing. 
I will try to compile locally without docker support. Maybe this gives me a hint which dependency is missing in tasmocompiler.

Compiling .pio/build/tasmota32-webcam/lib790/FS/vfs_api.cpp.o
/tmp/Tasmota/tasmota/tasmota_xsns_sensor/xsns_22_sr04.ino:41:10: fatal error: NewPing.h: No such file or directory

*****************************************************************
* Looking for NewPing.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:NewPing.h"
* Web  > https://registry.platformio.org/search?q=header:NewPing.h
*
*****************************************************************

   41 | #include <NewPing.h>
      |          ^~~~~~~~~~~
compilation terminated.
*** [.pio/build/tasmota32-webcam/src/tasmota.ino.cpp.o] Error 1
Compiling .pio/build/tasmota32-webcam/lib0a6/FFat/FFat.cpp.o
========================= [FAILED] Took 41.93 seconds =========================

Environment       Status    Duration
----------------  --------  ------------
tasmota32-webcam  FAILED    00:00:41.928

**Comment by benzino77** [comment]
Hi Andreas,

Have a look here:
https://github.com/benzino77/tasmocompiler/issues/366 and follow the mentioned links.  

esp32-cam board is somehow "special" and it does support all features regular esp32 boards do.
