### ISSUE TITLE
Warning messages regarding invalid field

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#41]
@benzino77 

gitpod /workspace/tasmocompiler $  HISTFILE=/workspace/.gitpod/cmd-0 history -r; {
> yarn install
> } && {
> yarn build && pip3 install platformio && node server/server.js
> }
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
**_warning file-loader@2.0.0: Invalid bin field for "file-loader".
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader"._**
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 47.66s.
yarn run v1.22.4
$ react-scripts build
Creating an optimized production build...
**_Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite_** browserslist`

Please check the log of a session in Google Chrome in a Windows 10 Profesisonal 64bit

Is it normal the warning reported in bold italic? Atre not important?

is it normal the message caniuse-lite is outdated?

I believe that the message regarding linux is why are running on Windows platform.

Thanks.

**Comment by benzino77** [comment]
I don't think that those warnings are important. But... some of them are probably caused by the newer version of nodejs (I'm using 10.x version to develop Tasmocompiler - this version is used inside docker images). I will try to change image used by gitpod.

**Comment by benzino77** [comment]
OK, so now gitpod environment is based on the same base image as one used with my own Tasmocompiler docker images. There is no such warnings as I can see. You can use gitpod procedure as usual, but now you will see some additional messages preparing the environment.

**Comment by bovirus** [comment]
UI etsted iot now.

The waring message are now info emssage

info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.

There is a new message that say that "yarn is not updated".

[4/4] Building fresh packages...
warning Your current version of Yarn is out of date. The latest version is "1.22.4", while you're on "1.13.0".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash

Have I delete some fodler on my pc?

And remain the messages that "caniuse-lite is outdated"

Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`

Thanks.

**Comment by benzino77** [comment]
yarn is just a package manager. You don't have to bother. 
["can I use"](https://www.npmjs.com/package/caniuse-lite) package is a dependency for one of packages used by Tasmocompiler.
Packages used by Tasmocompiler are listed in `package.json` file in dependencies section. There is no plan to update all packages in the project ;)

**Comment by bovirus** [comment]
@benzino77 

If I break the compilation, open command line and update manually the package I can do it.

Then could be means that the packages/dependecies that you have in your files could be not updated as expected.

When you can please consider to update the package/dependencies to avoid this warnings..

Thanks.

**Comment by benzino77** [comment]
Neither `browserslist` nor `caniuse-lite` are in the list of dependency for Tasmocompiler. Those packages are used _"underneath"_ other packages. So to dismiss this warning or other similar, I will have to probably upgrade the whole stack (every single package from the dependencies section in `package.json` file). 
I'm not planning to do this in the near future. 

Updating packages by hand, as you did, may lead to unexpected behavior or other undesired results. If you want to upgrade Tasmocompiler stack, than you have to start with packages listed here:
```javascript
 "dependencies": {
    "@material-ui/core": "^3.9.3",
    "@material-ui/icons": "^3.0.2",
    "body-parser": "^1.18.3",
    "debug": "^4.1.1",
    "express": "^4.16.4",
    "fs-extra": "^7.0.1",
    "ini": "^1.3.5",
    "lodash": "^4.17.11",
    "prop-types": "^15.7.2",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-scripts": "2.1.8",
    "shelljs": "^0.8.3",
    "simple-git": "^1.110.0",
    "socket.io": "^2.2.0",
    "socket.io-client": "^2.2.0",
    "typeface-roboto": "^0.0.54"
  }
```
Keep in mind what are the meanings of "~^><" etc. [docs](https://docs.npmjs.com/files/package.json#dependencies)
