### ISSUE TITLE
Buzzer disapeared in latest TasmoCompiler versions

### ISSUE THREAD

**Issue by aldweb** [benzino77/tasmocompiler#414]
**"Vanilla" tasmota32.bin from Tasmota website:**
 
![image](https://github.com/user-attachments/assets/8a73a84b-2109-4fb7-af79-38d5a84463d8)

Buzzer is correctly defined for GPIO32.

**Tasmota compiled with TasmoCompiler v12.2.0, using default options for ESP32:**
Refresh source / Next
Next
Esp32 Generic / Next
Next
V14.2.0 / English / Compile
 
![image](https://github.com/user-attachments/assets/c1f6ce68-0534-4725-861f-7ae4ecef9ce1)

Buzzer disapeared from GPIO32, and it is no more available in the list of selectable devices.

This bug seems to have appeared with v14.x Tasmota versions.
My last v13.4.0 compiled version with TasmoCompiler did not have the issue.

**Comment by benzino77** [comment]
Hi! Thanks for using TasmoCompiler.

It has changed on `v12.0.0`: https://github.com/benzino77/tasmocompiler/compare/v11.4.0...v12.0.0. 
Since `v12.0.0`, the buzzer functionality is included when LVGL is selected.
You can also add `#define USE_BUZZER` in "Custom parameters" step instead of adding LVGL feature.

**Comment by aldweb** [comment]
Hello,
I just realized that I basically copied and pasted my issue, forgetting to say hello and thank you for this great tool!
Thank you benzino77, this is very clear.
I missed this one, it was tricky! I would have never thought of the buzzer being migrated to LVGL.

**Comment by benzino77** [comment]
;) No problem at all. I'm glad you find TasmoCompiler as useful tool.
