### ISSUE TITLE
Modules/ features to enable in alphabetical order

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#42]
Hello.

i propose you to show the list of modules/features in alphabetical order.

I think that in this way it's easier tio identify the modules.

Is there a list of possible features that I can enable (and its meaning) for typical product like Sonofff R1/R2/R3 R1RF/R2RF/R3RF etc.
  
I  can define its as a compatibility list feature/product.

**Comment by benzino77** [comment]
I do believe that if you change order of features in the [AvailableFeatures.js](src/components/AppStepper/FeaturesStep/AvailableFeatures.js) file you will get the order you need.

**Comment by bovirus** [comment]
@benzino77 

Yes. Is this file.

Could you please re-arrange this file to have an on alphabetical order for the modules to enable?

Thanks.

**Comment by benzino77** [comment]
You can do this yourself and make Pull Request. All kind of contribution is welcome!

**Comment by bovirus** [comment]
@benzino77 

Done.
Made a re-order and I proposed some changes about description.

https://github.com/benzino77/tasmocompiler/pull/46
