### ISSUE TITLE
Create a downloadable log text file with all options selecetd

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#43]
@benzino77 

Do you think that it's possible to create at the end of compilation a text file that the user can download, with all options/info selected during compilation in all steps?

In this way it's possible archive the text file with firmware.bin and I know all setups about this file firmware.bin.

I think about less technical file that you already provdied.

Is just a copy of options selected in the stesps.

Thanks.

**Comment by benzino77** [comment]
It is already available to download. At the end of compilation you have three files to download:
- `firmware.bin` which is the firmware itself
- `platformio.ini` which is the platformio ini file used to compile your binary
- `user_config_override.h` which is the file containing all features (including WIFi, MQTT, IP settings) you selected for your custom firmware

**Comment by bovirus** [comment]
@benzino77 

I knwow that are already available these file.
That are techincal files.
I think about a moee simple text fil that contains only options selected during compilation.

I believe that could be useful as explained in separate issue to have a unique archive to download that contains all files (firmware + info files) instead three sperate download.
Because many tiems think to download firmware.bin and not info file.

**Comment by benzino77** [comment]
`user_config_override.h` contains only options selected/deselected during configuration. Nothing else. 
What kind of information do you think about? Could you provide a sample what is on your mind?

I think that it is related to #38
