### ISSUE TITLE
WiFi settings - How it works

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#44]
@benzino77 

I have a doubt about WiFi settings.
I looked for the doc but seems that I didn't find an answer.

If during compilation I select the option and setup Wifi SSID/password this info is included in firmware.bin and is operative after flash the firmware.bin file?

If I dodn't setup WiFi SSID/password after flash the firmware I can connect to device as usal (switch on, search for tasmota-xxxxx netwrok)?

Thanks.

**Comment by benzino77** [comment]
Yes, this setting is included in the resulting `firmware.bin` file, so you don't have to configure your device via AP provided by the device. It will try to connect to your WiFi home network just after flushing (restart the device after flushing by unplug and plugin power supply). 

If you do not provide WiFi credentials you will have to configure device via tasmota-xxx network.

**Comment by bovirus** [comment]
Thanks.
