### ISSUE TITLE
Create at the end an archive with firmware.bin / platform.io / user_config_override.h

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#45]
Hello.

I think taht useful efature is to craete at teh end not separate file with standard name but an archive like 

tasmocompiler_YYYYMMDD_hhmm.zip 

that contains

firmware.bin
platform.io
user_config_override.h

In this way it's easier to collect a library of firmware with different build.

Also you can include in the name of zip file the info about dev/stable and version and language

Example

tasmocompiler_dev_2.6.1_YYYYMMDD_hhmm_English.zip
tasmocompiler_stable_8.2.01_YYYYMMDD_hhmm_English.zip

Thanks.

**Comment by benzino77** [comment]
Let me leave this issue open and think about it.

**Comment by bovirus** [comment]
Thanks to consider this proposal.
