### ISSUE TITLE
FAQ - Add info about how to use personal repository with a single line command

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#47]
@benzino77 

As I requested here 

https://github.com/benzino77/tasmocompiler/issues/39

how to sed a personal repository for source code you mentioned thr info about Avantage Usage

https://github.com/benzino77/tasmocompiler/blob/master/ADVANCED.md

Could you please fix/update the info changing the reference about 

/tmp/Sonoff-Tasmota  

to 

/tmp/Tasmota 

and could you use instead series of commands

type: cd /tmp
type: rm -rf Tasmota
type: git clone https://github.com/stefanbode/Sonoff-Tasmota.git
type: cd Tasmota
type: git checkout -b development
type: cd /workspace/tasmocompiler
type: node server/server.js

a unique command joining the commands with &&

type: cd /tmp && rm -rf Tasmota && git clone https://github.com/stefanbode/Sonoff-Tasmota.git && cd Tasmota && git checkout -b development && cd /workspace/tasmocompiler && node server/server.js

in this way could be easy to copy/paste the long command to do all operations in one step.

**Comment by benzino77** [comment]
This is done on purpose. It shows what steps need to be performed. "Oneliner" is not clear to someone who reads this information.

**Comment by bovirus** [comment]
You could add both options and explain use of &&.

Line by line and one line commands.

If you repeat the same operations more than one time one line comamnd is sure better then single separate commands.

**Comment by benzino77** [comment]
Sure. That's good point! Please make a PR.

**Comment by benzino77** [comment]
Solved by PR #49
