### ISSUE TITLE
FAQ - Create tasmocompiler fork with custom settings

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#48]
@benzino77 

Could you help me?

Instead to stop every time and modify the gitpod of your repository I think to make a fork of your repository and make some changes to do these tasks

Use a personal repository
Use a default different language (Italian)

I did these tasks

- Made a fork of tasmocmpiler in https://github.com/bovirus/tasmocompiler.git

- Change in file 'Docker'
replace https://github.com/arendst/Tasmota.git with https://github.com/bovirus/tasmocompiler.git

- Change in file 'server/config/config.js'
replace https://github.com/arendst/Tasmota.git with https://github.com/bovirus/tasmocompiler.git

- Change in file 'src/component/AppStepper/VersioneStepper/Variables/Languages.js
Replace group "English" with "Italian" (Move Italian as first gorup and move down English)

- Launch gitpod

https://gitpod.io/#https://github.com/bovirus/tasmocompiler

Seelct Refresh source/No Wii settings/Alexa and Google module/Compile but I got an error.

Switching to branch development failed (on webUi compiler inetrace)

and

fatal: Cannot update paths and switch to branch 'development' at the same time.
Did you intend to checkout 'development' which can not be resolved as commit?

in gitpod command interface.

What's wrong?

**Comment by benzino77** [comment]
Yo don't have to make changes in `Dockerfile` and `'server/config/config.js`. It will use your version of Tasmocompiler but still use official version of Tasmota.

**Comment by bovirus** [comment]
@benzino77 

The scope is using my tasmota fork repo (to etst changes on tasmota) and avoid to stop and make changes on the fly with long command every time.

making a fork of tasnmocopiler repo and make changes reported

- Change ref from officvialo tasnmota repo to my my fofrk of tasmota dev repo
- Change language with Italian as first

I run gitpod from the fork of tasmocompielr repo with changes but I got the error reported.

is there something wrong?
Why this error?

**Comment by benzino77** [comment]
So you have to point to your Tasmocompiler fork from gitpod perspective: https://gitpod.io/#https://github.com/bovirus/tasmocompiler

On your fork of Tasmocompiler change the `server/config/config.js` to point to your fork of Tasmota: https://github.com/bovirus/Tasmota

**Comment by bovirus** [comment]
@benzino77 

Already done.
Also I changed the default language from English to italian.

When i ran https://gitpod.io/#https://github.com/bovirus/tasmocompiler and open browser and select all options (refersh source/no Wifi settings/select Alexa & google module/no custom parameters an compile I got teh error repoerted.

Try it.

**Comment by benzino77** [comment]
It will not work that way. Please read carefully the post above. Before you run gitpod with your version of tasmocompiler you have to change this [line](https://github.com/bovirus/tasmocompiler/blob/7e57736f56bab0259cd5650c7aa20bd0a7686530/server/config/config.js#L5) in file `server/config/config.js `
from:
`const githubRepo = 'https://github.com/bovirus/tasmocompiler.git;`
to
`const githubRepo = 'https://github.com/bovirus/Tasmota;`

**Comment by bovirus** [comment]
@benzino77 

It works. Great.

Thanks.
