### ISSUE TITLE
Flashsize wrong, should be MByte not Mbit

### ISSUE THREAD

**Issue by gknauf** [benzino77/tasmocompiler#5]
1st thanks for this very great tool!
I think the flashsize selector text is wrong, it should be MByte not Mbit.
It would also be great to have a setting for 512-kByte devices, f.e. older ESP-01 or the [H801](https://github.com/arendst/Sonoff-Tasmota/wiki/H801)

**Comment by Jason2866** [comment]
Building a 512k model isnt a good idea. You loose compatibility with standard 1M build.
Using a 1M build version on 512k device is NO problem. Just the firmware has to fit in flash.
OTA doesnt work for this device in no way you do

**Comment by gknauf** [comment]
> Building a 512k model isnt a good idea. You loose compatibility with standard 1M build.
what compatibility do you mean?
> Using a 1M build version on 512k device is NO problem. Just the firmware has to fit in flash.
not true - then sonoff-basic.bin and certainly sonoff-minimal.bin should run, but it seems that the device can not store its config; from what I've read in Tasmota issue [#2982](https://github.com/arendst/Sonoff-Tasmota/issues/2982) a different linker script is needed.
> OTA doesnt work for this device in no way you do
yes, but once you have flashed a working version it is not required to follow up with every latest Tasmota release.

**Comment by benzino77** [comment]
1. Well :) you are right on 1Mbit device even sonoff-minimal.bin won't fit ... its only 128KB in that way. Definitely there should be MB not Mb. Thanks for pointing it out!
2. You can upload 1MB memory layout bin file to old 512KB devices (as Jason said) - there should not be a problem.

I have checked that every core version got its 512K (0KB SPIFFS) memory layout linker settings:
```
cat ./packages/framework-arduinoespressif8266@1.20300.1/tools/sdk/ld/eagle.flash.512k0.ld                        
/* Flash Split for 512K chips, no SPIFFS */
/* sketch 487KB */
/* eeprom 20KB */

MEMORY
{
  dport0_0_seg :                        org = 0x3FF00000, len = 0x10
  dram0_0_seg :                         org = 0x3FFE8000, len = 0x14000
  iram1_0_seg :                         org = 0x40100000, len = 0x8000
  irom0_0_seg :                         org = 0x40201010, len = 0x79ff0
}

PROVIDE ( _SPIFFS_start = 0x4027B000 );
PROVIDE ( _SPIFFS_end = 0x4027B000 );
PROVIDE ( _SPIFFS_page = 0 );
PROVIDE ( _SPIFFS_block = 0 );

INCLUDE "../ld/eagle.app.v6.common.ld"
``` 

I do not have any 512K device but I will think about it ;)

**Comment by Jason2866** [comment]
@benzino77  my 2 cents.  Adding unecessary 512k option will result in OTA errors for 1M devices if user selected 512k by mistake when building firmware...

**Comment by benzino77** [comment]
You are right. I want to keep it simple and not overload it with too many choices which may lead to mistakes.

**Comment by benzino77** [comment]
Guenter it is fixed. Thanks again for pointing it out!
