### ISSUE TITLE
Multilanguage GUI in italian seems didn't work

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#52]
I made a fork of latest build on github

https://github.com/bovirus/tasmocompiler

I added it.json in language folder then I run gitpod from the fork

https://gitpod.io/#https://github.com/bovirus/tasmocompiler

After the compilation started the web page but report on top right EN.

And the browser is in italian

Tested with Chrome & Firefox

Firefox screenshot

![Firefox](https://user-images.githubusercontent.com/1262554/81284435-63911700-905e-11ea-95c6-431c4329450c.png)

**Comment by benzino77** [comment]
Please read this notes: [translation](https://github.com/benzino77/tasmocompiler/blob/master/TRANSLATION.md). You omit a file in your pull request.
