### ISSUE TITLE
Improvement - Features/languages in alphabetical order for not English UI

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#55]
@benzino77 
@rapejim 

Thanks for the MUI.

Now when you use different language then English, the list about features and languages is not in alphabetical order.

Could be make some changes on source code to have list about features and languages always in alphabetical order also with different language for MUI?

**Comment by rapejim** [comment]
@benzino77 
This is not easy, because the list is saved in English alphabetical order and is translated with the files of each language on the fly just when the browser has to show it, in memory it is still the list in English alphabetical order regardless of the interface language.

**Comment by rapejim** [comment]
@bovirus 
This is not easy, because the list is saved in English alphabetical order and is translated with the files of each language on the fly just when the browser has to show it, in memory it is still the list in English alphabetical order regardless of the interface language.

**Comment by bovirus** [comment]
@rapejim 

Of course it's an idea for future improvements.
If you get an idea how can do it please try.

**Comment by benzino77** [comment]
Closing as it was answered.

**Comment by bovirus** [comment]
@benzino77 

Why did close it?
Could leave it open as idea for future improvements.

If you close it you dind't see in a "wish" list.

**Comment by benzino77** [comment]
Sure.

**Comment by benzino77** [comment]
Closing this feature request because it is addressed by @drhideg in #97
