### ISSUE TITLE
Request - Use of CR/LF in UI language strings

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#56]
@benzino77 
@rapejim 

In long language (multi-period) string in UI is it possible to add a CR/LF?
How can do it?

Ex,. in this string

"stepCustomParamsDesc": "Qui sotto puoi inserire i parametri personalizzati che verranno inclusi alla fine del file. Se non li conosci o non devi inserirli seleziona 'Avanti'.",

Thanks.

**Comment by benzino77** [comment]
It won't be possible with plain JSON files. To do such things, translation files have to be moved to javascript objects.

Please use Issues to report problems related to the project. General question please direct to other places.
