### ISSUE TITLE
Bug fix - Using IT GUI didn't compile

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#57]
@benzino77 

This morning using latest build with fixes for IT UI, I ran Gitpod, and select basic option (no additional features, no custom parameters, Italian language).

I got an error and I couldn't compile the firmware.

Please check the log attached

[tasmocompiler-error.txt](https://github.com/benzino77/tasmocompiler/files/4597360/tasmocompiler-error.txt)

**Comment by benzino77** [comment]
That's because Theo rename files:
arendst/Tasmota@50614a18b5c45a79c3d449df24c2d5e4c7f9fb16

There is a fix needed on Tasmocompiler side to handle those changes.

**Comment by benzino77** [comment]
TasmoCompiler will work with any available to choose version of Tasmota except the development.

**Comment by bovirus** [comment]
@benzino77 

Then we can compile firmware currently only select as Tasmota version stable vesrion like 8.2.0 but not "development".

Will be there a way to fix it in the future in tasmocompiler and enable also to compile the firmware using tasmota "developmentt" branch?

**Comment by benzino77** [comment]
Yes, you can compile all versions except `development`.

**Comment by bovirus** [comment]
@benzino77 

I hope that you can add in tasmostacompielr the option to use Tasmota development branch because otherwise all new features in tasmota development branch will not availabel until Tasmota author apply the changes to the master branch.

**Comment by benzino77** [comment]
It should be addressed by benzino77/tasmocompiler@13d0713f85176e40d49df105d20dcc7d6642073d
