### ISSUE TITLE
Change default edgebranch from development to master

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#59]
Until will be possible to compile source of development branch I propasoe to change in

server/config/config.js 

the string

const edgeBranch = 'development';

to

const edgeBranch = 'master';

to avoid error using default development branch.

What do you think about it?

**Comment by ascillato** [comment]
The master branch gets old very fast. It is better to compile against development branch that has the latest fixes.

**Comment by bovirus** [comment]
@ascillato 

After latest change in tasmota repository currently we cannot compile development branch with tasocompiler.

**Comment by ascillato** [comment]
Latest changes were required for the CI (continuous Integration) Tests to allow also the tests also all firmwares types but for ESP32. As now this MCU is also supported, some adaptations were needed in most of the Tasmota's related tool.

**Comment by benzino77** [comment]
@ascillato Adrian good to have you here! Can you please have a look at proposition I've made:
[commit discussion](https://github.com/arendst/Tasmota/commit/50614a18b5c45a79c3d449df24c2d5e4c7f9fb16#commitcomment-39036540).
Having access to version at compile time can be useful in feature changes (in this issue too).

**Comment by benzino77** [comment]
@bovirus please do not open new issues regarding the same problem.

**Comment by benzino77** [comment]
> Until will be possible to compile source of development branch I propasoe to change in
> server/config/config.js
> the string
> const edgeBranch = 'development';
> to
> const edgeBranch = 'master';
> to avoid error using default development branch.
> What do you think about it?

Create a fork, make changes, use as you wish! That's the power of Open Source.

**Comment by bovirus** [comment]
@benzino77 

The problem is that it didn't work as expected.

Please check my post.

**Comment by ascillato** [comment]
Just for your information, the actual development branch is soon going to became the release 8.3, so everything in the development branch will be on the master branch.

**Comment by ascillato** [comment]
> Can you please have a look at proposition I've made: commit discussion.

Hi, I saw that, I'm ok to that but those types of modifications are up to Theo. Let's wait for his reply. You can ask to him also in the Discord Chat.

**Comment by bovirus** [comment]
@benzino77 

OK for near future 8.3.
But the problem will re-apper after release of 8.3.
Then could a good idea to fix on tasmocompiler.

Now I'm worjking with tasmota dvelopment branch on Gitpd.
And it works (but full support of all modules = big firmware).

**Comment by benzino77** [comment]
It should be addressed by benzino77/tasmocompiler@13d0713f85176e40d49df105d20dcc7d6642073d
