### ISSUE TITLE
UI _Add info about repository link used

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#60]
@benzino77 
@rapejim 

To test development in tasmota fimware 

- I make a fork of original tasmota repository
- I make a fork of tsmocompiler repository
- I change in my fork of tasmocompiler in server/config/config.js the value

const githubRepo = 'https://github.com/arendst/Tasmota.git';

in

const githubRepo = 'https://github.com/bovirus/Tasmota.git';

Could be possible to add in in multi-language gui before to select "download sorce"/"refresh source" a line like

Github site = xxxxxx

where xxx is the value gitHubrepo?

In this way I can check that I can really using my personal repo.

Thanks.

**Comment by bovirus** [comment]
i created a fork of tasmtota and I add in version 8,2,0 here

https://github.com/bovirus/Tasmota/tree/v8.2.0

the language files (italian and English).

Then I created a fork aof tsnmaocompielr here

https://github.com/bovirus/tasmocompiler

where i cahngae in config.json and Dockerfile reference from original tasmota repositopry to my fork.

Then I ran tasmocopiler via gitpod from my tasnmocompiler fork /selecting at the end v82.2.0) but i cannot see the changes in my lnguage files (seem remain the original).

What's the matter?

**Comment by benzino77** [comment]
That's the same as #48. I've explained you how you can do this. I'm not planing to implement it soon, because I don't want to overload the interface with too many options.

**Comment by bovirus** [comment]
@benzino77 

Please tajke care about the report on post #2 

I already did as in the past (create forks o repositories) but ... didn't work.
The language file are always the old version.

Could you explain what is wrong in my idea?

What's I did worng?
