### ISSUE TITLE
Google Home Assistant should be Home Assistant

### ISSUE THREAD

**Issue by s00500** [benzino77/tasmocompiler#61]
Hey, nice project, but 

`"stepFeaturesGoogleHADesc": "Google Home Assistant",`

seems very much incorrect to me =P This should be only **HomeAssistant** =D Gave me some confusion today... Has nothing to do with google home ;-)

And also check out HomeAssistant while you are at it https://www.home-assistant.io/ =D

Greetings =D

**Comment by benzino77** [comment]
You are right :) I will fix it with next release.

Thanks for reporting it!

**Comment by bovirus** [comment]
@benzino77 

This function is related to "Google Home Assistant" or generic "Home Assistant"?
If is it related to "Home Assitant" which product are compatible?

If this option is regarding "Google Home Assistant" compatibilityI disagree the name change.

"Home Assistant" is generic terms about domotics and is not refered to Google family products.

I believe that this options is related to the compatibility with "Google Home Assistant" product family.

The product family produced is named "Home Asistant" and the full name is "Google Home Assistant" as the product create by Amazon is called "Alexa" and full name is "Amazon Alexa".

**Comment by s00500** [comment]
@bovirus pleas check tasmota's documentation https://tasmota.github.io/docs/
