### ISSUE TITLE
Warning during gitpod compilation

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#64]
@benzino77 

During gitpod compilaton I got this warnings

**warning file-loader@2.0.0: Invalid bin field for "file-loader".
warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
warning url-loader@1.1.2: Invalid bin field for "url-loader".**

is it OK?

**Comment by benzino77** [comment]
It is a yarn (package manager) warning. You don't have to worry about it.
You can read more about tose kind of warnings [here](https://github.com/yarnpkg/yarn/issues/7803).

You can check each package `package.json` file to find out that the bin is set to empty string.
