### ISSUE TITLE
Improvement - Select in GUI a hardware model from a template list to select features 

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#65]
@benzino77 
@rapejim 

I propose you some ideas about a step up could be improve the program.
We can create a list of template, ex

Sonoff basic (r1/R2/r3)
Sonoff basic RF (R1/R2/R3)
Sonoff Mini
etc

where can define for each template which tasmota firmare feature is possible to enable.

when the user run compilation before to select features could decide if select a product template from a list or select manually which features enable in the firmware.

If the user select a model template (ex. Sonoff basic without RF), the program select automatically all possible featuers (based on template file) available for Sonoff Basic (ex not include RF, Air sensor etc).
 
In this way for many user can be easier to compile a firmware with all specific features for teh specifc hardware and nothing else.

What do you think about it?

**Comment by benzino77** [comment]
First, you can connect display to Sonoff Basic or you can connect Air sensor to Sonoff TH. If there are pins available you can select _Generic_ module and configure Sonoff or any other board as you like.

Second if you want to compile the firmware with model set to specific board, you can do this in step four: _Custom parameters_ where you can enter `#define` which will fit your needs:
```C
#define MODULE SONOFF_RF
```
or 
```C
#define MODULE SHELLY2
```
or ... put any other module which can be find [here](https://github.com/arendst/Tasmota/blob/650aca898d352807c5372aea36f470ec1c35db01/tasmota/tasmota_template.h#L760)

Third, not all devices are listed as modules. Huge number of them are available as [templates](https://templates.blakadder.com/index.html). Template cannot be set at compile time. Please have a look at Tasmota [readme](https://github.com/arendst/Tasmota#note).
