### ISSUE TITLE
does not come to end on Gitpod

### ISSUE THREAD

**Issue by 5chufti** [benzino77/tasmocompiler#67]
Hi, wanted to (re)compile shutterversion what worked ok in march, now after this message

> Compiling .pioenvs/custom/FrameworkArduino/umm_malloc/umm_poison.c.o
> Archiving .pioenvs/custom/libFrameworkArduino.a
> Indexing .pioenvs/custom/libFrameworkArduino.a
> Linking .pioenvs/custom/firmware.elf
> Welcome stranger!

runs for ever ...

**Comment by benzino77** [comment]
It means that there was a problem with WebSocket connection. You can have only one tab/window open with TasmoCompiler. 
In other cases just refresh the page.

**Comment by 5chufti** [comment]
Hi,
thanks for the reply. On several tries I did make sure I stopped the workspace, logged in to gitpod on a different machine, started the workspace, went through the config, hit "compile" and ... still the same. no more action after "Welcome stranger!" And I am sure there was no other tab/window with the TasmoCompiler. Refreshing the page just brought me back to the first config screen.
Did the same today, several times, different machines. Now, suddenly on the x-th try it finally brought

> Retrieving maximum program size .pioenvs/custom/firmware.elf
> Checking size .pioenvs/custom/firmware.elf
> Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
> RAM:   [======    ]  56.3% (used 46128 bytes from 81920 bytes)
> Flash: [=====     ]  53.2% (used 544804 bytes from 1023984 bytes)
> Building .pioenvs/custom/firmware.bin
> Creating BIN file ".pioenvs/custom/firmware.bin" using ".pioenvs/custom/firmware.elf"
> ========================= [SUCCESS] Took 50.95 seconds =========================
> Finished. Exit code: 0.
and showed the download buttons.
but at the end again
> Welcome stranger!
if this "welcome stranger" is wanted, why did the compile skip the elf/bin conversion earlier.
if it is not intended to bring "Welcome stranger, where is this coming from?

**Comment by benzino77** [comment]
Sorry, I cannot reproduce your problem. I'm pretty sure that this is a network problem. WebSocket connection is interrupted.
Before click "compile" button You can hit "F12" key to open browser dev tools. Choose "console" and observe if there is some information.

**Comment by 5chufti** [comment]
I dont get anything in console at the time of "welcome stranger!" and the messages in network window are the same in both cases (not ending and showing download buttons). At the moment it is a 50:50 chance for me. Is there a way to retrieve the files (asuming the compile comes to a regular end)?

**Comment by benzino77** [comment]
This is really strange... I do believe that you should see some errors in the browser console tab. You can find the websocket connection (screen below) on the network tab and watch how messages are flowing from server side to your browser:
![image](https://user-images.githubusercontent.com/15658235/82599031-e1e7d000-9bab-11ea-9bb2-05f97fbc74ca.png)

Yes, you can download binary by hand.  It is located in `/tmp/Tasmota/.pioenvs/custom`. Just open new terminal, type `cp /tmp/Tasmota/.pioenvs/custom/firmware.bin .` and the firmware.bin file should be available to download from the gitpod IDE:
![image](https://user-images.githubusercontent.com/15658235/82598860-99301700-9bab-11ea-8eac-1b19e8c44e34.png)

**Comment by benzino77** [comment]
Hi @5chufti 
I was able to reproduce your problem (well at least I think so). I do believe that the problem is with the amount of data send via WebSocket in very short time. This will occur when the compilation messages arrive very fast (fast compute unit on which the compilation is performed). I've prepared new branch `pa/patch-socketio` to address this problem (it groups messages to bunch of 20 lines and then send it to browser). Could you please check, if that solves your issue?

To test it on gitpod just go to https://gitpod.io/#https://github.com/benzino77/tasmocompiler/tree/pa/patch-socketio

**Comment by 5chufti** [comment]
Hi,
looks like you did put the finger on the right spot. I tried several runs with different configurations and all went well. 
Thanks for your great work!
