### ISSUE TITLE
Improvements - Setup Wifi - Password visible

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#68]
@benzino77 

Currently, If I want pre-set Wifi network SSID and password the password is not visible.

I believe that it's important to pre-set the right password and if teh password is not visible I'm not sure to digit it right.

Could be possible to show the password for Wifi in this step?

Thanks.

**Comment by benzino77** [comment]
It should rather be an option to click on show/hide password.

**Comment by bovirus** [comment]
@benzino77 

Show/hide password could be fine.
I beleive that show always password could be better to avoid errors.

**Comment by richard-scott** [comment]
The WiFi config page in Tasmota does exactly this. Maybe that could be used for inspiration 🤔

**Comment by bovirus** [comment]
@benzino77 

Thanks for the improvemnt.
