### ISSUE TITLE
Info about Wifi SSID/password and static ip settings

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#69]
@benzino77 

I'd like to have some info about preset Wifi SSID/password ans static IP. Example:

Today i created a new firmware (.bin file) with setting about Wifi SSID and password and static IP.

I flashed this firmware in the Sonoff and I'm using.

In the futuire If i want to build a new firmware versione have I to set every time these setiings (WiFi SSID user/password static IP) or can I leave these fields blank and new firmware didn't overwrite current settings (WiFi SSID user/password and staic IP).

Thanks.

**Comment by benzino77** [comment]
Every time you start session with TasmoCompiler or refresh the page you have to enter/check settings you want including your WiFi credentials.

Moving between steps (in the same session) will keep your choices and configuration you entered.
First example:
You are on the last step, and you are going to click on **_compile_** button, but you realize that you want to add some additional configuration in **_custom parameters_** step. You can do this, and information you've entered in the **_wifi configuration_** step will remain.

Second example:
You just compiled new firmware and want to compile another for other device with different settings. You can just go back to step **_select features_** check features you want for a new device and move to the **_select version and compile_** step. Information you've entered in **_wifi configuration_** will remain.

Third example:
Yesterday you compiled new firmware for your device. Today you want to compile another one for second device. You open new tab in your browser and go to gitpod/docker/local instance of TasmoCompiler. Your information you've entered yesterday **will not be available.**

**Comment by bovirus** [comment]
@benzino77 

Pelase don't close the issue until I confirm this.

My request type is different.
Is not regarding teh compilation with tasmocompiler but about the result of flash different firmware compiled in different time with different option.

First firmware
I created and flashed a firmware with custom tasmocompiler settings about WiFi SSID/password and static IP.

Second firmware
I created a firmware with no tasmocompiler settings about SSID name/password and static IP (empty)

Question.
In my Sonoff unit I have the first firmware.
Then the unit use specifed option (SSID name/password and statyic IP).

If I flash the second firmware will i lost in Sonoff the current settings ((SSID name/password and statyic IP)?

**Comment by ascillato** [comment]
> If I flash the second firmware will i lost in Sonoff the current settings ((SSID name/password and statyic IP)?

No, settings are saved in a different part of the flash memory. Updating the firmware don't affect settings. They are kept.

**Comment by bovirus** [comment]
@benzino77 

Thanks for the info.

My scope is to create a starting firmware for first Sonoff setup (setting in the device Wifi SSID WiFi password and static IP).

The next firmwares will be update and can be used to update the core without change the settings and without delete the previous settings,.

Thanks for the info.

**Comment by benzino77** [comment]
That's the question to Tasmota Forum/Discord - not TasmoCompiler.
If you upload new firmware over existing one you will not loose your configuration (Tasmota will keep your settings between updates/uploads new firmware, but there is always a chance that something will go wrong). If you reset your device (with command `reset` or with any other action) you will put your device in default state of **last** firmware, which in your case do not include wifi credentials and static IP information.
