### ISSUE TITLE
Multi arch with rpi support 

### ISSUE THREAD

**Issue by epandi** [benzino77/tasmocompiler#7]
Hi,

Can you make the docker repo multi arch with raspberry pi support? I've tester it working with using the following base image:

FROM arm32v7/node:10.15.3-stretch-slim

**Comment by benzino77** [comment]
Build a new, arm compatible, docker image is rather simple (I will probably create additional Dockerfile for arm architecture). But I have no idea how to build arm image on nonarm machine and how to make docker repo "multiarch" :)

Let me dive into.

**Comment by benzino77** [comment]
OK, so I think tasmocompiler docker images are now multiarch. If you are trying to run tasmocompiler on x86 or Raspberry PI or A53, H3, H5, Allwinner SBC boards just type:
`docker pull benzino77/tasmocompiler`
or just
`docker run --rm --name tasmocompiler -p 3000:3000 benzino77/tasmocompiler`

and docker should choose the proper image for your architecture.

Please test it and give me a feedback (I don't have RPI, Orange Pi, Banana Pi, etc. so I'm not able to test it on those architectures) if it works OK.

**Comment by epandi** [comment]
Excellent! It's working on raspberry pi!
