### ISSUE TITLE
Core 2.1.7 IR Full not compiling

### ISSUE THREAD

**Issue by AleksandarKotsev** [benzino77/tasmocompiler#72]
@benzino77
@rapejim

10x for updating to the new version, but it is not compiling with "IR full" option selected.
Can you please have a look?

**Comment by benzino77** [comment]
I do believe that this is a problem with core 2.7.1. If you try to compile with core 2.6.1 it compiles fine.
You have to contact Tasmota dev team.

**Comment by benzino77** [comment]
It can be a problem with Core 2.7.1 or IRSend library.

**Comment by AleksandarKotsev** [comment]
10x for the update i'll try contacting the Tasmota Team

**Comment by benzino77** [comment]
I think eventually that it is on my side. Will have a look at this closer.

**Comment by Jason2866** [comment]
This part is needed in PlatformIO.ini
```
[irremoteesp_full]
build_flags               = -DUSE_IR_REMOTE_FULL
                            -U_IR_ENABLE_DEFAULT_
                            -DDECODE_PRONTO=false -DSEND_PRONTO=false
```
for compiling IR Remote Full

**Comment by benzino77** [comment]
For full IR suppoort it hase to have no `IR_ENABLE_DEFAULT_` set. For basic IR support it needs `IR_ENABLE_DEFAULT_=false`.
I have to work on it.

**Comment by benzino77** [comment]
If you are using gitpod - you can test the new version now. 
If you are using Docker than you have to wait for build new images.
I haven't tested firmwares themselves but the sizes of firmwares without IR, basic IR support and full IR support differs:
```
used 617868 bytes from 1023984 bytes (full_ir)
used 509004 bytes from 1023984 bytes (basic_ir)
used 499192 bytes from 1023984 bytes (no_ir)
```

Let me know the results.

**Comment by AleksandarKotsev** [comment]
@benzino77
The solution compiles successfully I'll test it later to see if it also functions correctly.
10x again for your help.

**Comment by benzino77** [comment]
Does it solves your issue?

**Comment by benzino77** [comment]
Closing this issue because there is no feedback from @AleksandarKotsev .
Let me know if this should be reopen.
