### ISSUE TITLE
Info about pre-set WiFi SSID and password

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#73]
Hello.

Is there a file in your source where can I pre-set WiFi SSID name and password used during tasmota compilation?

Typically I make a fork of your tasmocompiler repository.
I do it because I modify the link for tasmota repository to my personal fork of tasmota source that contains changes about language UI (that are in test).

Anytime that I compile a new firmware I have to set manually WiFi SSID name paassword.

If there is a file in your source that contains this info I can setup up to get it without asking me.

Thanks.

**Comment by benzino77** [comment]
Copy and paste:
```C
#ifdef STA_SSID1
  #undef STA_SSID1
#endif
#define STA_SSID1       "yourssid"

#ifdef STA_PASS1
  #undef STA_PASS1
#endif
#define STA_PASS1       "yourpassword"

#ifdef MY_LANGUAGE
  #undef MY_LANGUAGE
#endif
#define MY_LANGUAGE     <your_language_code>
```
these settings in fourth step (Custom parameters).  Custom parameters are written at the end of `user_config_override.h` file so it will overwrite any other (previous) settings.

You should very carefully read [Compiling](https://tasmota.github.io/docs/Compile-your-build/) section of Tasmota documentation as it should better fits your needs.

**Comment by bovirus** [comment]
@benzino

Thanks for the sugegstion.

It require always a copy/paste for each compilation.

My scope is to change a file in the local repoistyory of your source that pre-setr always automatically SSID name/password and just confirm.

Can I change in some way the file

components/AppStepp/WiFiStep.js

**Comment by benzino77** [comment]
I'm wondering how many different features configurations do you have? It is really needed to compile new firmware for EVERY device you have?

**Comment by bovirus** [comment]
Ths settings (SSID name and passowrd ) as you can imagine is nceesary for ANY tasmota device that anyone can compile for spacifc configurationm.

**Comment by benzino77** [comment]
As you can imagine the same firmware can be applied to MANY devices. You can have one binary which will be uploaded to MANY devices. There is no need to compile the same firmware for EVERY new device.
How many different "specific" configurations do you have? How many different SSIDs in your house do you have? It's sounds very weird for me. Especially you have to click at least 6 times in TasmoCompiler (assuming you will not choose any additional features) to compile and download new binary, but on the other hand you are saying that hitting `CTRL+C` ant then `CTRL+V` is a problem for you. 

Please, could you describe your situation in more detailed way?

**Comment by benzino77** [comment]
Anyway, you can preset your SSID and WiFi password in this two lines of your TasmoCompiler fork:
[preset SSID](https://github.com/benzino77/tasmocompiler/blob/master/src/components/AppStepper/WifiStep.js#L23)
[preset password](https://github.com/benzino77/tasmocompiler/blob/master/src/components/AppStepper/WifiStep.js#L24)

**Comment by bovirus** [comment]
@benzino77 

Thanks.

It's the info that I need.

Then I can do like this in WiFiStep.js

      STA_SSID1: 'WiFINetwork',
      STA_PASS1: 'WifiPassword',

If I want to pre-set SSID = WiFINetwork with password = WifiPassword ?

Thanks.
