### ISSUE TITLE
512 KB & Ukraine Language Error

### ISSUE THREAD

**Issue by BosakS** [benzino77/tasmocompiler#74]
Great software. Although there are nuances. I compile for 512 kb, but there is no such choice.
When choosing the Ukrainian language, it gives a compilation error.

**Comment by benzino77** [comment]
Please read discussion on issue #5 and #17.
There was a typo for Ukrainian language. Thanks for pointing it out! It is fixed. I will push new docker images.

**Comment by benzino77** [comment]
Maybe you want to translate TasmoCompiler GUI to Ukrainian language? If so, there is description how to do this: [TRANSLATION](https://github.com/benzino77/tasmocompiler/blob/master/TRANSLATION.md)

**Comment by BosakS** [comment]
No.
[image: зображення.png]
[image: зображення.png]
And 512kb - Sonoff Mini - new device from Itead.



чт, 9 лип. 2020 о 13:54 benzino77 <notifications@github.com> пише:

**Comment by benzino77** [comment]
Sorry I don't see any image.

The "No" in the first sentence is the answer to the question whether you want to translate Tasmocompiler to Ukrainian language?

Sonoff Mini is supported by Tasmota. See the [docs](https://tasmota.github.io/docs/devices/Sonoff-Mini/).

**Comment by BosakS** [comment]
Processing custom (platform: espressif8266@2.3.0; framework: arduino;
board: esp01_1m)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION:
https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 2.3.0 > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES:
 - framework-arduinoespressif8266 2.20601.191124 (2.6.1)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.20800.0 (2.8.0)
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Converting tasmota.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 74 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <SSD3115> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <HPMA115S0 Arduino Library> 1.0.0
|-- <RA8876> 1.0.2
|   |-- <SPI> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|-- <FrogmoreScd30>
|   |-- <Wire> 1.0
|-- <Adafruit_SH1106-gemu-1.0>
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <Unishox Compressor Decompressor highly customized and optimized for
ESP8266 and Tasmota> 1.0
|-- <base64> 1.1.1
|-- <Adafruit ILI9341> 1.2.0
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|-- <OpenTherm Library> 0.9.0
|-- <cc1101>
|   |-- <SPI> 1.0
|-- <Wire> 1.0
|-- <C2Programmer> 1.0.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <Adafruit GFX Library> 1.5.6
|   |-- <SPI> 1.0
|-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <ILI9488> 1.0.2
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <SPI> 1.0
|-- <KeeloqLib> 1.1
|-- <ArduinoNTPd>
|   |-- <ESP8266WiFi> 1.0
|-- <I2Cdevlib-MPU6050>
|   |-- <I2Cdevlib-Core>
|   |   |-- <Wire> 1.0
|-- <PubSubClient> 2.7
|-- <LiquidCrystal_I2C>
|   |-- <Wire> 1.0
|-- <ESP KNX IP Library> 0.5.2
|   |-- <EEPROM> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WebServer> 1.0
|   |   |-- <ESP8266WiFi> 1.0
|-- <A4988_Stepper> 0.0.1
|-- <SPI> 1.0
|-- <Adafruit_TSL2591_Library>
|   |-- <Wire> 1.0
|-- <AT24C256>
|   |-- <Wire> 1.0
|-- <LinkedList>
|-- <ESP8266httpUpdate> 1.3
|   |-- <ESP8266HTTPClient> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <Adafruit SSD1306> 1.3.0
|   |-- <SPI> 1.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|   |-- <Waveshare esp 2.9 inch e-paper display driver> 1.0
|   |   |-- <Adafruit GFX Library> 1.5.6
|   |   |   |-- <SPI> 1.0
|   |   |-- <SPI> 1.0
|   |-- <Wire> 1.0
|-- <ESP8266WiFi> 1.0
|-- <SD(esp8266)> 2.0.0
|   |-- <SDFS> 0.1.0
|   |   |-- <SPI> 1.0
|   |   |-- <ESP8266SdFat> 1.1.0
|   |   |   |-- <SPI> 1.0
|-- <FT6236-gemu-1.0>
|   |-- <Wire> 1.0
|-- <VL53L0X> 1.0.2
|   |-- <Wire> 1.0
|-- <Adafruit SGP30 Sensor> 1.0.3
|   |-- <Wire> 1.0
|-- <Adafruit LED Backpack Library> 1.1.6
|   |-- <Wire> 1.0
|   |-- <Adafruit GFX Library> 1.5.6
|   |   |-- <SPI> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <Adafruit CCS811 Library> 1.0.0
|   |-- <Wire> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <TasmotaModbus> 1.2.0
|   |-- <TasmotaSerial> 3.0.0
|-- <Adafruit MAX31865 library> 1.0.1
|   |-- <SPI> 1.0
|-- <BME680_driver-bme680_v3.5.9>
|-- <Joba_Tsl2561> 2.0.10
|   |-- <Wire> 1.0
|-- <IRremoteESP8266> 2.7.6
|-- <RF24> 1.3.3
|   |-- <SPI> 1.0
|-- <I2Cdevlib-Core>
|   |-- <Wire> 1.0
|-- <Mutichannel_Gas_Sensor> 0.0.1
|   |-- <Wire> 1.0
|-- <NewPing> 1.9.1
|-- <ESP8266HTTPClient> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <rc-switch> 2.6.2
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson> 5.13.4
|-- <Ticker> 1.0
|-- <NeoPixelBus> 2.5.0
|   |-- <SPI> 1.0
|-- <TasmotaSerial> 3.0.0
|-- <BearSSL> 0.6
Building in release mode
*** use provided user_config_override.h as planned ***
Compiling .pioenvs/custom/src/Parsing.cpp.o
Compiling .pioenvs/custom/src/StackThunk_light.cpp.o
In file included from tasmota/my_user_config.h:738:0,
                 from tasmota/StackThunk_light.cpp:28:
tasmota/user_config_override.h:4:2: warning: #warning ****
user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pioenvs/custom/src/WiFiClientSecureLightBearSSL.cpp.o
In file included from tasmota/my_user_config.h:738:0,
                 from tasmota/WiFiClientSecureLightBearSSL.cpp:23:
tasmota/user_config_override.h:4:2: warning: #warning ****
user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
Compiling .pioenvs/custom/src/core_esp8266_waveform.cpp.o
Compiling .pioenvs/custom/src/core_esp8266_wiring_digital.cpp.o
Compiling .pioenvs/custom/src/core_esp8266_wiring_pwm.cpp.o
Compiling .pioenvs/custom/src/tasmota.ino.cpp.o
In file included from tasmota/my_user_config.h:738:0,
                 from /tmp/Tasmota/tasmota/tasmota.ino:38:
tasmota/user_config_override.h:4:2: warning: #warning ****
user_config_override.h: Using Settings from this File **** [-Wcpp]
 #warning **** user_config_override.h: Using Settings from this File ****
  ^
In file included from /tmp/Tasmota/tasmota/tasmota.ino:43:0:
tasmota/i18n.h:629:37: fatal error: language/uk_UK.h: No such file or
directory
   #include INCLUDE_FILE(MY_LANGUAGE)
                                     ^
compilation terminated.
*** [.pioenvs/custom/src/tasmota.ino.cpp.o] Error 1
========================= [FAILED] Took 88.96 seconds
=========================
Finished. Exit code: 1.
Welcome stranger!
Welcome stranger!
Welcome stranger!



чт, 9 лип. 2020 о 15:43 benzino77 <notifications@github.com> пише:

**Comment by benzino77** [comment]
If you are using docker you have to update image. Just pull new version.
If you are using gitpod then probably you have to start new workspace.
If you are starting TasmoCompiler from locally cloned repo, then you have to pull latest changes.

In other words you are using the old version of TasmoCompiler which does not include latest changes.
