### ISSUE TITLE
Improvement - Compiling for ESP32

### ISSUE THREAD

**Issue by tiagofreire-pt** [benzino77/tasmocompiler#79]
There is a alpha branch for ESP32 on Tasmota.

This is huge, providing much more powerful hardware to run it on.

Could you develop this awesome project for that, please?

Thanks!

**Comment by benzino77** [comment]
Well, definitely support for esp32 is a nice feature. It is in early alpha stage development so many, many things can change. I think that _Release Candidate_ stage is a good point to start thinking of implementing it in TasmoCompiler. 

I will leave this issue open. Maybe someone will pick it up to implement it earlier.

**Comment by Jason2866** [comment]
ESP32 releases are done. ESP32 builds are in (stable) Beta state. 
Beta because not all features are there and some features are not fully tested

**Comment by benzino77** [comment]
Thanks for keeping me informed!
I have to order esp32 board before implement esp32 support in Tasmocompiler.

**Comment by tiagofreire-pt** [comment]
@benzino77 , how could I test it through docker images?

`
docker pull benzino77/tasmocompiler/tree/pa/esp32
`

Doesn't work.

**Comment by benzino77** [comment]
There is no docker image for this branch. You can use gitpod or build image yourself (Dockerfile is in the repo)

**Comment by catalintabirca** [comment]
should it still work?  a get error: tasmota/tasmota_compat.h:23:28: fatal error: esp8266toEsp32.h: No such file or directory

**Comment by Jason2866** [comment]
@catalintabirca  the Tasmocompiler esp32 branch is outdated and doesnt work anymore.
Tasmota (setup) has a lot of changes since this time

**Comment by benzino77** [comment]
As @Jason2866 said this branch is outdated. To tell the truth I completely forgot about this branch and it is now so outdated that I'm not sure if I can do rebase on it.

**Comment by benzino77** [comment]
Closing as ESP32 support is included from version 4.0.0 of TasmoCompiler.
