### ISSUE TITLE
TasmoCompiler: Unable to get TAGS

### ISSUE THREAD

**Issue by gutier76** [benzino77/tasmocompiler#8]
- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Sonoff-Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in issues (https://github.com/arendst/Sonoff-Tasmota/issues)
- [x] Searched the problem in the wiki (https://github.com/arendst/Sonoff-Tasmota/wiki/Troubleshooting)
- [x] Searched the problem in the forum (https://groups.google.com/d/forum/sonoffusers)
- [x] Device used (i.e. Sonoff Basic) : planned NodeMCU ESP8266
- [x] Tasmota binary firmware version number used : 2.3.0/2.4.2/2.5.2 / ( self-compiled)
- [x] Development IDE - Compiler / Upload tools used : TasmoCompiler

Greetings,
I'm attempting to use a TasmoCompiler but without success.
At the final step I'm receiving a message "Unable to get TAGS"
I've used the "less easy way" to install TasmoCompiler on Win7 (without docker).

Where is the glitch?

best regards
Marcin

**Comment by benzino77** [comment]
Hi Marcin,

This is a problem with tasmocompiler, which is not fully "cross platform" (well, two platforms *NIX like , and Windows) as I realize just now.

Have a look at the config file where `WORKDIR` is [defined](https://github.com/benzino77/tasmocompiler/blob/master/server/config/config.js#L3). It assumes that if there is no `WORKDIR` environment variable defined, it is *NIX OS and the `WORKDIR` should be `/tmp` - path which is not available on Windows systems.

You can try to set this variable before start tasmocompiler:
`set WORKDIR=%TEMP%`
or
`set WORKDIR=%TMP%`
or you can set `WORKDIR` to any other path you like , and then run `node server/server.js`.

You should also set DEBUG variable to see debugging messages on the console:
`set DEBUG=server,git,compile`
 before start tasmocompiler. It could give you more information about what tasmocompiler is doing.

**Comment by gutier76** [comment]
Hi,  Thank You for the tips. I&#39;ve tried it, but results have unfortunately not imroved. Web-page wizard crashed on infinite loop, and on the console I&#39;ve retrieved a response:   C:\Users\cp24\Documents\Doku\E build  yarn run v1.16.0  $ react-scripts build  Creating an optimized production build...  Compiled successfully.   File sizes after gzip:     116.86 KB  build\static\js\2.caa16151.chu    5.2 KB     build\static\js\main.d4a02972.    764 B      build\static\js\runtime~main.c    580 B      build\static\css\2.bbb837e6.ch    276 B      build\static\css\main.cd5f18f5   The project was built assuming it is hosted at the server root.  You can control this with the homepage field in your package.json.  For example, add this to build it for GitHub Pages:     &#34;homepage&#34; : &#34; myname.github.io myname.github.io &#34;,   The build folder is ready to be deployed.  You may serve it with a static server:     yarn global add serve    serve -s build   Find out more about deployment here:      bit.ly bit.ly   Done in 11.50s.   C:\Users\cp24\Documents\Doku\E WORKDIR=%TMP%   C:\Users\cp24\Documents\Doku\E DEBUG=server,git,compile   C:\Users\cp24\Documents\Doku\E server/server.js  Server started on port 3000  Error: spawn git ENOENT      at Process.ChildProcess._handle.o (internal/child_process.js:240      at onErrorNT (internal/child_process.js:415      at process._tickCallback (internal/process/next_tick.js    git Unable to CLONE git repository +0ms    git Unable to get TAGS +8s    server {    server   &#34;showDownloadLinks&#34;: false,    server   &#34;STA_SSID1&#34;: &#34;xxxxxxxxxxx&#34;,    server   &#34;STA_PASS1&#34;: &#34;xxxxxxxxxxxxxxxxxxxxxxxxxxx&#34;,    server   &#34;WIFI_IP_ADDRESS&#34;: &#34;&#34;,    server   &#34;WIFI_SUBNETMASK&#34;: &#34;&#34;,    server   &#34;WIFI_GATEWAY&#34;: &#34;&#34;,    server   &#34;WIFI_DNS&#34;: &#34;&#34;,    server   &#34;staticIPEnabled&#34;: false,    server   &#34;USE_DOMOTICZ&#34;: true,    server   &#34;USE_HOME_ASSISTANT&#34;: true,    server   &#34;USE_KNX&#34;: true,    server   &#34;USE_DISCOVERY&#34;: true,    server   &#34;USE_TIMERS&#34;: true,    server   &#34;USE_RULES&#34;: true,    server   &#34;USE_ADC_VCC&#34;: true,    server   &#34;USE_I2C&#34;: true,    server   &#34;USE_SPI&#34;: true,    server   &#34;airsensors&#34;: true,    server   &#34;USE_MHZ19&#34;: true,    server   &#34;USE_SENSEAIR&#34;: true,    server   &#34;USE_PMS5003&#34;: true,    server   &#34;USE_NOVA_SDS&#34;: true,    server   &#34;energysensors&#34;: true,    server   &#34;USE_PZEM004T&#34;: true,    server   &#34;USE_PZEM_AC&#34;: true,    server   &#34;USE_PZEM_DC&#34;: true,    server   &#34;USE_MCP39F501&#34;: true,    server   &#34;USE_IR_REMOTE&#34;: true,    server   &#34;USE_WS2812&#34;: true,    server   &#34;USE_SR04&#34;: true,    server   &#34;USE_RC_SWITCH&#34;: true,    server   &#34;customParams&#34;: &#34;#ifndef USE_I2C #define USE_I2C\n #ifndef USE_BMP #d  efine USE_BMP\n #endif\n#endif\n&#34;,    server   &#34;tasmotaVersion&#34;: &#34;development&#34;,    server   &#34;coreVersion&#34;: {    server     &#34;platform&#34;: &#34;core_2_5_2&#34;,    server     &#34;mem_prefix&#34;: &#34;eagle.flash.&#34;    server   },    server   &#34;MY_LANGUAGE&#34;: &#34;en-GB&#34;,    server   &#34;boardVersion&#34;: {    server     &#34;mem&#34;: 4,    server     &#34;board&#34;: &#34;nodemcuv2&#34;    server   },    server   &#34;memoryBuildFlag&#34;: &#34;eagle.flash.4m1m.ld&#34;    server } +0ms    git Unable to get TAGS +2m    compile Error: Unable to get TAGS    compile     at getRepoTags (C:\Users\cp24\Documents\Doku\  \server\git\git.js:47:9) +0ms    It appears he can&#39;t clone repo from github, and I don&#39;t know why.   greetings   Marcin   Dnia 7 lipca 2019 10:13 benzino77 &lt;notifications@github.com&gt; napisał(a):  Hi Marcin,  This is a problem with tasmocompiler, which is not fully &#34;cross platform&#34; (well, two platforms *NIX like , and Windows) as I realize just now.  Have a look at the config file where  WORKDIR  is  github.com defined . It assumes that if there is no  WORKDIR  environment variable defined, it is *NIX OS and the  WORKDIR  should be  /tmp  - path which is not available on Windows systems.  You can try to set this variable before start tasmocompiler:    set WORKDIR=%TEMP%   or    set WORKDIR=%TMP%   or you can set  WORKDIR  to any other path you like , and then run  node server/server.js .  You should also set DEBUG variable to see debugging messages on the console:    set DEBUG=server,git,compile   before start tasmocompiler. It could give you more information about what tasmocompiler is doing.  —  You are receiving this because you authored the thread.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by gutier76** [comment]
I have had a broken installation instance of 'git' also.
Thank You for help
