### ISSUE TITLE
Only Tasmota core 2.7.4.1 is used and supported 

### ISSUE THREAD

**Issue by Jason2866** [benzino77/tasmocompiler#83]
all other cores are not supported and recommended anymore.
The next Tasmota version 8.5 (release tomorrow) will be build with this core. 

To build latest Tasmota version PlatformIO v.5.0 is needed.
To enable Tasmota core 2.7.4.1 this entry is needed:
```
; *** Esp8266 Tasmota modified Arduino core based on core 2.7.4
platform                  = espressif8266@2.6.2
platform_packages         = jason2866/framework-arduinoespressif8266
```

Thx for contributing a tool for Tasmota!

**Comment by benzino77** [comment]
Thanks for keeping me updated!

Tasmota version `v8.3.x` does not compile with core version `2.7.3` and `2.7.4`. It compiles well with core `2.7.1` and `2.6.1`.

**Comment by benzino77** [comment]
New docker images are pushed.
