### ISSUE TITLE
Latest Version not compiling

### ISSUE THREAD

**Issue by AleksandarKotsev** [benzino77/tasmocompiler#86]
Dear kind sir (@benzino77)
The latest version of tasmota is not compiling (8.5.0 core 2.7.4). Can you please fix it if possible?
Best regards.

**Comment by benzino77** [comment]
Works for me.

![image](https://user-images.githubusercontent.com/15658235/93466988-642f9900-f8ed-11ea-95b2-1e0f3c26c515.png)

**Comment by AleksandarKotsev** [comment]
Sorry for not providing you with the full information
Here is the error:
![image](https://user-images.githubusercontent.com/67271839/93472571-84675400-f8fd-11ea-9d51-f43b3d6830af.png)

Here is the feature selection:
![image](https://user-images.githubusercontent.com/67271839/93472615-95b06080-f8fd-11ea-83a8-ea0a158da297.png)

Hope this helps you enough.

**Comment by benzino77** [comment]
Have a look here:
https://github.com/esp8266/Arduino/issues/6275

You probably want to compile in to many things, or too "big" features.

**Comment by AleksandarKotsev** [comment]
Has something dramatically changed in the libraries used because I'm able to compile this set of features with the previous version without a problem.
![image](https://user-images.githubusercontent.com/67271839/93574634-50de0580-f9a1-11ea-809d-e325ef2a1018.png)
Have in mind that I also tried the NodeMcu setting which has 4 mb and the result is the same.
10x in advance

**Comment by benzino77** [comment]
I do believe that there some changes from core version to core version which can impact on available iram space for firmware features. It is also possible that there are changes in Tasmota features code which can consume more memory space. What you can do is:
- choose previous version (or just another) version of core
- choose another version on Tasmota itself
- divide functionality for more than one board (one board for IR another for RF)

First two are reachable with TasmoCompiler. The last one depends on you requirements. You can also try ESP32, which I believe has much more memory space than esp8266. There is experimental TasmoCompiler version (branch) which support compiling firmware for ESP32 - but you have to keep in mind that not all features are tested with ESP32. 

PS.
I'm not sure that changing board type from ESP-01 to NodeMCU will guarantee more iram space (@Jason2866 or @ascillato can probably tell more).

**Comment by Jason2866** [comment]
Every ESP82XX has the same iram. The difference in the modules is just flash space.
Tasmota precompiled builds uses ALWAYS 1M builds. 
Core 2.7.x has the most free iram of all cores. Anyway suport for cores before 2.7.x has been dropped. Probably trying to compile latest Tasmota on old Arduino cores will fail or is resulting in a unstable firmware. 
@benzino77  do you use our Tasmota modified core 2.7.4.1? It is available via Platformio registry with the entry `platform_packages  = jason2866/framework-arduinoespressif8266` right after `platform  = espressif8266@2.6.2` Not using our modified core will result in problems for dimmed light (PWM) and shutter use.

**Comment by benzino77** [comment]
@Jason2866 yes (at least I think so):
```
[core_2_7_4]
platform          = espressif8266@2.6.2
platform_packages = jason2866/framework-arduinoespressif8266
```

**Comment by Jason2866** [comment]
Just did a Tasmocompiler run. Yes you do. For me Tasmocompiler works. Firmware builds successfully. You should remove all other cores. There is all code removed from Tasmota for supporting cores before 2.7.x

**Comment by Jason2866** [comment]
@AleksandarKotsev  if you run out of iram you have to deselect one or more features.
Features have been added in many parts so it is possible that a combination of features that worked
with older Tasmota versions now is not possible

**Comment by AleksandarKotsev** [comment]
Dear @Jason2866 im compiling only those features an oviously still running out of iram
![image](https://user-images.githubusercontent.com/67271839/93686854-d1942300-fac1-11ea-9edc-e912aeb6a126.png)

**Comment by Jason2866** [comment]
"Only" you have choosen the biggest features together. Displays and IR full.
The ESP82XX has very limited resources. Your setup needs to be more specific for the use case you need. There is a reason why there are precompiled builds for IR full and Displays.

**Comment by AleksandarKotsev** [comment]
@Jason2866 I'm only using displays because if the i2c since I'm using some i2c sensors. Can I use i2c communication without the displays package?

**Comment by Jason2866** [comment]
Yes, see https://github.com/benzino77/tasmocompiler#how-to-use-custom-parameters
and for more infos read https://tasmota.github.io/docs/Compile-your-build/#customize-your-build

**Comment by AleksandarKotsev** [comment]
I'll give it a try. !0x
