### ISSUE TITLE
Allow Tasmota forks to compile

### ISSUE THREAD

**Issue by schrej-zz** [benzino77/tasmocompiler#9]
There are some interesting forks of Tasmota around, like Stefan Bodes rollershutter fork.
is it possible to implement an option to refer to the source code of another fork_

**Comment by benzino77** [comment]
You could try, I will try to help you.
Please tell me how do you start TasmoCompiler (gitpod, docker, nodejs on local machine)?

**Comment by schrej-zz** [comment]
Thanks,


I start Tasmocompiler via Gitpod Web Interface.


I think, if the "Download Sourcecode" has an option to enter  a URL, it would be sufficient.




Thanks Joerg 




On Sun, Jul 7, 2019 at 6:25 PM +0200, "benzino77" <notifications@github.com> wrote:












You could try, I will try to help you.

Please tell me how do you start TasmoCompiler (gitpod, docker, nodejs on local machine)?

**Comment by benzino77** [comment]
I don't think that it will work. I have just looked at @stefanbode repo and there are some differences with git repo itself (the changes in code are less important than that). @stefanbode does not have `development` branch, and the tags for particular versions of code stops on `v4.1.3`. TasmoCompiler is looking for tags starts with `v6*` or `v7*` and for `development`. But it is still possible I think.

I f you are using gitpod try this steps (this worked for me, but I only check if the result of compile is ok, I have not pushed the binary to the device):
1. start your gitpod workspace
2. close all tabs/windows with TasmoCompiler GUI
3. in the gitpod console (bottom part of the view, where the information _Server started on port 3000_ is displayed) hit ctrl+c
4. type: `cd /tmp`
5. type: `rm -rf Sonoff-Tasmota`
6. type: `git clone https://github.com/stefanbode/Sonoff-Tasmota.git`
7. type: `cd Sonoff-Tasmota`
8. type: `git checkout -b development`
9. type: `cd /workspace/tasmocompiler`
10. type: `node server/server.js`
11. open TasmoCompiler GUI by clicking "Open Browser" (if it didn't open automatically)

The only version of Tasmota which will be available to choose will be `development` - this is the exact copy of `master` branch of @stefanbode code (step 8 above)

You have to remember that on _Select features_ step there will be no @stefanbode features. If you want to customize @stefanbode fork, you have to do this by _Custom parameters_ step.

**Comment by stefanbode** [comment]
Hi benzino, yes the tag stop at 4.1 because this was the initial time where I did do the fork. I continuously update my fork to keep in sync with the master, but for sure the check-in tags will not be synced. Additionally a for will always be MASTER in the first shot.

**Comment by benzino77** [comment]
Hi Stefan,
If your `master` is synced with Theo's `development`, step 8 from the above procedure will do the job, and allow @schrej-zz compile your fork with TasmoCompiler.

There is always possibility to create tags from specific commit (and then they will be available to choose on the last step) or create `development` branch from specific point in time indicated by _Merge branch 'master' of https://github.com/stefanbode/Sonoff-Tasmota_ commit description.

**Comment by schrej-zz** [comment]
Hi,
followed the instruction and worked like a charm. Compiling as well as installed.
Maybe the guide should be added to the wiki.
Thanks for your great support.

**Comment by benzino77** [comment]
Nice to hear it worked for you.
Wiki.... It is already there:
https://github.com/benzino77/tasmocompiler/#troubleshooting-and-advanced-usage
https://github.com/benzino77/tasmocompiler/blob/master/ADVANCED.md#compile-someone-fork-of-tasmota-code
