### ISSUE TITLE
Doesn't build on ARM

### ISSUE THREAD

**Issue by llevi** [benzino77/tasmocompiler#93]
Docker build does not work on arm32 and arm64 neither.

output:

`********************************************************************************
If you like PlatformIO, please:
- follow us on Twitter to stay up-to-date on the latest project news > https://twitter.com/PlatformIO_Org
- star it on GitHub > https://github.com/platformio/platformio
- try PlatformIO IDE for embedded development > https://platformio.org/platformio-ide
********************************************************************************

Processing custom (platform: espressif8266@2.6.2; framework: arduino; board: esp01_1m)
--------------------------------------------------------------------------------
Platform Manager: Installing espressif8266 @ 2.6.2
Platform Manager: espressif8266 @ 2.6.2 has been installed!
The platform 'espressif8266@2.6.2' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing tool-esptoolpy @ ~1.20800.0
Tool Manager: tool-esptoolpy @ 1.20800.0 has been installed!
Tool Manager: Installing toolchain-xtensa @ ~2.40802.191122
Tool Manager: Warning! More than one package has been found by toolchain-xtensa @ ~2.40802.191122 requirements:
 - platformio/toolchain-xtensa @ 2.100100.200706
 - mcspr/toolchain-xtensa @ 5.100200.200918
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Tool Manager: toolchain-xtensa @ 2.40802.200502 has been installed!
Tool Manager: Installing tool-esptool @ <2
Tool Manager: Warning! More than one package has been found by tool-esptool @ <2 requirements:
 - platformio/tool-esptool @ 1.413.0
 - volcas/tool-esptool @ 1.413.1
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Tool Manager: tool-esptool @ 1.413.0 has been installed!
Tool Manager: Installing jason2866/framework-arduinoespressif8266 @ *
Tool Manager: framework-arduinoespressif8266 @ 2.7.4+1 has been installed!
Tool Manager: Installing platformio/tool-scons @ ~4.40001.0
Tool Manager: tool-scons @ 4.40001.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp01_1m.html
PLATFORM: Espressif 8266 (2.6.2) > Espressif Generic ESP8266 ESP-01 1M
HARDWARE: ESP8266 80MHz, 80KB RAM, 1MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 2.7.4+1 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Converting tasmota.ino
sh: 1: xtensa-lx106-elf-g++: not found
*** Error 127
AssertionError: :
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/main.py", line 169:
    env.SConscript("$BUILD_SCRIPT")
  File "/root/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py", line 598:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/root/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Script/SConscript.py", line 287:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/root/.platformio/platforms/espressif8266/builder/main.py", line 238:
    target_elf = env.BuildProgram()
  File "/root/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/tools/platformio.py", line 61:
    env.ProcessProgramDeps()
  File "/root/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/tools/platformio.py", line 127:
    env.BuildFrameworks(env.get("PIOFRAMEWORK"))
  File "/root/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/tools/platformio.py", line 339:
    env.ConvertInoToCpp()
  File "/root/.platformio/packages/tool-scons/scons-local-4.0.1/SCons/Environment.py", line 219:
    return self.method(*nargs, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/tools/piomisc.py", line 239:
    out_file = c.convert(ino_nodes)
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/tools/piomisc.py", line 91:
    return self.process(contents)
  File "/usr/local/lib/python3.5/dist-packages/platformio/builder/tools/piomisc.py", line 112:
    assert self._gcc_preprocess(contents, out_file)
========================= [FAILED] Took 70.92 seconds =========================
Finished. Exit code: 1.
Welcome stranger!
`

**Comment by benzino77** [comment]
Yo don't use latest TasmoCompiler version.

**Comment by llevi** [comment]
Many Thanks, Using the new version really helps.

Btw, the latest tag doesn't work for arm64
`root@rock64:~# docker run --rm benzino77/tasmocompiler
Unable to find image 'benzino77/tasmocompiler:latest' locally
latest: Pulling from benzino77/tasmocompiler
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
See 'docker run --help'.`

**Comment by benzino77** [comment]
It looks like it is a problem with docker manifest.

You can pull new image by `docker pull benzino77/tasmocompiler:arm64v8` and then `docker run <....> benzino77/tasmocompiler:arm64v8`.

I have to look at it closer. I don't have such board on my side, so I will ask you to test my changes.

**Comment by llevi** [comment]
It works with that tag, so was my fault to use the wrong version, thanks.
I will test new manifest, just tell me to try it. My pleasure to help with this awesome project :)

**Comment by benzino77** [comment]
Try to pull it now by `docker pull benzino77/tasmocompiler` on your ARM board.

**Comment by llevi** [comment]
It pulls now on my ARM64 board. Thank you.

**Comment by anonymousaga** [comment]
I had this issue on both my Pi and M1 Mac.

Simple solution: add this to docker command ` --platform linux/amd64 `
Worked on my mac, but not on my pi
